---
sidebar: sidebar 
permalink: br-start-faq.html 
keywords: backup and recovery faq, bluexp backup and recovery frequently asked questions 
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= BlueXP backup and recoveryに関するよくある質問
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== 導入

* BlueXPバックアップおよびリカバリのプレビュー バージョンを使用するにはライセンスが必要ですか?*

次のライセンスタイプを使用できます。

* 30日間の無償トライアルにサインアップしてください。


* BlueXP backup and recoveryを有効にするには？*BlueXP backup and recoveryは有効化の必要はありません。BlueXPの左側のナビゲーションで、バックアップとリカバリのオプションが自動的に有効になります。

このサービスをお試しいただくには、サインアップするか、NetApp営業担当者にお問い合わせください。BlueXP Connectorを使用すると、サービスに適した機能が含まれます。

BlueXP backup and recoveryを開始するには、最初のランディング ページから「ワークロードの検出を開始する」をクリックします。

* BlueXP backup and recoveryは、標準モード、制限モード、プライベート モードで使用できますか? *現時点では、 BlueXP backup and recoveryのプレビュー バージョンは、標準モードでのみ使用できます。今後もご期待ください。

すべてのBlueXP  サービスにおけるこれらのモードの詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXPの導入モード"^]。



== アクセス

* BlueXP backup and recoveryのURL は何ですか?*BlueXP  コンソールにアクセスするには、ブラウザで次のように入力します。 https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/backup-and-recovery"^]

*アクセス権限はどのように処理されますか？*サービスを開始してワークロードを検出できるのは、組織の管理者だけです（これにはリソースの使用をコミットする必要があるため）。その後の対話は、任意の役割で行うことができます。

*どのデバイス解像度が最適ですか？*BlueXP backup and recoveryに推奨されるデバイス解像度は 1920x1080 以上です。

*どのブラウザを使用すればよいですか？*最新のブラウザは機能します。



== 他のサービスとのやり取り

* BlueXP backup and recoveryは、 NetApp ONTAPで行われた保護設定を認識しますか? *はい、 BlueXP backup and recoveryは、 ONTAPで設定されたスナップショット スケジュールを検出します。

* BlueXP backup and recoveryを使用してポリシーを設定した場合、今後の変更はこのサービスでのみ行う必要がありますか? *ポリシーの変更は、BlueXP backup and recoveryサービスから行うことをお勧めします。



== ワークロード

*ワークロードの構成要素*ワークロードとは、Preview 2025 バージョンのアプリケーションです。ワークロードには、単一のアプリケーションインスタンスで使用されるすべてのボリュームが含まれます。例えば、mssql3.host.com にデプロイされた Microsoft SQL Server DB インスタンスには、データ用とログ用としてそれぞれ vol1 と vol2 が存在します。これらのボリュームが組み合わさって、その DB インスタンスのワークロードが構成されます。

* BlueXP backup and recoveryはどのようなワークロードをサポートしますか?*

Preview 2025 バージョンでは、 BlueXP backup and recoveryは次のワークロードを識別できます: Microsoft SQL Server アプリケーション。

*「保護された」ワークロードとは何ですか？*BlueXP backup and recoveryでは、プライマリ検出ポリシーが有効になっている場合、ワークロードは「保護」ステータスを表示します。

*「リスクにさらされている」ワークロードとは何ですか？*ワークロードでプライマリ検出ポリシーが有効になっていない場合は、バックアップポリシーとSnapshotポリシーが有効になっていても「リスク」になります。

*新しいワークロードが追加されましたが、まだ表示されません* 環境に新しいワークロードを追加した場合は、検出を再度開始し、保護ポリシーを適用してその新しいリソースを保護します。



== 保護ポリシー

* BlueXP backup and recoveryは、 NetApp ONTAPで行われた保護設定を認識しますか?*

はい、 BlueXP backup and recoveryは、 ONTAPで設定されたスナップショット スケジュールと、検出されたワークロードで ARP および FPolicy が有効になっているかどうかを検出します。ダッシュボードに最初に表示される情報は、他のNetAppソリューションおよび製品から集約されます。

* BlueXP backup and recoveryは、 SnapCenterですでに作成されているポリシーを認識しますか?*

はい、 SnapCenterで管理されているワークロードがある場合、それらの製品によって管理されているポリシーはBlueXP backup and recoveryに取り込まれます。

* SnapCenterから引き継がれたポリシーを変更できますか?*

はい、 BlueXP backup and recovery内でSnapCenterによって管理されていたポリシーを変更できます。

* ONTAPからのポリシーが存在する場合 (ARP、FPolicy、スナップショットなど、System Manager ですでに有効になっている)、それらはBlueXP backup and recoveryで変更されますか? *

いいえ。BlueXPBlueXP backup and recoveryでは、 ONTAPの既存の検出ポリシー (ARP、FPolicy 設定) は変更されません。

* BlueXP backup and recoveryにサインアップした後、 SnapCenterに新しいポリシーを追加するとどうなりますか?*

BlueXP backup and recoveryは、 SnapCenterで作成された新しいポリシーを認識します。

* ONTAPからポリシーを変更できますか？*

はい、 BlueXP backup and recoveryでONTAPのポリシーを変更できます。また、 BlueXP backup and recoveryで新しいポリシーを作成し、ワークロードに適用することもできます。この操作により、既存のONTAPポリシーがBlueXP backup and recoveryで作成されたポリシーに置き換えられます。
