---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: bluexp, backup, back up, restore, recovery, aws, azure 
summary: BlueXP backup and recoveryを使用する前に、いくつかの手順を実行してバックアップ先を設定します。 
---
= BlueXP backup and recoveryを使用する前にバックアップ先を設定します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP backup and recoveryを使用する前に、いくつかの手順を実行してバックアップ先を設定します。

作業を開始する前に、を参照して、link:concept-start-prereq.html["前提条件"]環境の準備が完了していることを確認してください。



== バックアップ先の準備

次のバックアップ先を 1 つ以上準備します。

* NetAppStorageGRID。
+
を参照してください https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRIDについて知る"^]。

+
参照 https://docs.netapp.com/us-en/storagegrid/index.html["StorageGRID のドキュメント"^]StorageGRIDの詳細については、こちらをご覧ください。

* Amazon Web サービス。を参照してください https://docs.netapp.com/us-en/bluexp-s3-storage/index.html["Amazon S3 ドキュメント"^]。
+
AWS をバックアップ先として準備するには、次の手順を実行します。

+
** AWSでアカウントをセットアップします。
** 次のセクションにリストされている AWS の S3 権限を設定します。
** BlueXP  でのAWSストレージの管理の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["Amazon S3バケットを管理します"^]。




* マイクロソフト アジュール。
+
** を参照してください https://docs.netapp.com/us-en/bluexp-azure-netapp-files/index.html["Azure NetApp Files のドキュメント"^]。
** Azureでアカウントをセットアップします。
** 設定 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Azure権限"^] Azure で。
** BlueXPでAzureストレージを管理する方法の詳細については、以下を参照してください。  https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["Azureストレージアカウントの管理"^] 。




バックアップ先自体のオプションを設定した後、 BlueXP backup and recoveryサービスでバックアップ先として設定します。BlueXPBlueXP backup and recoveryでバックアップ先を設定する方法の詳細については、以下を参照してください。 link:br-start-discover-backup-targets.html["バックアップターゲットの検出"] 。



== S3 権限をセットアップする

AWS S3 権限を 2 セット設定する必要があります。

* S3バケットの作成と管理を行うコネクタの権限。
* オンプレミスの ONTAP クラスタの権限。 S3 バケットに対してデータの読み取りと書き込みを行うことができます。


.手順
. コネクタに必要な権限があることを確認します。詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html["BlueXP  ポリシーの権限"]。
+

NOTE: AWS Chinaリージョンでバックアップを作成する場合は、IAMポリシーのall_Resource_sectionsの下にあるAWSリソース名「arn」を「aws」から「aws-cn」に変更する必要があります `arn:aws-cn:s3:::netapp-backup-*`。

. サービスをアクティブ化すると、バックアップウィザードからアクセスキーとシークレットキーの入力を求められます。これらのクレデンシャルは、 ONTAP がデータをバックアップして S3 バケットにリストアできるように ONTAP クラスタに渡されます。そのためには、以下の権限を持つ IAM ユーザを作成する必要があります。
+
を参照してください https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["AWS ドキュメント：「 Creating a Role to Delegate Permissions to an IAM User"^]。

+
[%collapsible]
====
[source, json]
----
{
    "Version": "2012-10-17",
     "Statement": [
        {
           "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation",
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": "arn:aws:s3:::netapp-backup-*",
            "Effect": "Allow",
            "Sid": "backupPolicy"
        },
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListAllMyBuckets",
                "s3:PutObjectTagging",
                "s3:GetObjectTagging",
                "s3:RestoreObject",
                "s3:GetBucketObjectLockConfiguration",
                "s3:GetObjectRetention",
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutObjectRetention"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*/*",
            "Effect": "Allow"
        }
    ]
}
----
====

