---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Microsoft SQL ServerアプリケーションのデータをオンプレミスのONTAPシステムからAmazon Web Services、Microsoft Azure、 StorageGRIDにバックアップすることで、データを確実に保護できます。3-2-1バックアップは自動的に生成され、パブリックまたはプライベートクラウドアカウントのオブジェクトストアに格納されます。戦略を実装することで、ソースデータの3つのコピーを2つの異なるストレージシステムに、1つのコピーをクラウドに保存できます。 
---
= BlueXP backup and recoveryによる Microsoft SQL ワークロードの保護の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP backup and recoveryを使用して、オンプレミスのONTAPシステムからAmazon Web Services、Microsoft Azure、またはStorageGRIDに至るまで、Microsoft SQL Serverアプリケーションのデータを保護します。バックアップは、作成したポリシーに基づいて自動的に生成され、パブリッククラウドまたはプライベートクラウドアカウントのオブジェクトストアに保存されます戦略を実装することで、ソースデータの3つのコピーを2つの異なるストレージシステムに、1つのコピーをクラウドに保持できます。

3-2-1アプローチの利点は次のとおりです。

* 複数のデータコピーを使用して、内部（内部）と外部のサイバーセキュリティの脅威に対する多層保護を実現します。
* 複数のメディアタイプにより、1つのメディアタイプの物理的または論理的な障害が発生した場合でもフェイルオーバーを実行できます。
* オンサイト コピーにより迅速な復元が可能になり、オンサイト コピーが侵害された場合に備えてオフサイト コピーも利用できます。


BlueXP backup and recoveryは、 NetApp SnapMirrorデータ レプリケーション テクノロジを活用して、スナップショット コピーを作成し、それをバックアップ場所に転送することで、すべてのバックアップが完全に同期されるようにします。

次の保護目標を達成できます。

* link:concept-start-prereq-snapcenter-import.html["SnapCenterからインポートする場合の追加項目を構成する"]
* link:br-start-discover.html["Microsoft SQL Server ワークロードを検出し、オプションでSnapCenterリソースをインポートします"]
* link:br-use-mssql-backup.html["ローカルONTAPプライマリ ストレージ上のローカル スナップショットを使用してワークロードをバックアップします。"]
* link:br-use-mssql-backup.html["ワークロードをONTAPセカンダリストレージに複製する"]
* link:br-use-mssql-backup.html["ワークロードをオブジェクトストアの場所にバックアップする"]
* link:br-use-mssql-backup.html["今すぐワークロードをバックアップ"]
* link:br-use-mssql-restore-overview.html["ワークロードの復元"]
* link:br-use-mssql-clone.html["クローンワークロード"]
* link:br-use-manage-inventory.html["ワークロードのインベントリを管理する"]
* link:br-use-manage-snapshots.html["Snapshotの管理"]


ワークロードをバックアップするには、通常、バックアップおよび復元操作を管理するポリシーを作成します。詳細については、を参照してください link:br-use-policies-create.html["ポリシーの作成"] 。

.サポートされるバックアップ先
BlueXP backup and recoveryを使用すると、Microsoft SQL Server インスタンスとデータベースを次のソース作業環境から次のセカンダリ作業環境およびパブリックおよびプライベート クラウド プロバイダーのオブジェクト ストレージにバックアップできます。Snapshotコピーはソースの作業環境に配置されます。

[cols="33,33,33"]
|===
| ソースの作業環境 | セカンダリ作業環境（レプリケーション） | デスティネーションオブジェクトストア（バックアップ） 


| AWS の Cloud Volumes ONTAP | AWS の Cloud Volumes ONTAP
オンプレミスの ONTAP システム | Amazon S3 


| Azure の Cloud Volumes ONTAP | Azure の Cloud Volumes ONTAP
オンプレミスの ONTAP システム | Azure Blob の略 


| オンプレミスの ONTAP システム | Cloud Volumes ONTAP
オンプレミスの ONTAP システム | Amazon S3 Azure Blob NetApp StorageGRID ifdef::gcp[] endif::gcp[] ifdef::gcp[] endif::gcp[] 
|===
.サポートされるリストア先
プライマリ ストレージまたはセカンダリ作業環境 (複製されたボリューム) またはオブジェクト ストレージ (バックアップ ファイル) にあるバックアップから、Microsoft SQL Server インスタンスとデータベースを次の作業環境に復元できます。Snapshotコピーはソースの作業環境に存在し、同じシステムにのみリストアできます。

[cols="33,33,33"]
|===
2+| バックアップファイルの場所から | デスティネーションの作業環境へ 


| *オブジェクトストア（バックアップ）* | *セカンダリシステム（レプリケーション）* |  


| Amazon S3 | AWS の Cloud Volumes ONTAP
オンプレミスの ONTAP システム | AWSオンプレミスONTAPシステムのクラウドボリューム 


| Azure Blob の略 | Azure の Cloud Volumes ONTAP
オンプレミスの ONTAP システム | Azure のCloud Volumes ONTAPオンプレミスONTAPシステム ifdef::gcp[] endif::gcp[] 


| StorageGRID | Cloud Volumes ONTAP
オンプレミスの ONTAP システム | オンプレミスの ONTAP システム 
|===

NOTE: 「オンプレミスのONTAPシステム」への参照には、 FASとAFFシステムが含まれます。
