---
sidebar: sidebar 
permalink: br-use-restore-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: BlueXP backup and recoveryと、保護ポリシーで保護したアプリケーションを復元できます。 
---
= Kubernetesアプリケーションの復元
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP backup and recoveryを使用すると、保護ポリシーで保護したアプリケーションを復元できます。アプリケーションを復元するには、アプリケーションの保護ステータスが「保護」に設定され、保護ポリシーが関連付けられている必要があります。アプリケーションの復元には、ローカル スナップショット、セカンダリ スナップショット、およびオブジェクト ストアへのバックアップで構成される復元ポイントを使用します。アプリケーションは、ローカル アーカイブ、セカンダリ アーカイブ、またはオブジェクト ストア アーカイブを使用して復元できます。

.必要なBlueXPロール
組織管理者またはSnapCenter管理者。link:reference-roles.html["BlueXP backup and recoveryのアクセス ロールについて学ぶ"] 。  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["すべてのサービスに対するBlueXPのアクセスロールについて学ぶ"^] 。

.手順
. BlueXP backup and recoveryで、*インベントリ*を選択します。
. Kubernetes ワークロードを選択し、そのワークロードの [ホスト] 列で [*表示*] を選択します。
. アプリケーションのリストで、復元するアプリケーションを選択し、関連する [アクション] メニューを選択します。
. *表示と復元*を選択します。
+
復元ポイントのリストが表示されます。

. 使用する復元ポイントの「アクション」メニューを開き、「復元」を選択します。


[discrete]
===== 一般設定

. 復元元のソース (ローカル、セカンダリ、またはオブジェクト ストア) を選択します。
. *クラスター* リストから宛先クラスターを選択します。
. 復元先の名前空間 (元の名前空間または新規の名前空間) を選択します。
+
別のクラスターおよび元の名前空間への復元はサポートされていないことに注意してください。

. 「 * 次へ * 」を選択します。


[discrete]
===== リソースの選択

. アプリケーションに関連付けられているすべてのリソースを復元するか、フィルターを使用して復元する特定のリソースを選択するかを選択します。


[role="tabbed-block"]
====
.すべてのリソースを復元する
--
. [すべてのリソースをリストア]*を選択します。
. 「 * 次へ * 」を選択します。


--
.特定のリソースを復元する
--
. *選択的リソース*を選択します。
. リソースフィルターの動作を選択します。*含める*を選択した場合、選択したリソースが復元されます。*除外*を選択した場合、選択したリソースは復元されません。
. リソースを選択するためのフィルターを定義するルールを追加するには、「ルールを追加」を選択します。リソースをフィルタリングするには、少なくとも1つのルールが必要です。
+
各ルールは、リソースの名前空間、ラベル、グループ、バージョン、種類などの基準でフィルタリングできます。

. 各ルールを保存するには、[保存] を選択します。
. 必要なルールをすべて追加したら、「*検索*」を選択して、フィルター条件に一致するバックアップ アーカイブ内の利用可能なリソースを表示します。
. 結果に満足したら、[次へ] を選択します。


--
====
[discrete]
===== 宛先設定

. デフォルトのストレージ クラスに復元するか、別のストレージ クラスに復元するかを選択します。
. オプションで、別のストレージクラスに復元することを選択した場合は、各ソースストレージクラスに対応する宛先ストレージクラスを選択します。宛先ストレージクラスは、宛先クラスターで使用可能である必要があります。
. [* Restore] を選択します。

