---
sidebar: sidebar 
permalink: br-use-settings-advanced.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: バックアップおよびリカバリ環境の維持には、いくつかの詳細設定が役立つ場合があります。詳細設定では、インベントリの管理、バックアップの削除、リソースの登録解除、リレーションシップの削除、サービス料金の停止のためのリソースの保護解除、 SnapMirrorリレーションシップの最大転送速度の設定、スナップショットのコピーのオブジェクトストアへのエクスポート、年次スナップショットの自動削除の有効化、メンテナンスモードの有効化、アプリケーションプラグインの更新などを行うことができます。 
---
= BlueXP backup and recoveryの詳細設定を構成する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
バックアップおよびリカバリ環境の維持には、いくつかの詳細設定が役立つ場合があります。詳細設定では、インベントリの管理、バックアップの削除、リソースの登録解除、リレーションシップの削除、サービス料金の停止のためのリソースの保護解除、 SnapMirrorリレーションシップの最大転送速度の設定、スナップショットのコピーのオブジェクトストアへのエクスポート、年次スナップショットの自動削除の有効化、メンテナンスモードの有効化、アプリケーションプラグインの更新などを行うことができます。

BlueXP backup and recoveryの詳細設定を次の方法で構成します。

* バックアップを削除します。
* バックアップ、データベース、インスタンス、またはアプリケーション ホストを登録解除します。
* 関係を削除します。
* データベース、インスタンス、アプリケーション ホスト、および作業環境の保護を解除して、サービス料金を停止します。
* SnapMirror関係の最大転送速度を設定し、帯域幅の使用を管理して、 SnapMirror操作が他のネットワーク アクティビティに干渉しないようにします。
* スナップショット コピーをオブジェクト ストアにエクスポートし、古いスナップショット コピーをベースライン バックアップ コピーに移動して、クラウド内のバックアップを初期化します。
* 毎年のスナップショットの自動削除を有効にする
* 更新またはメンテナンス タスクを実行できるように、メンテナンス モードを有効にします。
* アプリケーションプラグインを更新します。




== バックアップを削除します

バックアップを削除してストレージのスペースを解放することができます。

. BlueXP backup and recoveryコンソールで、[**設定**] を選択します。
. **詳細設定**を選択します。
. **バックアップを削除** を選択します。
. 削除するバックアップを選択します。
. **削除**を選択します。




== バックアップ、データベース、インスタンス、またはアプリケーションホストの登録を解除する

バックアップ、データベース、インスタンス、またはアプリケーション ホストを登録解除して、インベントリから削除できます。

. BlueXP backup and recoveryコンソールで、[**設定**] を選択します。
. **詳細設定**を選択します。
. **リソースの登録解除**を選択します。
. 登録解除するリソースを選択します。
. **登録解除**を選択します。




== 関係を削除します

関係を削除して、インベントリから削除することができます。

. BlueXP backup and recoveryコンソールで、[**設定**] を選択します。
. **詳細設定**を選択します。
. **関係を削除** を選択します。
. 削除する関係を選択します。
. **削除**を選択します。




== データベース、インスタンス、アプリケーションホスト、作業環境の保護を解除します

データベース、インスタンス、アプリケーション ホスト、および作業環境の保護を解除して、サービス料金を停止できます。

. BlueXP backup and recoveryコンソールで、[**設定**] を選択します。
. **詳細設定**を選択します。
. **リソースの保護を解除** を選択します。




== SnapMirror関係の最大転送速度を設定する

SnapMirror関係の最大転送速度を設定して帯域幅の使用を管理し、 SnapMirror操作が他のネットワーク アクティビティに干渉しないようにすることができます。

. BlueXP backup and recoveryコンソールで、[**設定**] を選択します。
. **詳細設定**を選択します。
. ** SnapMirror関係の最大転送速度を設定する** を選択します。
. 最大転送速度を入力します。
. **保存**を選択します。




== スナップショットのコピーをオブジェクトストアにエクスポートする

スナップショット コピーをオブジェクト ストアにエクスポートし、古いスナップショット コピーをベースライン バックアップ コピーに移動することで、クラウド内のバックアップを初期化できます。

. BlueXP backup and recoveryコンソールで、[**設定**] を選択します。
. **詳細設定**を選択します。
. **スナップショットのコピーをオブジェクト ストアにエクスポート** を選択します。
. エクスポートするスナップショットのコピーを選択します。
. **エクスポート**を選択します。




== 毎年のスナップショットの自動削除を有効にする

毎年のスナップショットの自動削除を有効にして、1 年以上経過したスナップショットを削除できます。

. BlueXP backup and recoveryコンソールで、[**設定**] を選択します。
. **詳細設定**を選択します。
. **毎年のスナップショットの自動削除を有効にする** を選択します。
. **有効にする**を選択します。




== メンテナンスモードを有効にします

メンテナンス モードを有効にすると、更新やメンテナンス タスクを実行できるようになります。

. BlueXP backup and recoveryコンソールで、[**設定**] を選択します。
. **詳細設定**を選択します。
. **メンテナンス モードを有効にする** を選択します。
. **有効にする**を選択します。




== アプリケーションプラグインを更新する

アプリケーション プラグインを更新して、最新の機能を確実に利用できるようになります。

. BlueXP backup and recoveryコンソールで、[**設定**] を選択します。
. **詳細設定**を選択します。
. **アプリケーションプラグインの更新**を選択します。
. **更新**を選択します。

