---
sidebar: sidebar 
permalink: concept-clone-cloud-native-oracle-concepts.html 
keywords: cloud native, application data, clone, Cloud Manager, BlueXP, Oracle database, Oracle, clone limitations, clone methods, clone naming scheme, requirements, clone specification file 
summary: データベースをクローニングする前に、クローンの概念を確認しておきます。 
---
= クローンの概念と要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
データベースのバックアップを使用して、ソースデータベースホストまたは代替ホストにOracleデータベースをクローニングすることができます。バックアップはプライマリストレージシステムからクローニングできます。

データベースをクローニングする前に、クローンの概念を理解し、すべての要件を満たしていることを確認する必要があります。



== Oracle データベースをクローニングするための要件

Oracle データベースをクローニングする前に、前提条件を満たしていることを確認する必要があります。

* データベースのバックアップを作成しておく必要があります。クローニング処理を正常に実行するには、オンラインデータとログバックアップが正常に作成されている必要があります。
* asm_diskstringパラメータでは、次の設定を行う必要があります。
+
** AFD：* ASMFDを使用している場合
** ORCL:* ASMlibを使用している場合
** ASMUDEV <exact_device_location> を使用している場合は/dev/ASMUDEVを使用します


* 代替ホストでクローンを作成する場合、代替ホストは次の要件を満たす必要があります。
+
** プラグインは代替ホストにインストールする必要があります。
** Oracleソフトウェアは代替ホストにインストールする必要があります。
** iSCSI SANストレージ上にあるデータベースのクローニングを行う場合は、クローンホストでストレージからLUNを検出できる必要があります。代替ホストにクローニングする場合は、ストレージと代替ホストの間にiSCSIセッションが確立されていることを確認します。
** ソースデータベースが ASM データベースの場合は、次の手順を実行します。
+
*** クローンを実行するホスト上で、 ASM インスタンスが稼働している必要があります。
*** クローニングしたデータベースのアーカイブログファイルを専用のASMディスクグループに配置する場合は、クローン処理の前にASMディスクグループをプロビジョニングする必要があります。
*** データディスクグループの名前は設定できますが、クローンを実行するホスト上の他のASMディスクグループに名前が使用されていないことを確認してください。
*** ASMディスクグループにあるデータファイルは、クローンワークフローの一環としてプロビジョニングされます。








== 制限

* qtreeにあるデータベースのクローニングはサポートされていません。
* クローンデータベースのバックアップはサポートされていません。




== クローンメソッド

基本的な方法またはクローン仕様ファイルを使用して、クローンを作成できます。



=== 基本的な方法でクローニングします

ソースデータベースと選択したバックアップを基に、デフォルトの設定でクローンを作成できます。

* データベースパラメータ、ホーム、およびOSユーザは、デフォルトでソースデータベースに設定されます。
* データファイルパスの名前は、選択した名前スキームに基づいて決まります。
* プリスクリプト、ポストスクリプト、およびSQLステートメントは指定できません。
* リカバリ・オプションは'デフォルトでは* Until cancel *であり'データ・バックアップに関連付けられたログ・バックアップをリカバリに使用します




=== 仕様ファイルを使用してクローニングする

クローン仕様ファイルで設定を定義し、それを使用してデータベースをクローニングできます。仕様ファイルをダウンロードし、要件に合わせて変更してから、ファイルをアップロードできます。 link:task-clone-cloud-native-oracle-data.html["詳細はこちら。"]。

仕様ファイルに定義されているさまざまなパラメーターと、変更可能なパラメーターは次のとおりです。

|===
| パラメータ | 説明 


 a| 
control_files
 a| 
クローンデータベースの制御ファイルの場所。

制御ファイルの数はソースデータベースと同じになります。制御ファイルのパスを無効にする場合は、別の制御ファイルのパスを指定します。ファイルシステムまたはASMディスクグループがホストに存在する必要があります。



 a| 
REDOログ
 a| 
REDOログの場所、サイズ、Redoグループの数。

データベースをクローニングするには、少なくとも 2 つの REDO ロググループが必要です。REDOログファイルのパスを上書きする場合は、ソースデータベースとは別のファイルシステムにREDOログファイルのパスをカスタマイズできます。ファイルシステムまたはASMディスクグループはホストに存在する必要があります。



 a| 
ORACLE_VERSION
 a| 
ターゲット・ホスト上のOracleのバージョン。



 a| 
ORACLE_HOMEを参照してください
 a| 
ターゲット・ホストのOracleホーム



 a| 
enable_archive_log_mode
 a| 
クローンデータベースのアーカイブログモードを制御します



 a| 
databE_parameters
 a| 
クローンデータベースのデータベースパラメータ



 a| 
SQL_statements
 a| 
クローニング後にデータベースで実行するSQLステートメント



 a| 
os_user_detail
 a| 
ターゲットクローンデータベースのOracle OSユーザ



 a| 
databa_port
 a| 
ホストでOS認証が無効な場合に、データベースとの通信に使用するポート。



 a| 
asm_portのようになります
 a| 
Create Clone入力にクレデンシャルが指定されている場合に、ASMデータベースとの通信に使用するポート。



 a| 
skip_recovery
 a| 
はリカバリ処理を実行しません。



 a| 
Until SCN
 a| 
指定したSystem Change Number（SCN）までデータベースをリカバリします。



 a| 
until _ time
 a| 
指定した日時までデータベースをリカバリします。

指定できる形式は、_mm/dd/yyyy hh：mm：ss_です。



 a| 
until _ cancel
 a| 
クローニング対象として選択したデータバックアップに関連付けられたログバックアップをマウントすることでリカバリできます。

クローンデータベースは、欠落または破損したログファイルまでリカバリされます。



 a| 
LOG_PATHS
 a| 
クローンデータベースのリカバリに使用するアーカイブログパスの追加場所。



 a| 
source_locationのコマンドを使用します
 a| 
ソースデータベースホスト上のディスクグループまたはマウントポイントの場所。



 a| 
clone_location
 a| 
ソースの場所に対応するターゲットホストに作成する必要があるディスクグループまたはマウントポイントの場所。



 a| 
location_type
 a| 
asm_diskgroupまたはmountpointを指定できます。

値は、ファイルのダウンロード時に自動的に入力されます。このパラメータは編集しないでください。



 a| 
pre_script
 a| 
クローンを作成する前にターゲットホストで実行するスクリプト。



 a| 
post_script
 a| 
クローン作成後にターゲットホストで実行するスクリプト。



 a| 
パス
 a| 
クローンホスト上のスクリプトの絶対パス。

スクリプトは、/var/opt/snapcenter/spl/scriptsまたはこのパス内の任意のフォルダに保存してください。



 a| 
タイムアウト
 a| 
ターゲットホストで実行されているスクリプトに対して指定されたタイムアウト時間。



 a| 
引数
 a| 
スクリプトに指定された引数。

|===


== クローンの命名方式

クローンの命名スキームは、マウントポイントの場所と、クローニングされたデータベースのディスクグループの名前を定義します。「*同一*」または「*自動生成*」のいずれかを選択できます。



=== 同一の命名方式

クローンの命名方式として「* identical *」を選択した場合、クローニングされたデータベースのマウントポイントの場所とディスクグループの名前は、ソースデータベースと同じになります。

たとえば、ソースデータベースのマウントポイントが、クローンデータベースの________oursourcedb/data_1、+DATA1_DG_である場合、SANのNFSとASMの両方のマウントポイントは同じままです。

* 制御ファイルやREDOファイルの数やパスなどの構成はソースと同じになります。
+

NOTE: REDOログまたは制御ファイルのパスがデータボリューム以外に存在する場合は、ターゲットホストにASMディスクグループまたはマウントポイントをプロビジョニングしておく必要があります。

* Oracle OSユーザとOracleバージョンはソースデータベースと同じになります。
* クローンストレージボリューム名は、sourceVolNameSCS_Clone_CurrentTimeStampNumberという形式になります。
+
たとえば、ソースデータベース上のボリューム名が_sourceVolName_の場合、クローンボリューム名は_sourceVolNameSCS_Clone_1661420020304608825_になります。

+

NOTE: CurrentTimeStampNumber_はボリューム名に一意性を示します。





=== 自動生成される命名方式

クローニングスキームとして*自動生成*を選択した場合、マウントポイントの場所とクローニングされたデータベースのディスクグループの名前にはサフィックスが付加されます。

* 基本的なクローニング方法を選択した場合、接尾辞に*クローンSID *が付加されます。
* 仕様ファイル方式を選択した場合、クローン仕様ファイルのダウンロード時に指定した*サフィックス*がサフィックスとして付加されます。


たとえば、ソースデータベースのマウントポイントが_/NetApp_sourcedb/data_1_and the * Clone SID * or * Suffix * is_HR_の場合、クローンデータベースのマウントポイントは_/NetApp_sourcedb/data_1_HR_に なります。

* 制御ファイルとREDOログファイルの数がソースと同じになります。
* すべてのREDOログファイルと制御ファイルは、クローニングされたデータマウントポイントまたはデータASMディスクグループのいずれかに配置されます。
* クローンストレージボリューム名は、sourceVolNameSCS_Clone_CurrentTimeStampNumberという形式になります。
+
たとえば、ソースデータベース上のボリューム名が_sourceVolName_の場合、クローンボリューム名は_sourceVolNameSCS_Clone_1661420020304608825_になります。

+

NOTE: CurrentTimeStampNumber_はボリューム名に一意性を示します。

* NASマウントポイントの形式は、_SourceNASMountPoint_suffix_です。
* ASMディスクグループの形式は、_SourceDiskgroup_suffix_です。
+

NOTE: クローンディスクグループ内の文字数が25文字を超える場合は、_SC_hashCode_suffix_が付けられます。





== データベースパラメータ

次のデータベース・パラメータの値は、クローンの命名方式に関係なく、ソース・データベースの値と同じになります。

* LOG_ARCH_FORMATの略
* audit_trail
* プロセス
* PGAアグリゲート・ターゲット
* remote_login_passwordfileを指定します
* undo_tablespace
* オープンカーソル
* SGAターゲット
* DB_BLOBK_SIZE


次のデータベースパラメータの値には、クローンのSIDに基づくサフィックスが付加されます。

* audit_file_dest =｛sourcedatabase-parameteralue｝サフィックス
* LOG_ARCHIVE _ dest_1 =｛sourcedatabase-oraclehome｝サフィックス




== 特定のプリスクリプトとポストスクリプトのクローニングでサポートされる事前定義された環境変数

データベースのクローニングの実行時にプリスクリプトとポストスクリプトを実行する場合は、サポートされる事前定義された環境変数を使用できます。

* sc_original_SIDには、ソースデータベースのSIDを指定します。このパラメータは、アプリケーションボリュームに対して入力されます。例： NFSB32
* sc_original_hostは、ソースホストの名前を指定します。このパラメータは、アプリケーションボリュームに対して入力されます。例： asmrac1.gdl.englab.netapp.com
* SC_ORACLE_HOMEは'ターゲット・データベースのOracleホーム・ディレクトリのパスを指定します例： /ora01/app/oracle/product/18.1.0/db_1
* sc_backup_nameには、バックアップの名前を指定します。このパラメータは、アプリケーションボリュームに対して入力されます。例
+
** データベースがARCHIVELOGモードで実行されていない場合：DATA @RG2_scspr2417819002_07-020-202021 _ 116.9267_0 | LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267 _1
** データベースがARCHIVELOGモードで実行されている場合：DATA @RG2_scspr2417819002_07-020-20-220_1120_116.9267_0 | LOG @RG2_scspr2417819002_07-07-20-20-220_112_112.16.48.9267_1、Rg2_scspr24002_06_24002_0.262.16002_0.262.16002_0.7_2.168.262.162.168.261_2.24002_0.21_2.168.262.168.262.168.262_0.7_2.24002_0.262.168.


* sc_original_os_userは、ソースデータベースのオペレーティングシステム所有者を指定します。例： oracle
* sc_original_os_groupは、ソースデータベースのオペレーティングシステムグループを指定します。例： oinstall
* sc_target_SIDには、クローンデータベースのSIDを指定します。PDB クローンワークフローの場合、このパラメータの値は事前定義されていません。このパラメータは、アプリケーションボリュームに対して入力されます。例： clonedb
* sc_target_hostは、データベースをクローニングするホストの名前を指定します。このパラメータは、アプリケーションボリュームに対して入力されます。例： asmrac1.gdl.englab.netapp.com
* sc_target_os_userは、クローンデータベースのオペレーティングシステムの所有者を指定します。PDB クローンワークフローの場合、このパラメータの値は事前定義されていません。例： oracle
* sc_target_os_groupには、クローンデータベースのオペレーティングシステムグループを指定します。PDB クローンワークフローの場合、このパラメータの値は事前定義されていません。例： oinstall
* sc_target_db_portは、クローンデータベースのデータベースポートを指定します。PDB クローンワークフローの場合、このパラメータの値は事前定義されていません。例： 1521




=== サポートされるデリミタ

* @は、データベース名からデータを分離し、キーから値を分離するために使用されます。例：data@RG2_scspr2417819002_07-08-202021 _116.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267 _1
* |は、SC_backup_nameパラメータに2つのエンティティ間でデータを分離するために使用します。例：DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267 _0 | LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267 _1
* は、同じキーに対して一連の変数を区切るために使用します。例：data@RG2_scspr2417819002_07-02-20-20-220_116.9267_0|log@RG2_scspr2417819002_07-07-20-20-220_116.9267_1, RG2_scspr2417819002_07-02-21-2202.16_222.168.261_222.168.262_002_0.24002_0.262_0.261_2.168.262_0.172.168.262_0.264_002_0.172.168.262_0.7_122_0.262_0.262_0.262_0.262_0.262_

