---
sidebar: sidebar 
permalink: prev-reference-aws-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: BlueXPのバックアップとリカバリは、2つのS3アーカイブストレージクラスとほとんどのリージョンをサポートしています。 
---
= BlueXP backup and recoveryでサポートされている AWS アーカイブ ストレージ層
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPのバックアップとリカバリは、2つのS3アーカイブストレージクラスとほとんどのリージョンをサポートしています。

[]
====
*注意* BlueXP backup and recoveryUIのバージョンを切り替えるには、 link:br-start-switch-ui.html["以前のBlueXP backup and recoveryUIに切り替える"] 。

====


== BlueXPのバックアップとリカバリでサポートされるS3アーカイブストレージクラス

バックアップファイルが最初に作成されるときは、 S3_Standard_storage に格納されています。この階層は、アクセス頻度の低いデータを格納するために最適化されていますが、すぐにアクセスすることもできます。30 日経過すると、バックアップは S3_Standard - Infrequent Access_storage クラスに移行してコストを削減します。

ソースクラスタで ONTAP 9.10.1 以降が実行されている場合は、特定の日数（通常は 30 日以上）が経過したあとに S3 Glacier Deep Archive_storage にバックアップを階層化して、コストをさらに最適化することができます。これを「0」または1～999日に設定できます。「0」日に設定した場合、後で1～999日に変更することはできません。

これらの階層のデータは、必要なときにすぐにアクセスすることはできず、取得コストが高くなるため、アーカイブされたバックアップファイルからデータをリストアする頻度を考慮する必要があります。アーカイブストレージからのデータのリストアについては、このページのセクションを参照してください。

* BlueXPのバックアップとリカバリをアクティブ化するときに最初のバックアップポリシーでアーカイブ階層を選択しない場合は、以降のポリシーでは_S3 Glacier_のみがアーカイブオプションになります。
* 最初のバックアップポリシーで_S3 Glacier_を選択した場合は、そのクラスタの以降のバックアップポリシー用に_S3 Glacier Deep Archive_tierに変更できます。
* 最初のバックアップポリシーで_S3 Glacier Deep Archive_を 選択した場合は、その階層がそのクラスタの今後のバックアップポリシーで使用できる唯一のアーカイブ階層になります。


このタイプのライフサイクルルールを使用してBlueXPのバックアップとリカバリを設定する場合は、AWSアカウントでバケットをセットアップするときにライフサイクルルールを設定しないでください。

https://aws.amazon.com/s3/storage-classes/["S3 ストレージクラスについて説明します"^]。



== アーカイブストレージからデータをリストア

古いバックアップファイルをアーカイブストレージに保存すると、標準または標準の IA ストレージよりもはるかに低コストですが、リストア処理のためにアーカイブストレージ内のバックアップファイルからデータにアクセスすると、時間がかかり、コストがかかります。

Amazon S3 Glacier と Amazon S3 Glacier Deep Archive からデータをリストアするのにどれくらいのコストがかかりますか。:: Amazon S3 Glacier からデータを読み出すときは 3 つのリストア優先度を選択でき、 Amazon S3 Glacier Deep Archive からデータを読み出すときは 2 つのリストア優先度を選択できます。S3 Glacier Deep Archive のコストは S3 Glacier よりも低く：
+
--
[cols="25,25,25,25"]
|===
| アーカイブ階層 3+| 優先度とコストを復元します 


|  | * 高 * | * 標準 * | * 低 * 


| * S3 Glacier * | 高速な読み出し、コストの最大化 | 取得速度が低下し、コストが削減されます | 読み出しに時間がかかり、コストを最小限に抑えます 


| * S3 Glacier Deep Archive * |  | 高速な読み出し、コストの増大 | 取得速度が遅く、コストが最も低い 
|===
各メソッドには、 GB 単位の取得料金とリクエストごとの料金が異なります。AWS リージョン別の S3 Glacier の詳細な価格設定については、を参照してください https://aws.amazon.com/s3/pricing/["Amazon S3 の価格設定ページ"^]。

--
Amazon S3 Glacier にアーカイブされているオブジェクトのリストアにはどれくらいの時間がかかりますか。:: リストアの合計時間は、次の 2 つの要素で構成されます。
+
--
* * 取得時間 * ：アーカイブからバックアップファイルを取得して標準ストレージに保存する時間。これは、「水和」時間と呼ばれることもあります。取得時間は、選択したリストア優先度によって異なります。
+
[cols="25,20,20,20"]
|===
| アーカイブ階層 3+| 優先度と取得時間のリストア 


|  | * 高 * | * 標準 * | * 低 * 


| * S3 Glacier * | 3 ～ 5 分 | 3 ～ 5 時間 | 5～12時間 


| * S3 Glacier Deep Archive * |  | 12時間 | 48時間 
|===
* * リストア時間 * ： Standard ストレージのバックアップファイルからデータをリストアする時間。アーカイブ層を使用しない場合、この時間は標準ストレージから直接実行される通常のリストア処理と同じです。


Amazon S3 Glacier と S3 Glacier Deep Archive の読み出しオプションの詳細については、を参照してください https://aws.amazon.com/s3/faqs/#Amazon_S3_Glacier["これらのストレージクラスに関する Amazon FAQ"^]。

--

