---
sidebar: sidebar 
permalink: prev-vmware-register-snapcenter.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp BlueXP backup and recoveryを使用して VMware ワークロードを保護します。 
---
= BlueXP backup and recoveryで使用するためにSnapCenter Plug-in for VMware vSphereを登録します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
データストアと仮想マシンを表示するには、BlueXP バックアップおよびリカバリで VMware vSphere ホスト用の SnapCenter プラグインを登録する必要があります。SnapCenter Plug-in for VMware vSphereホストを登録できるのは、管理者アクセス権を持つユーザだけです。

[]
====
*注意* BlueXP backup and recoveryのワークロードを切り替えるには、 link:br-start-switch-ui.html["さまざまなBlueXP backup and recoveryワークロードに切り替える"] 。

====
.手順
. BlueXP UI で、*保護* > *バックアップとリカバリ* > *仮想マシン* を選択します。
. *設定* ドロップダウンから、* SnapCenter Plug-in for VMware vSphere* を選択します。
. * SnapCenter Plug-in for VMware vSphereの登録*を選択します。
. 次の情報を指定します。
+
.. SnapCenter Plug-in for VMware vSphereフィールドで、SnapCenter Plug-in for VMware vSphereホストのFQDNまたはIPアドレスを指定します。
.. [ポート]フィールドで、SnapCenter Plug-in for VMware vSphereホストが実行されているポート番号を指定します。
+
デフォルトの8144ポートで実行されているオンプレミスのSnapCenter Plug-in for VMware vSphereホストと、任意のクラウドプロバイダ（Amazon Web Services、Microsoft Azure、Google Cloud Platform）またはオンプレミスで実行されているBlueXPコネクタインスタンスの間で通信が開かれていることを確認する必要があります。

.. [Username]フィールドと[Password]フィールドに、管理者ロールを持つvCenterユーザのクレデンシャルを指定します。


. [*Register] を選択します。


* 終了後 *

*バックアップとリカバリ* > *仮想マシン* を選択して、登録済みのSnapCenter Plug-in for VMware vSphereを使用して保護されているすべてのデータストアと仮想マシンを表示します。
