---
settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: クラウドプロバイダ
    default: すべてのクラウドプロバイダ
    options:
    - name: Amazon Web Services の
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: BlueXPのバックアップとリカバリのドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/whats-new.html"
    - title: 既知の制限
      url: "/reference-limitations.html"
  - title: はじめに
    entries:
    - title: BlueXPのバックアップとリカバリについて説明します
      url: "/concept-backup-to-cloud.html"
    - title: ライセンスをセットアップする
      url: "/task-licensing-cloud-backup.html"
  - title: データ保護を監視
    entries:
    - title: データ保護の適用範囲に関するレポートを作成します
      url: "/task-report-inventory.html"
    - title: バックアップジョブとリストアジョブのステータスを監視します
      url: "/task-monitor-backup-jobs.html"
  - title: ONTAP データのバックアップとリストア
    entries:
    - title: ONTAP ボリュームのデータを保護
      url: "/concept-ontap-backup-to-cloud.html"
    - title: 保護対策を計画しましょう
      url: "/concept-protection-journey.html"
    - title: ONTAPボリュームのポリシーを管理します。
      url: "/task-create-policies-ontap.html"
    - title: オブジェクトへのバックアップポリシーのオプション
      url: "/concept-cloud-backup-policies.html"
    - title: "[Advanced Settings]でオブジェクトへのバックアップオプションを管理します。"
      url: "/task-manage-backup-settings-ontap.html"
    - title: Cloud Volumes ONTAP を Amazon S3 にバックアップします
      flavor: aws
      url: "/task-backup-to-s3.html"
    - title: Cloud Volumes ONTAP を Azure Blob にバックアップ
      flavor: azure
      url: "/task-backup-to-azure.html"
    - title: Cloud Volumes ONTAP を Google Cloud にバックアップ
      flavor: gcp
      url: "/task-backup-to-gcp.html"
    - title: オンプレミスの ONTAP から Amazon S3 へのバックアップ
      flavor: aws
      url: "/task-backup-onprem-to-aws.html"
    - title: オンプレミスの ONTAP を Azure Blob にバックアップ
      flavor: azure
      url: "/task-backup-onprem-to-azure.html"
    - title: オンプレミスの ONTAP から Google Cloud へのバックアップ
      flavor: gcp
      url: "/task-backup-onprem-to-gcp.html"
    - title: オンプレミスのONTAPをONTAP S3にバックアップ
      url: "/task-backup-onprem-to-ontap-s3.html"
    - title: オンプレミスの ONTAP を StorageGRID にバックアップ
      url: "/task-backup-onprem-private-cloud.html"
    - title: ONTAP バックアップを管理します
      url: "/task-manage-backups-ontap.html"
    - title: ONTAP バックアップからリストアする
      url: "/task-restore-backups-ontap.html"
  - title: オンプレミスのアプリケーションデータのバックアップとリストア
    entries:
    - title: オンプレミスアプリケーションのデータを保護
      url: "/concept-protect-app-data-to-cloud.html"
    - title: SnapCenter サーバを登録します
      url: "/task-register-snapcenter-server.html"
    - title: アプリケーションをバックアップするポリシーを作成する
      url: "/task-create-policies-apps.html"
    - title: オンプレミスアプリケーションのデータをAmazon Web Servicesにバックアップ
      flavor: aws
      url: "/task-backup-app-data-to-aws.html"
    - title: オンプレミスアプリケーションのデータをMicrosoft Azureにバックアップ
      flavor: azure
      url: "/task-backup-app-data-to-azure.html"
    - title: オンプレミスアプリケーションのデータをGoogle Cloudにバックアップ
      flavor: gcp
      url: "/task-backup-app-data-to-gcp.html"
    - title: オンプレミスのアプリケーションデータをStorageGRID にバックアップ
      url: "/task-backup-app-data-to-storagegrid.html"
    - title: アプリケーションの保護を管理します
      url: "/task-manage-app-backups.html"
    - title: オンプレミスアプリケーションのデータをリストア
      entries:
      - title: Oracle データベースをリストアします
        url: "/task-restore-oracle-data.html"
      - title: SQL Server データベースをリストアする
        url: "/task-restore-sql-data.html"
      - title: SAP HANAデータベースをリストア
        url: "/task-restore-hana-backup.html"
      - title: MongoDB、MySQL、PostgreSQLデータベースのリストア
        url: "/task-restore-customplugin-backup.html"
  - title: 仮想マシンのデータのバックアップとリストア
    entries:
    - title: 仮想マシンのデータを保護
      url: "/concept-protect-vm-data.html"
    - title: SnapCenter Plug-in for VMware vSphereホストを登録
      url: "/task-register-snapCenter-plug-in-for-vmware-vsphere.html"
    - title: データストアをバックアップするポリシーを作成します
      url: "/task-create-policies-vms.html"
    - title: データストアをAmazon Web Servicesにバックアップする
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: データストアをMicrosoft Azureにバックアップする
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: データストアをGoogle Cloud Platformにバックアップする
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: データストアをStorageGRID にバックアップする
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: データストアと仮想マシンのデータの保護を管理します
      url: "/task-manage-vm-data-in-cloud.html"
    - title: 仮想マシンのデータをリストアします
      url: "/task-restore-vm-data.html"
  - title: REST API で自動化
    url: "/api-backup-restore.html"
  - title: 参照
    entries:
    - title: サポート対象の AWS アーカイブストレージ階層
      url: "/reference-aws-backup-tiers.html"
    - title: サポートされている Azure アーカイブアクセス層
      url: "/reference-azure-backup-tiers.html"
    - title: サポートされているGoogleアーカイブストレージ階層
      url: "/reference-google-backup-tiers.html"
    - title: Azure でマルチアカウントアクセスのバックアップを設定する
      flavor: azure
      url: "/reference-backup-multi-account-azure.html"
    - title: ダークサイトでBlueXPのバックアップ/リカバリデータベースをリストア
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: BlueXPのバックアップとリカバリを再開します
      url: "/reference-restart-backup.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/task-get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
