---
settings:
  name: BlueXP backup and recovery
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: クラウドプロバイダ
    default: すべてのクラウドプロバイダ
    options:
    - name: Amazon Web Services の
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: BlueXPのバックアップとリカバリのドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/whats-new.html"
    - title: Microsoft SQL Server ワークロードの既知の制限
      url: "/br-limitations.html"
    - title: ONTAPボリュームワークロードの既知の制限
      url: "/br-reference-limitations.html"
  - title: はじめに
    entries:
    - title: BlueXPのバックアップとリカバリについて説明します
      url: "/concept-backup-to-cloud.html"
    - title: BlueXP backup and recoveryの前提条件
      url: "/concept-start-prereq.html"
    - title: BlueXPのバックアップとリカバリのライセンスをセットアップ
      url: "/br-start-licensing.html"
    - title: BlueXP backup and recoveryを使用する前にバックアップ先を設定します
      url: "/br-start-setup.html"
    - title: BlueXP backup and recoveryにログイン
      url: "/br-start-login.html"
    - title: バックアップターゲットの検出
      url: "/br-start-discover-backup-targets.html"
    - title: さまざまなBlueXP backup and recoveryワークロードに切り替える
      url: "/br-start-switch-ui.html"
    - title: BlueXP backup and recoveryの一般設定を構成する
      url: "/br-start-configure.html"
  - title: BlueXP backup and recoveryを使用する
    entries:
    - title: ダッシュボードで保護の状態を確認する
      url: "/br-use-dashboard.html"
    - title: バックアップとリストアを管理するポリシーを作成する
      url: "/br-use-policies-create.html"
    - title: ONTAPボリュームのワークロードを保護する
      entries:
      - title: ONTAPボリュームワークロードの保護の概要
        url: "/prev-ontap-protect-overview.html"
      - title: ONTAPボリュームの保護を計画する
        url: "/prev-ontap-protect-journey.html"
      - title: ONTAPボリュームのポリシーを管理します。
        url: "/prev-ontap-policy-manage.html"
      - title: ONTAPボリュームのオブジェクトへのバックアップポリシーオプション
        url: "/prev-ontap-policy-object-options.html"
      - title: オブジェクトへのバックアップポリシーの詳細設定オプションを管理する
        url: "/prev-ontap-policy-object-advanced-settings.html"
      - title: Cloud Volumes ONTAP を Amazon S3 にバックアップします
        url: "/prev-ontap-backup-cvo-aws.html"
      - title: Cloud Volumes ONTAP を Azure Blob にバックアップ
        url: "/prev-ontap-backup-cvo-azure.html"
      - title: Cloud Volumes ONTAP を Google Cloud にバックアップ
        url: "/prev-ontap-backup-cvo-gcp.html"
      - title: オンプレミスの ONTAP から Amazon S3 へのバックアップ
        url: "/prev-ontap-backup-onprem-aws.html"
      - title: オンプレミスの ONTAP を Azure Blob にバックアップ
        url: "/prev-ontap-backup-onprem-azure.html"
      - title: オンプレミスの ONTAP から Google Cloud へのバックアップ
        url: "/prev-ontap-backup-onprem-gcp.html"
      - title: オンプレミスのONTAPをONTAP S3にバックアップ
        url: "/prev-ontap-backup-onprem-ontaps3.html"
      - title: オンプレミスの ONTAP を StorageGRID にバックアップ
        url: "/prev-ontap-backup-onprem-storagegrid.html"
      - title: SnapMirrorを使用したボリュームのクラウドへの再同期
        url: "/prev-ontap-migrate-resync.html"
      - title: ダークサイトで構成データを復元する
        url: "/reference-backup-cbs-db-in-dark-site.html"
      - title: ONTAP バックアップを管理します
        url: "/prev-ontap-backup-manage.html"
      - title: ONTAP バックアップからリストアする
        url: "/prev-ontap-restore.html"
    - title: Microsoft SQL Server ワークロードを保護する (プレビュー)
      entries:
      - title: Microsoft SQL Server ワークロードの保護の概要
        url: "/br-use-mssql-protect-overview.html"
      - title: SnapCenterからインポートする場合の追加項目を構成する
        url: "/concept-start-prereq-snapcenter-import.html"
      - title: Microsoft SQL Server ワークロードの検出
        url: "/br-start-discover.html"
      - title: Microsoft SQL Server ワークロードのバックアップ
        url: "/br-use-mssql-backup.html"
      - title: Microsoft SQL Server ワークロードを復元する
        url: "/br-use-mssql-restore.html"
      - title: Microsoft SQL Server ワークロードのクローン作成
        url: "/br-use-mssql-clone.html"
      - title: Microsoft SQL Server のインベントリを管理する
        url: "/br-use-manage-inventory.html"
      - title: Microsoft SQL Server スナップショットを管理する
        url: "/br-use-manage-snapshots.html"
      - title: Microsoft SQL Server レポートを作成する
        url: "/br-use-reports.html"
    - title: 仮想マシンのワークロードを保護する
      entries:
      - title: 仮想マシンのワークロードの保護の概要
        url: "/prev-vmware-protect-overview.html"
      - title: 仮想マシンのワークロードを保護するための前提条件
        url: "/prev-vmware-prereqs.html"
      - title: SnapCenter Plug-in for VMware vSphereホストを登録
        url: "/prev-vmware-register-snapcenter.html"
      - title: 仮想マシンのデータをバックアップするポリシーを作成する
        url: "/prev-vmware-policy-create.html"
      - title: データストアをAmazon Web Servicesにバックアップする
        url: "/prev-vmware-backup-aws.html"
      - title: データストアをMicrosoft Azureにバックアップする
        url: "/prev-vmware-backup-azure.html"
      - title: データストアをGoogle Cloud Platformにバックアップする
        url: "/prev-vmware-backup-gcp.html"
      - title: データストアをStorageGRID にバックアップする
        url: "/prev-vmware-backup-storagegrid.html"
      - title: データストアと仮想マシンのデータの保護を管理します
        url: "/prev-vmware-manage.html"
      - title: 仮想マシンのデータとデータストアを復元する
        url: "/prev-vmware-restore.html"
    - title: Kubernetes ワークロードを保護する（プレビュー）
      entries:
      - title: Kubernetes ワークロードの保護の概要
        url: "/br-use-kubernetes-protect-overview.html"
      - title: Kubernetes ワークロードを発見する
        url: "/br-start-discover-kubernetes.html"
      - title: Kubernetes アプリケーションの追加と保護
        url: "/br-use-protect-kubernetes-applications.html"
      - title: Kubernetesアプリケーションの復元
        url: "/br-use-restore-kubernetes-applications.html"
      - title: Kubernetes クラスタを管理
        url: "/br-use-manage-kubernetes-clusters.html"
      - title: Kubernetes アプリケーションを管理する
        url: "/br-use-manage-kubernetes-applications.html"
      - title: Kubernetes ワークロードの実行フック テンプレートを管理する
        url: "/br-use-manage-execution-hook-templates.html"
    - title: ジョブの監視
      url: "/br-use-monitor-tasks.html"
    - title: BlueXPのバックアップとリカバリを再開します
      url: "/reference-restart-backup.html"
  - title: REST API で自動化
    url: "/br-api-backup-restore.html"
  - title: 参照
    entries:
    - title: SnapCenterのポリシーとBlueXP backup and recoveryの比較
      url: "/reference-policy-differences-snapcenter.html"
    - title: BlueXP backup and recoveryの役割と権限
      url: "/reference-roles.html"
    - title: サポート対象の AWS アーカイブストレージ階層
      url: "/prev-reference-aws-archive-storage-tiers.html"
    - title: サポートされている Azure アーカイブ ストレージ層
      url: "/prev-reference-azure-archive-storage-tiers.html"
    - title: サポートされている Google Cloud アーカイブ ストレージ層
      url: "/prev-reference-gcp-archive-storage-tiers.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
