---
settings:
  name: Cloud Backup
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: クラウドプロバイダ
    default: すべてのクラウドプロバイダ
    options:
    - name: Amazon Web Services の
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Cloud Backup のドキュメント
    url: "/index.html"
  - title: リリースノート
    url: "/whats-new.html"
  - title: はじめに
    entries:
    - title: Cloud Backup の詳細をご確認ください
      url: "/concept-backup-to-cloud.html"
    - title: ライセンスをセットアップする
      url: "/task-licensing-cloud-backup.html"
    - title: バックアップジョブとリストアジョブのステータスを監視します
      url: "/task-monitor-backup-jobs.html"
  - title: ONTAP データのバックアップとリストア
    entries:
    - title: ONTAP データを保護
      url: "/concept-ontap-backup-to-cloud.html"
    - title: Cloud Volumes ONTAP を Amazon S3 にバックアップします
      flavor: aws
      url: "/task-backup-to-s3.html"
    - title: Cloud Volumes ONTAP を Azure Blob にバックアップ
      flavor: azure
      url: "/task-backup-to-azure.html"
    - title: Cloud Volumes ONTAP を Google Cloud にバックアップ
      flavor: gcp
      url: "/task-backup-to-gcp.html"
    - title: オンプレミスの ONTAP から Amazon S3 へのバックアップ
      flavor: aws
      url: "/task-backup-onprem-to-aws.html"
    - title: オンプレミスの ONTAP を Azure Blob にバックアップ
      flavor: azure
      url: "/task-backup-onprem-to-azure.html"
    - title: オンプレミスの ONTAP から Google Cloud へのバックアップ
      flavor: gcp
      url: "/task-backup-onprem-to-gcp.html"
    - title: オンプレミスの ONTAP を StorageGRID にバックアップ
      url: "/task-backup-onprem-private-cloud.html"
    - title: ONTAP バックアップを管理します
      url: "/task-manage-backups-ontap.html"
    - title: クラスタレベルのバックアップの設定を管理します
      url: "/task-manage-backup-settings-ontap.html"
    - title: ONTAP バックアップからリストアする
      url: "/task-restore-backups-ontap.html"
  - title: Kubernetes データのバックアップとリストア
    entries:
    - title: Kubernetes のデータを保護
      url: "/concept-kubernetes-backup-to-cloud.html"
    - title: Amazon S3 にバックアップします
      flavor: aws
      url: "/task-backup-kubernetes-to-s3.html"
    - title: Azure Blob にバックアップ
      flavor: azure
      url: "/task-backup-kubernetes-to-azure.html"
    - title: Google Cloud にバックアップ
      flavor: gcp
      url: "/task-backup-kubernetes-to-gcp.html"
    - title: Kubernetes のバックアップを管理
      url: "/task-manage-backups-kubernetes.html"
    - title: Kubernetes バックアップからリストア
      url: "/task-restore-backups-kubernetes.html"
  - title: アプリケーションデータを保護
    entries:
    - title: オンプレミスアプリケーションのデータを保護
      entries:
      - title: オンプレミスアプリケーションのデータを保護
        url: "/concept-protect-app-data-to-cloud.html"
      - title: SnapCenter サーバを登録します
        url: "/task-register-snapcenter-server.html"
      - title: アプリケーションをバックアップするポリシーを作成する
        url: "/task-create-policies-apps.html"
      - title: オンプレミスアプリケーションのデータをAmazon Web Servicesにバックアップ
        flavor: aws
        url: "/task-backup-app-data-to-aws.html"
      - title: オンプレミスアプリケーションのデータをMicrosoft Azureにバックアップ
        flavor: azure
        url: "/task-backup-app-data-to-azure.html"
      - title: オンプレミスアプリケーションのデータをGoogle Cloudにバックアップ
        flavor: gcp
        url: "/task-backup-app-data-to-gcp.html"
      - title: オンプレミスのアプリケーションデータをStorageGRID にバックアップ
        url: "/task-backup-app-data-to-storagegrid.html"
      - title: アプリケーションの保護を管理します
        url: "/task-manage-app-backups.html"
      - title: オンプレミスアプリケーションのデータをリストア
        entries:
        - title: Oracle データベースをリストアします
          url: "/task-restore-oracle-data.html"
        - title: SQL Server データベースをリストアする
          url: "/task-restore-sql-data.html"
      - title: アプリケーションバックアップをマウント
        url: "/task-mount-app-backup.html"
    - title: クラウドネイティブアプリケーションのデータを保護
      entries:
      - title: クラウドネイティブアプリケーションのデータを保護
        url: "/concept-protect-cloud-app-data-to-cloud.html"
      - title: クラウドネイティブアプリケーションデータをバックアップ
        entries:
        - title: クラウドネイティブのOracleデータベースをバックアップ
          entries:
          - title: BlueXPにアクセスします
            url: "/reference-access-bluexp.html"
          - title: ONTAP のFSXを設定します
            url: "/reference-configure-fsx-for-ontap.html"
          - title: Cloud Volumes ONTAP を設定します
            url: "/reference-configure-cloud-volumes-ontap.html"
          - title: ホストを追加し、Oracleデータベースを検出します
            url: "/task-add-host-discover-oracle-databases.html"
          - title: Oracleデータベースをバックアップする
            url: "/task-backup-cloud-native-oracle-data.html"
        - title: クラウドネイティブのSAP HANAデータベースをバックアップ
          entries:
          - title: BlueXPにアクセスします
            flavor: azure
            url: "/reference-access-bluexp.html"
          - title: Azure NetApp Files を設定します
            flavor: azure
            url: "/reference-configure-azure-netapp-files.html"
          - title: SnapCenter Plug-in for SAP HANAを導入
            flavor: azure
            url: "/task-deploy-snapcenter-plugin-for-sap-hana.html"
          - title: SAP HANAデータベースをバックアップする
            flavor: azure
            url: "/task-backup-cloud-native-sap-hana-data.html"
      - title: クラウドネイティブアプリケーションのデータをリストア
        entries:
        - title: クラウドネイティブのOracleデータベースをリストアする
          url: "/task-restore-cloud-native-oracle-data.html"
        - title: クラウドネイティブのSAP HANAデータベースをリストア
          flavor: azure
          url: "/task-restore-cloud-native-sap-hana-data.html"
      - title: クラウドネイティブアプリケーションデータのクローニング
        entries:
        - title: クラウドネイティブのOracleデータベースをクローニングします
          entries:
          - title: クローンの概念と要件
            url: "/concept-clone-cloud-native-oracle-concepts.html"
          - title: クラウドネイティブのOracleデータベースをクローニングします
            url: "/task-clone-cloud-native-oracle-data.html"
      - title: クラウドネイティブなアプリケーションデータの保護を管理
        url: "/task-manage-cloud-native-app-data.html"
  - title: 仮想マシンのデータのバックアップとリストア
    entries:
    - title: 仮想マシンのデータを保護
      url: "/concept-protect-vm-data.html"
    - title: SnapCenter Plug-in for VMware vSphereの登録
      url: "/task-register-snapCenter-plug-in-for-vmware-vsphere.html"
    - title: 仮想マシンをバックアップするポリシーを作成します
      url: "/task-create-policies-vms.html"
    - title: データストアをAmazon Web Servicesにバックアップする
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: データストアをMicrosoft Azureにバックアップする
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: データストアをGoogle Cloud Platformにバックアップする
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: データストアをStorageGRID にバックアップする
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: 仮想マシンの保護を管理します
      url: "/task-manage-vm-data-in-cloud.html"
    - title: 仮想マシンのデータをリストアします
      url: "/task-restore-vm-data.html"
  - title: REST API で自動化
    url: "/api-backup-restore.html"
  - title: 参照
    entries:
    - title: Cloud Backupポリシーの設定
      url: "/concept-cloud-backup-policies.html"
    - title: サポート対象の AWS アーカイブストレージ階層
      url: "/reference-aws-backup-tiers.html"
    - title: サポートされている Azure アーカイブアクセス層
      url: "/reference-azure-backup-tiers.html"
    - title: サポートされているGoogleアーカイブストレージ階層
      url: "/reference-google-backup-tiers.html"
    - title: ダークサイトのCloud Backupデータベースをバックアップする
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: Azure でマルチアカウントアクセス用にバックアップを設定
      url: "/reference-backup-multi-account-azure.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/task-get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: Cloud Backup の詳細をご確認ください
      url: concept-backup-to-cloud.html
    - title: 新機能
      url: whats-new.html
    - title: ライセンスをセットアップする
      url: task-licensing-cloud-backup.html
    - title: バックアップジョブとリストアジョブのステータスを監視します
      url: task-monitor-backup-jobs.html
  - title: ONTAP データをクラウドにバックアップ
    links:
    - title: Cloud Volumes ONTAP から Amazon S3 へ
      url: task-backup-to-s3.html
      flavor: aws
    - title: Cloud Volumes ONTAP と Azure Blob の間
      url: task-backup-to-azure.html
      flavor: azure
    - title: Cloud Volumes ONTAP から Google Cloud へ
      url: task-backup-to-gcp.html
      flavor: gcp
    - title: オンプレミスの ONTAP から Amazon S3 へ
      url: task-backup-onprem-to-aws.html
      flavor: aws
    - title: オンプレミスの ONTAP と Azure Blob の間でデータを移動
      url: task-backup-onprem-to-azure.html
      flavor: azure
    - title: オンプレミスの ONTAP から Google Cloud へ
      url: task-backup-onprem-to-gcp.html
      flavor: gcp
    - title: オンプレミスの ONTAP から StorageGRID へ
      url: task-backup-onprem-private-cloud.html
  - title: Kubernetes のデータをクラウドにバックアップ
    links:
    - title: Kubernetes クラスタから Amazon S3 へ
      url: task-backup-kubernetes-to-s3.html
      flavor: aws
    - title: Kubernetes クラスタから Azure Blob への移行
      url: task-backup-kubernetes-to-azure.html
      flavor: azure
    - title: Kubernetes クラスタから Google Cloud へ
      url: task-backup-kubernetes-to-gcp.html
      flavor: gcp
  - title: アプリケーションデータを保護
    links:
    - title: オンプレミスアプリケーションのデータをAmazon Web Servicesにバックアップ
      flavor: aws
      url: "/task-backup-app-data-to-aws.html"
    - title: オンプレミスアプリケーションのデータをMicrosoft Azureにバックアップ
      flavor: azure
      url: "/task-backup-app-data-to-azure.html"
    - title: オンプレミスアプリケーションのデータをGoogle Cloudにバックアップ
      flavor: gcp
      url: "/task-backup-app-data-to-gcp.html"
    - title: オンプレミスのアプリケーションデータをStorageGRID にバックアップ
      url: "/task-backup-app-data-to-storagegrid.html"
    - title: クラウドネイティブのOracleデータベースをバックアップ
      url: task-backup-cloud-native-oracle-data.html
    - title: クラウドネイティブのSAP HANAデータベースをバックアップ
      url: task-backup-cloud-native-sap-hana-data.html
  - title: 仮想マシンのデータのバックアップとリストア
    links:
    - title: データストアをAmazon Web Servicesにバックアップする
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: データストアをMicrosoft Azureにバックアップする
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: データストアをGoogle Cloud Platformにバックアップする
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: データストアをStorageGRID にバックアップする
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: クラウドから仮想マシンをリストアします
      url: task-restore-vm-data.html
  - title: ONTAP バックアップファイルからデータをリストアする
    links:
    - title: ONTAP ボリュームをリストア
      url: task-restore-backups-ontap.html
    - title: ONTAP ボリュームからファイルとフォルダをリストア
      url: task-restore-backups-ontap.html
    - title: Kubernetes ボリュームをリストア
      url: task-restore-backups-kubernetes.html
  - title: ONTAP バックアップファイルを管理します
    links:
    - title: ボリュームのバックアップを有効または無効にします
      url: task-manage-backups-ontap.html#enabling-and-disabling-backups-of-volumes
    - title: 既存のバックアップポリシーを編集する
      url: task-manage-backups-ontap.html#editing-an-existing-backup-policy
    - title: 新しいバックアップポリシーを追加します
      url: task-manage-backups-ontap.html#adding-a-new-backup-policy
    - title: 既存のボリュームに割り当てられているポリシーを変更します
      url: task-manage-backups-ontap.html#changing-the-policy-assigned-to-existing-volumes
    - title: ボリュームの手動バックアップを作成します
      url: task-manage-backups-ontap.html#creating-a-manual-volume-backup-at-any-time
    - title: 各ボリュームのバックアップのリストを表示します
      url: task-manage-backups-ontap.html#viewing-the-list-of-backups-for-each-volume
    - title: バックアップを削除します
      url: task-manage-backups-ontap.html#deleting-backups
  - title: ブログとコミュニティ
    links:
    - title: ネットアップコミュニティ
      url: https://community.netapp.com/t5/Public-Cloud-Services/ct-p/CDS
    - title: BlueXPブログ
      url: https://bluexp.netapp.com/blog
    - title: Cloud Backupのユースケース
      url: https://bluexp.netapp.com/cloud-backup
    - title: クラウドに関する Web セミナー
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: BlueXPのすべてのマニュアル
