---
sidebar: sidebar 
permalink: reference-google-backup-tiers.html 
keywords: google, storage classes, archive 
summary: Cloud Backupは、1つのGoogleアーカイブストレージクラスとほとんどのリージョンをサポートします。 
---
= Googleアーカイブストレージクラスとリストアの読み出し時間
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Backupは、1つのGoogleアーカイブストレージクラスとほとんどのリージョンをサポートします。



== Cloud BackupでサポートされているGoogleアーカイブストレージクラス

バックアップファイルが最初に作成されるときは、_Standard_storageに保存されます。この階層は、アクセス頻度の低いデータを格納するために最適化されていますが、すぐにアクセスすることもできます。

オンプレミスクラスタがONTAP 9.12.1以降を使用している場合は、特定の日数（通常は30日以上）が経過した後に、古いバックアップをクラウドバックアップUIで_Archive_storageに階層化して、さらなるコスト最適化を行うことができます。（この機能は現在、Cloud Volumes ONTAP システムでは使用できません）。この階層のデータには高い読み出しコストが必要なため、アーカイブされたバックアップファイルからデータをリストアする頻度を考慮する必要があります。についてのセクションを参照してください <<アーカイブストレージからのデータのリストア,アーカイブストレージからのデータのリストア>>。

このタイプのライフサイクルルールでCloud Backupを設定する場合は、Googleアカウントでバケットを設定する際にライフサイクルルールを設定しないでください。

https://cloud.google.com/storage/docs/storage-classes["Googleのストレージクラスについて説明します"^]。



== アーカイブストレージからのデータのリストア

古いバックアップファイルをアーカイブストレージに保存すると、標準ストレージよりもはるかに低コストですが、リストア処理のためにアーカイブストレージ内のバックアップファイルからデータにアクセスすると、所要時間が若干長くなり、コストが増大します。

Google Archiveからデータを復元するのにどのくらいのコストがかかりますか。:: 地域別のGoogle Cloud Storageの詳細な価格設定については、を参照してください https://cloud.google.com/storage/pricing["Google Cloud Storageの価格設定ページ"^]。
Google Archiveにアーカイブされているオブジェクトをリストアするのにどれくらいの時間がかかりますか。:: リストアの合計時間は、次の 2 つの要素で構成されます。
+
--
* *取得時間*：アーカイブからバックアップファイルを取得して標準ストレージに保存する時間。これは、「水和」時間と呼ばれることもあります。他のクラウドプロバイダが提供する「最低目的」のストレージソリューションとは異なり、データには数ミリ秒でアクセスできます。
* * リストア時間 * ： Standard ストレージのバックアップファイルからデータをリストアする時間。アーカイブ層を使用しない場合、この時間は標準ストレージから直接実行される通常のリストア処理と同じです。


--

