---
sidebar: sidebar 
permalink: reference-prereq-protect-cloud-native-app-data.html 
keywords: Cloud Manager, FSx for ONTAP, working environment, Connector, AWS, deploy Oracle plug-in, BlueXP 
summary: バックアップを作成する前に前提条件を完了します。 
---
= 前提条件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPにアクセスし'BlueXPアカウントを作成して作業環境とコネクタを作成し'Oracle向けSnapCenter プラグインを導入している必要があります



== BlueXPにアクセスします

お勧めします https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["BlueXPにログインします"^]をクリックし、を設定します https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-setting-up-netapp-accounts.html["ネットアップアカウント"^]。



== ONTAP 作業環境用のFSXを作成します

データベースがホストされているONTAP 環境用のAmazon FSXを作成する必要があります。詳細については、を参照してください link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/start/task-getting-started-fsx.html["Amazon FSX for ONTAP の利用を開始しましょう"] および link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["Amazon FSX for ONTAP 作業環境の作成と管理"]。

NetApp FSXは、BlueXPまたはAWSを使用して作成できます。AWSを使用してを作成した場合は、BlueXPのONTAP システム用FSXを検出する必要があります。



== コネクタを作成します

アカウント管理者は、AWSにConnectorを導入する必要があります。これにより、BlueXPでパブリッククラウド環境内のリソースとプロセスを管理できるようになります。

詳細については、を参照してください link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html["BlueXPからAWSでコネクタを作成する"]。

* FSX作業環境とOracleデータベースの両方を管理する場合には、同じコネクタを使用する必要があります。
* FSX作業環境とOracleデータベースが同じVPC内にある場合は、同じVPC内にコネクタを導入できます。
* FSX作業環境および異なるVPC内のOracleデータベースがある場合：
+
** FSX上にNAS（NFS）ワークロードが設定されている場合、どちらのVPCにもコネクタを作成できます。
** NAS（NFS）ワークロードを使用しないようにSANワークロードだけを設定している場合は、FSXシステムが作成されたVPCにコネクタを作成する必要があります。
+

NOTE: NAS（NFS）ワークロードを使用する場合は、OracleデータベースVPCとFSX VPCの間に転送ゲートウェイを設定する必要があります。フローティングIPアドレスであるNFS IPアドレスには、転送ゲートウェイ経由でのみ別のVPCからアクセスできます。VPCをピアリングしてフローティングIPアドレスにアクセスすることはできません。





コネクターを作成したら、*ストレージ*>*キャンバス*>*作業環境*>*作業環境の追加*をクリックし、画面の指示に従って作業環境を追加します。コネクタからOracleデータベースホストおよびFSX作業環境への接続が確立されていることを確認します。コネクタは、FSX作業環境のクラスタ管理IPアドレスに接続できる必要があります。


IMPORTANT: コネクタを作成したら、[コネクタ（Connector）]>[コネクタの管理（Manage Connectors）]*をクリックし、コネクタ名を選択してコネクタIDをコピーします。



== SnapCenter Plug-in for Oracleを導入します

SnapCenter Plug-in for Oracleは、各Oracleデータベースホストに導入する必要があります。OracleホストでSSHキーベースの認証が有効になっているかどうかに応じて、いずれかの方法でプラグインを導入できます。


NOTE: 各OracleデータベースホストにJava 8がインストールされ、JAVA_HOME変数が適切に設定されていることを確認します。



=== SSHキーベースの認証を使用するプラグインの導入

OracleホストでSSHキーベースの認証が有効になっている場合、次の手順を実行してプラグインを導入できます。手順を実行する前に、コネクタへのSSH接続が有効になっていることを確認してください。

. Connector VMにroot以外のユーザとしてログインします。
. ベースマウントパスを取得します。「sudo Docker volume ls | grep scs_cloud_volume | awk {'print$2'}|xargs sudo Docker volume inspect | grep mountpoint`」
. プラグインを導入します。
+
sudo <base_mount_path>/scripts/oracle_plugin_copy_and_install.sh --host <host_name>--sshkey <ssh_key_file>--username <user_name>--port <ssh_port>--plugin port <plugin_port>--installdir <install_dir>

+
** host_nameはOracleホストの名前です。これは必須パラメータです。
** ssh_key_fileは、Oracleホストへの接続に使用するSSHキーで、これは必須パラメータです。
** user_name：OracleホストでSSH権限を持つユーザ。これはオプションパラメータです。デフォルト値はec2-userです。
** ssh_port：Oracleホスト上のSSHポート。これはオプションパラメータです。デフォルト値は22です
** plugin_port：プラグインで使用するポート。これはオプションパラメータです。デフォルト値は8145です
** install_dir：プラグインが配置されるディレクトリ。これはオプションのパラメータです。デフォルト値は/optです。




たとえば、「sudo /var/lib/docker/volumes/service-manager--2 _ cloudmanager_scs_cloud_volume/_data/scripts/oracle_plugin_copy_and_install.sh -- host xxx.xxx.xxx.xxx -- key/keys/NetApp-ssh.pk`」のように指定します



=== プラグインの手動導入

OracleホストでSSHキーベースの認証が有効になっていない場合は、次の手動手順を実行してプラグインを導入する必要があります。

. Connector VMにログインします。
. SnapCenter Linuxホストプラグインバイナリをダウンロードします。「sudo Docker exec-it cloudmanager_scs_cloud curl -X get 'http://127.0.0.1/deploy/downloadLinuxPlugin'`[]
. ベースマウントパスを取得します。「sudo Docker volume ls | grep scs_cloud_volume | awk {'print$2'}|xargs sudo Docker volume inspect | grep mountpoint`」
. ダウンロードしたプラグインのバイナリパスを取得します。sudo ls <base_mount_path>$（sudo Docker PS | grep -Po " cloudmanager_scs_cloud：*？"|sed -e '/*$//'/|cut -f2 -d ":")/sc-linux -host-plugin/snapcenter linux _host_plugin_bbin
. scpまたはその他の代替方法を使用して、Oracleデータベースホストのそれぞれにcopy_snapcenter linux_host_plugin_scs.bin _をコピーします。
. Oracleデータベース・ホストで、次のコマンドを実行してバイナリの実行権限を有効にします。chmod +x snapcenter linux_host_plugin_sbin`
. Oracleプラグインをrootユーザとして導入します。snapcenter_linux_host_plugin_scs.bin -私は黙っている
. connector VMのcopy_certificate.p12_from_<base_mount_path>/client/certificate/_pathを、プラグインホスト上の_/var/opt/snapcenter/spl/etc/にコピーします。
+
.. _/var/opt/snapcenter/spl/etcに移動し、keytoolコマンドを実行して証明書をインポートします。keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore keystore.jks -deststoretype JKS -srcstorepass SnapCenter -deststorepass SnapCenter agentcert -destalias agentcert -noprompt`
.. spl:'systemctl restart sp'を再起動します



