---
sidebar: sidebar 
permalink: reference-configure-fsx-for-ontap.html 
keywords: Cloud Manager, FSx for ONTAP, working environment, Connector, BlueXP 
summary: FSX for ONTAP 作業環境とコネクターを作成します 
---
= ONTAP のFSXを設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPを使用してFSx for ONTAP 作業環境を作成し、ボリュームや追加のデータサービスを追加、管理する必要があります。また、AWSでコネクタを作成して、パブリッククラウド環境内のリソースとプロセスをBlueXPで管理できるようにする必要があります。



== ONTAP 作業環境用のFSXを作成します

データベースがホストされているFSx for ONTAP 作業環境を作成する必要があります。詳細については、を参照してください link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Amazon FSX for ONTAP の利用を開始しましょう"] および link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-creating-fsx-working-environment.html["Amazon FSX for ONTAP 作業環境の作成と管理"]。

FSx for ONTAP 作業環境は、BlueXPまたはAWSを使用して作成できます。AWSを使用してを作成した場合は、BlueXPのONTAP システム用FSXを検出する必要があります。



== コネクタを作成します

アカウント管理者はAWSでコネクタを作成し、BlueXPでパブリッククラウド環境内のリソースとプロセスを管理する必要があります。

詳細については、を参照してください link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["BlueXPからAWSでコネクタを作成する"]。

* FSx for ONTAP の作業環境とデータベースの管理には、同じコネクタを使用する必要があります。
* FSx for ONTAP の作業環境とデータベースが同じ仮想プライベートクラウド（VPC）内にある場合は、コネクタを同じVPCに導入できます。
* FSx for ONTAP の作業環境とデータベースが異なるVPCにある場合：
+
** FSx for ONTAP でNAS（NFS）ワークロードが設定されている場合は、どちらかのVPCにコネクタを作成できます。
** SANワークロードのみが設定されていて、NAS（NFS）ワークロードを使用する予定がない場合は、FSx for ONTAP システムが作成されたVPCにコネクタを作成する必要があります。
+

NOTE: NAS（NFS）ワークロードを使用する場合は、データベースVPCとAmazon VPC間のトランジットゲートウェイが必要です。フローティングIPアドレスであるNFS IPアドレスには、転送ゲートウェイ経由でのみ別のVPCからアクセスできます。VPCをピアリングしてフローティングIPアドレスにアクセスすることはできません。





コネクタを作成したら、*[ストレージ]*>* Canvas *>* My Working Environments *>*[Add Working Environment]*をクリックし、プロンプトに従って作業環境を追加します。コネクタからOracleデータベースホストおよびFSx作業環境への接続が確立されていることを確認します。コネクタは、FSx作業環境のクラスタ管理IPアドレスに接続できる必要があります。

* [ストレージ]*>* Canvas *>* My Working Environments *>*[作業環境の追加]*をクリックして、作業環境を追加します。
+
コネクタからデータベースホストおよびFSx for ONTAP 作業環境への接続が確立されていることを確認します。コネクタは、FSx for ONTAP 作業環境のクラスタ管理IPアドレスに接続する必要があります。

* コネクター（Connector）>コネクターを管理（Manage Connectors）*をクリックし、コネクター名を選択して、コネクターIDをコピーします。

