---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, backup, restore, backup and recovery 
summary: 既知の制限事項には、このリリースの製品でサポートされていない機能、またはこのリリースと正しく相互運用できない機能が記載されています。これらの制限事項を慎重に確認してください 
---
= 既知の制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既知の制限事項には、このリリースの製品でサポートされていない機能、またはこのリリースと正しく相互運用できない機能が記載されています。これらの制限事項を慎重に確認してください



== ONTAPのバックアップとリストアの制限事項

* BlueXP  のバックアップとリカバリCloud Volume ONTAPをAWS中国のリージョン（北京と寧夏を含む）のオブジェクトストアにバックアップしますが、最初にIDとアクセス管理（IAM）ポリシーを手動で変更する必要がある場合があります。
+
AWSでのコネクタの作成の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-bluexp.html["AWSにコネクタをインストールする"^]。

+
ブログ記事の詳細については、を参照してくださいhttps://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-May-23-Updates/ba-p/444052["BlueXP  のバックアップとリカバリ機能に関するブログ（2023年5月）"^]。

* BlueXP  のバックアップとリカバリでは、Microsoft Azure中国リージョンはサポートされません。
+
Azureでのコネクタの作成の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-bluexp.html["Azureにコネクタをインストールしています"^]。

* BlueXP  のバックアップとリカバリでは、FlexCacheボリュームのバックアップはサポートされません。




=== レプリケーションの制限事項

* レプリケーション対象として一度に選択できるFlexGroupボリュームは1つだけです。FlexGroupボリュームごとにバックアップを個別にアクティブ化する必要があります。
+
FlexVolボリュームに関する制限はありません。作業環境内のすべてのFlexVolボリュームを選択し、同じバックアップポリシーを割り当てることができます。

* では、次の機能がサポートされます https://docs.netapp.com/us-en/bluexp-replication/index.html["BlueXPレプリケーションサービス"]ただし、BlueXPのバックアップとリカバリのレプリケーション機能を使用している場合は適用されません。
+
** ボリュームAからボリュームBへ、およびボリュームBからボリュームCへのレプリケーションを行うカスケード構成はサポートされていませんサポートには、ボリュームAからボリュームBへのレプリケーションが含まれます
** FSx for ONTAPシステムとの間でのデータのレプリケートはサポートされていません。
** ボリュームの1回限りのレプリケーションを作成することはできません。


* オンプレミスのONTAPシステムからレプリケーションを作成する場合、ターゲットのCloud Volumes ONTAPシステムのONTAPのバージョンが9.8、9.9、または9.11の場合は、mirror-vaultポリシーのみが許可されます。




=== オブジェクトへのバックアップの制限事項

* データのバックアップ時に、BlueXP  のバックアップとリカバリでNetApp Volume Encryption（NVE）が維持されません。つまり、NVEボリューム上の暗号化されたデータは、データがデスティネーションに転送されている間は復号化され、暗号化は維持されません。
+
これらの暗号化タイプの詳細については、を参照してくださいhttps://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["NetAppボリューム暗号化の設定の概要"^]。



* SnapMirrorポリシーのスケジュールを使用してSnapMirrorデスティネーションボリュームで長期保持のSnapshotを有効にすると、デスティネーションボリュームにSnapshotが直接作成されます。この場合、BlueXP  のバックアップとリカバリを使用してこれらのボリュームをバックアップしないでください。Snapshotはオブジェクトストレージに移動されません。
* バックアップポリシーにボリュームが割り当てられていないときにバックアップポリシーを作成または編集する場合、保持されるバックアップの最大数は1018です。ポリシーにボリュームを割り当てたら、ポリシーを編集して最大4、000個のバックアップを作成できます。
* DP ボリュームをバックアップする場合は、次の点に注意してください。
+
** SnapMirrorラベルが設定された関係 `app_consistent` および `all_source_snapshot` クラウドにバックアップできない。
** SnapMirrorデスティネーションボリュームでSnapshotのローカルコピーを作成する場合（使用するSnapMirrorラベルに関係なく）、これらのSnapshotはバックアップとしてクラウドに移動されません。この時点で、BlueXPのバックアップとリカバリでソースDPボリュームをバックアップできるように、目的のラベルを指定したSnapshotポリシーをソースDPボリュームに作成する必要があります。


* FlexGroup ボリュームのバックアップをアーカイブストレージに移動することはできません。
* クラスタでONTAP 9.13.1以降が実行されている場合、FlexGroupボリュームのバックアップでDataLockとランサムウェア対策を使用できます。
* SVM-DR ボリュームバックアップは、次の制限事項でサポートされます。
+
** バックアップは ONTAP セカンダリからのみサポートされます。
** ボリュームに適用されるSnapshotポリシーは、BlueXPのバックアップとリカバリで認識されるポリシー（日次、週次、月次など）のいずれかである必要があります デフォルトの「sm_created」ポリシー（*[すべてのSnapshotをミラーリング]*に使用）は認識されず、バックアップ可能なボリュームのリストにDPボリュームは表示されません。
** ソースまたはデスティネーションからバックアップを作成した場合、SVM-DRとボリュームのバックアップとリカバリは完全に独立して機能します。唯一の制限事項は、SVM-DRでSnapMirrorクラウド関係がレプリケートされないことです。セカンダリサイトでSVMがオンラインになったDRシナリオでは、SnapMirrorクラウド関係を手動で更新する必要があります。




* MetroCluster のサポート：
+
** ONTAP 9.12.1 GA以上を使用している場合は、プライマリシステムに接続しているときにバックアップがサポートされます。バックアップ構成全体がセカンダリシステムに転送されるため、スイッチオーバー後もクラウドへのバックアップが自動的に続行されます。セカンダリシステムにバックアップを設定する必要はありません（実際には、セットアップは制限されています）。
** ONTAP 9.12.0以前を使用している場合、バックアップはONTAPセカンダリシステムからのみサポートされます。
** 現時点では、FlexGroup ボリュームのバックアップはサポートされていません。


* [今すぐバックアップ]ボタンを使用したアドホック・ボリューム・バックアップは'データ保護ボリュームではサポートされていません
* SM-BC 設定はサポートされません。
* ONTAP では、1つのボリュームから複数のオブジェクトストアへのSnapMirror関係のファンアウトはサポートされていません。そのため、この構成はBlueXPのバックアップおよびリカバリではサポートされていません。
* 現時点では、オブジェクトストアのWORM / ComplianceモードはAmazon S3、Azure、StorageGRID でサポートされています。これはDataLock機能と呼ばれ、クラウドプロバイダのインターフェイスではなく、BlueXPのバックアップとリカバリの設定を使用して管理する必要があります。




=== リストアの制限事項

これらの制限事項は、特に明記されていない限り、ファイルとフォルダをリストアするための検索とリストアおよび参照と復元の両方の方法に適用されます。

* ブラウズとリストアでは、一度に最大100個のファイルをリストアできます。
* 検索とリストアでは、一度に1つのファイルをリストアできます。
* ONTAP 9.13.0以降を使用している場合、[参照と復元]および[検索と復元]では、フォルダ内のすべてのファイルとサブフォルダとともにフォルダを復元できます。
+
9.11.1より前のバージョンのONTAP を使用している場合、リストア処理でリストアできるのは選択したフォルダとそのフォルダ内のファイルのみです。サブフォルダまたはサブフォルダ内のファイルはリストアされません。

+
9.11.1より前のバージョンのONTAP を使用している場合、フォルダのリストアはサポートされません。

* ディレクトリ/フォルダのリストアは、クラスタでONTAP 9.13.1以降が実行されている場合にのみアーカイブストレージに格納されたデータでサポートされます。
* DataLockを使用して保護されているデータについては、クラスタでONTAP 9.13.1以降が実行されている場合にのみ、ディレクトリ/フォルダのリストアがサポートされます。
* レプリケーションやローカルスナップショットからのディレクトリ/フォルダのリストアは現在サポートされていません。
* FlexGroup ボリュームからFlexVol ボリューム、またはFlexVol ボリュームからFlexGroup ボリュームへのリストアはサポートされていません。
* リストアするファイルは、デスティネーションボリュームの言語と同じ言語を使用している必要があります。言語が異なる場合は、エラーメッセージが表示されます。
* AzureアーカイブストレージからStorageGRID システムにデータをリストアする場合、_High_restore優先度はサポートされません。
* DPボリュームのバックアップ後にそのボリュームへのSnapMirror関係を解除する場合は、SnapMirror関係を削除するか、SnapMirrorの方向を逆にしないかぎり、そのボリュームにファイルをリストアすることはできません。
* クイックリストアの制限事項：
+
** デスティネーションの場所は、ONTAP 9.13.0以降を使用するCloud Volumes ONTAPシステムである必要があります。
** アーカイブストレージにあるバックアップではサポートされません。
** FlexGroupボリュームは、クラウドバックアップの作成元のソースシステムでONTAP 9.12.1以降が実行されている場合にのみサポートされます。
** SnapLockボリュームは、クラウドバックアップの作成元のソースシステムでONTAP 9.11.0以降が実行されている場合にのみサポートされます。



