---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database 
summary: インターネットにアクセスできないサイトでクラウドバックアップを使用する場合は、問題 にBlueXP Connectorホストシステムがインストールされている場合に、重要なクラウドバックアップファイルを定期的にバックアップする必要があります。これにより、新しいコネクタを導入し、重要なクラウドバックアップデータをリストアできるようになります。 
---
= ダークサイトでCloud Backupのデータのバックアップとリストアを行う
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
インターネットにアクセスできないサイトでクラウドバックアップを使用する場合は、問題 にBlueXP Connectorホストシステムがインストールされている場合に、重要なクラウドバックアップファイルを定期的にバックアップする必要があります。これにより、新しいコネクタを導入し、重要なクラウドバックアップデータをリストアできるようになります。

BlueXP Connectorがクラウドプロバイダまたはインターネットにアクセス可能な独自のホストシステムに導入されているSaaS環境でCloud Backupを使用すると、重要なすべてのCloud Backup設定データがバックアップされ、クラウドに保存されます。インターネットアクセスのないサイト（「ダークサイト」とも呼ばれる）でCloud Backupを使用している場合、このクラウドバックアップ情報はローカルコネクタシステムにのみ保存されます。

ここでは、接続されているStorageGRID システムに重要なクラウドバックアップデータをバックアップする方法について説明します。また、必要に応じて新しいコネクタにデータをリストアする方法についても説明します。



== 重要なクラウドバックアップデータをバックアップ

バックアップが必要なデータには、次の2種類があります。

* Cloud Backupデータベース
* インデックスカタログファイル（検索とリストア機能に使用）



NOTE: このCloud Backupデータは定期的にバックアップするように計画して、最新のデータに常時アクセスできるようにしてください。

ボリュームデータがCloud BackupデータベースまたはIndexed Catalogファイルに含まれることはありません。



=== Cloud Backupデータベースをバックアップします

Cloud Backupデータベースには、すべてのボリューム、バックアップファイル、バックアップポリシー、および構成情報のリストが含まれています。

.手順
. 適切なクレデンシャルを使用してコネクタホストシステムにログインします。
. 次のコマンドを入力して、MySQLコンテナシェルを入力します。
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
. コンテナシェルで、「env」を導入します。
. MySQL DBのパスワードが必要なので、キー「mysql_root_password」の値をコピーします。
. 次のコマンドを入力して、Cloud BackupのMySQL DBをバックアップします。
+
[source, cli]
----
mysqldump --user root --password -p cloud_backup --result-file=mysql.dump.cloud_backup.sql
----
. 次のコマンドを入力して、MySQL DockerコンテナからMySQL DBのバックアップをコピーします。
+
[source, cli]
----
docker cp ds_mysql_1:/mysql.dump.cloud_backup.sql .
----
. バックアップをネットワーク内の安全な場所にコピーします。ローカルStorageGRID システムは、その場所へのONTAP ボリュームのバックアップを作成する場合に使用できます。




=== インデックス付けされたカタログファイルをバックアップします

インデックスカタログは、検索と復元機能に使用されます。このディレクトリには、すべてのボリュームとすべてのバックアップファイルに関する情報が含まれているため、リストアするボリュームデータを検索する際に、迅速かつ効率的に検索を行うことができます。

. Connectorホストシステムで、ディレクトリを「/tmp」に変更します。
. [インデックスカタログ]フォルダを探します。文字列* catalog *から始まります。
. 次のコマンドを入力して、「catalog <_xxxxxx_>」フォルダを圧縮します。
+
[source, cli]
----
zip -r catalogxxxxxx.zip catalogxxxxxx
----
. 圧縮されたバックアップをネットワーク内の安全な場所にコピーします。




== Cloud Backupのデータを新しいコネクタにリストアします

オンプレミスコネクタに重大な障害が発生した場合は、新しいコネクタを取り付け、Cloud Backupデータを新しいコネクタにリストアする必要があります。

Cloud Backupシステムを稼働状態に戻すには、次の4つのタスクを実行する必要があります。

* 新しいBlueXPコネクタを取り付けます
* Cloud Backupデータベースをリストアします
* インデックス付けされたカタログファイルを復元します
* すべてのオンプレミスONTAP システムとStorageGRID システムをBlueXP UIに再検出します


システムが正常に動作していることを確認したら、新しいバックアップファイルを作成することをお勧めします。



=== 新しいオンプレミスLinuxホストに新しいコネクタをインストールします

新しいBlueXPコネクタをインストールするときは、元のコネクタにインストールしたものと同じリリースのソフトウェアをダウンロードしてください。Cloud Backupデータベース構造に定期的に変更が加えられると、新しいソフトウェアリリースで元のデータベースバックアップとの互換性がなくなる可能性があります。可能です https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-connectors.html#upgrade-the-connector-on-prem-without-internet-access["Backupデータベースをリストアした後、Connectorソフトウェアを最新バージョンにアップグレードします"^]。

. https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html["新しいオンプレミスLinuxホストにBlueXP Connectorをインストールします"^]
. 作成した管理者ユーザー資格情報を使用してBlueXPにログインします。




=== Cloud Backupデータベースをリストアします

. MySQLのバックアップを安全な場所から新しいコネクタホストにコピーします。
. 次のコマンドを使用して、MySQL Dockerコンテナにバックアップをコピーします。
+
[source, cli]
----
docker cp mysql.dump.cloud_backup.sql ds_mysql_1:/.
----
. 次のコマンドを使用してMySQLコンテナシェルを入力します。
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
. コンテナシェルで、「env」を導入します。
. MySQL DBのパスワードが必要なので、キー「mysql_root_password」の値をコピーします。
. 次のコマンドを使用して、Cloud Backup MySQL DBをリストアします。
+
[source, cli]
----
mysql -u root -p cloud_backup < mysql.dump.cloud_backup.sql
----
. 次のSQLコマンドを使用して、Cloud Backup MySQL DBが正しくリストアされたことを確認します。
+
[source, cli]
----
# mysql -u root -p cloud_backup
----
+
パスワードを入力します。

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
表示されているボリュームが、元の環境に存在していたボリュームと同じかどうかを確認します。





=== インデックス付けされたカタログファイルを復元します

. Indexed Catalogバックアップzipファイルを'セキュアな場所から'/tmpフォルダ内の新しいコネクタ・ホストにコピーします
. 次のコマンドを使用して、「catalxxxxxx.zip」ファイルを解凍します。
+
[source, cli]
----
unzip catalogxxxxxx.zip
----
. 「*ls *」コマンドを実行して、サブフォルダ「changes」と「snapshots」を含むフォルダ「catalogxxxxxx」が作成されていることを確認します。




=== ONTAP クラスタとStorageGRID システムを検出

. https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector["オンプレミスのONTAP 作業環境をすべて検出できます"^] 以前の環境で使用できていたものです。
. https://docs.netapp.com/us-en/cloud-manager-storagegrid/task-discover-storagegrid.html["StorageGRID システムを検出"^]。




=== StorageGRID 環境の詳細を設定

を使用して元のコネクタセットアップを行ったときの、ONTAP の作業環境に関連付けられているStorageGRID システムの詳細を追加します https://docs.netapp.com/us-en/cloud-manager-automation/index.html["BlueXP API"^]。

これらの手順は、StorageGRID にデータをバックアップするONTAP システムごとに実行する必要があります。

. 次のOAuth/token APIを使用して、認証トークンを抽出します。
+
[source, http]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100101 Firefox/108.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":admin@netapp.com,"password":"Netapp@123","grant_type":"password"}
> '
----
+
このAPIは、次のような応答を返します。次のように、認証トークンを取得できます。

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. テナンシー/外部/リソースAPIを使用して、作業環境IDとX-Agent-IDを抽出します。
+
[source, http]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
このAPIは、次のような応答を返します。「resourceIdentifier」の下の値は_WorkingEnvironment ID_を示し、「AgentID」の下の値は_x-agent-id_を示します。

. 作業環境に関連付けられているStorageGRID システムの詳細を使用して、クラウドバックアップデータベースを更新します。StorageGRID の完全修飾ドメイン名と、次に示すアクセスキーおよびストレージキーを入力してください。
+
[source, http]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




=== Cloud Backupの設定を確認

. 各ONTAP 作業環境を選択し、右パネルのバックアップ/リカバリ・サービスの横にある*バックアップの表示*をクリックします。
+
ボリュームに対して作成されたすべてのバックアップが表示されます。

. リストア・ダッシュボードの[検索とリストア]セクションで、[*インデックス設定*]をクリックします。
+
インデックスカタログが有効になっている作業環境が、以前に有効なままであることを確認します。

. [検索と復元]ページで、いくつかのカタログ検索を実行して、インデックス付けされたカタログの復元が正常に完了したことを確認します。

