---
sidebar: sidebar 
permalink: task-register-snapCenter-plug-in-for-vmware-vsphere.html 
keywords: register, registration, SnapCenter Plug-in for VMware vSphere 
summary: BlueXPでSnapCenter Plug-in for VMware vSphereホストを登録します。 
---
= SnapCenter Plug-in for VMware vSphereホストを登録
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
表示するデータストアと仮想マシンについては、BlueXPでSnapCenter Plug-in for VMware vSphereホストを登録する必要があります。SnapCenter Plug-in for VMware vSphereホストを登録できるのは、管理者アクセス権を持つユーザだけです。


NOTE: BlueXPでは、複数のSnapCenter Plug-in for VMware vSphereホストを登録できます。ただし、登録後にSnapCenter Plug-in for VMware vSphereホストを削除することはできません。

.手順
. BlueXP UIで、[*保護*>*バックアップとリカバリ*>*仮想マシン*]をクリックします。
. [*設定*]ドロップダウンから、[* SnapCenter Plug-in for VMware vSphere*]をクリックします。
. [* SnapCenter Plug-in for VMware vSphere*の登録]をクリックします。
. 次の情報を指定します。
+
.. SnapCenter Plug-in for VMware vSphereフィールドで、SnapCenter Plug-in for VMware vSphereホストのFQDNまたはIPアドレスを指定します。
.. [ポート]フィールドで、SnapCenter Plug-in for VMware vSphereホストが実行されているポート番号を指定します。
+
SnapCenter Plug-in for VMware vSphereホストとBlueXPの間で通信するためには、ポートが開いていることを確認する必要があります。

.. Username and Passwordフィールドで、管理者ロールを持つユーザのクレデンシャルを指定します。


. [*Register] をクリックします。


* 終了後 *

[バックアップとリカバリ]*>*[仮想マシン]*をクリックして、登録済みのSnapCenter Plug-in for VMware vSphereホストを使用して保護されているすべてのデータストアと仮想マシンを表示します。
