---
sidebar: sidebar 
permalink: task-add-host-discover-oracle-databases.html 
keywords: Cloud Manager, BlueXP, SnapCenter Plug-in for Oracle, Oracle, database, host, deploy, add host, discover 
summary: 各OracleデータベースホストにSnapCenter Plug-in for Oracleを導入します。 
---
= SnapCenter Plug-in for Oracleを導入し、データベースホストを追加します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for Oracleを各Oracleデータベースホストに導入し、データベースホストを追加し、ホスト上のデータベースを検出して、ポリシーを割り当ててバックアップを作成する必要があります。

* データベースホストでSSHが有効になっている場合は、次のいずれかの方法でプラグインを導入できます。
+
** プラグインを導入し、SSHオプションを使用してホストUIを追加します。 <<SSHオプションを使用してプラグインを導入し、UIからホストを追加します,詳細はこちら。>>。
** スクリプトを使用してプラグインを導入し、手動オプションを使用してUIからホストを追加します。 <<スクリプトを使用してプラグインを導入し、手動オプションを使用してUIからホストを追加します,詳細はこちら。>>。


* SSHが無効な場合は、プラグインを手動で導入し、手動オプションを使用してUIからホストを追加します。 <<プラグインを手動で導入し、手動オプションを使用してUIからホストを追加します,詳細はこちら。>>。




== 前提条件

ホストを追加する前に、前提条件を満たしていることを確認する必要があります。

* 作業環境とコネクタを作成しておきます。
* コネクタが作業環境とOracleデータベースホストに接続されていることを確認してください。
* BlueXPユーザーに「アカウント管理者」の役割があることを確認します。
* Java 11（64ビット）のOracle JavaまたはOpenJDKが各Oracleデータベースホストにインストールされていて、JAVA_HOME変数が適切に設定されていることを確認します。
* SnapCenter ユーザを作成し、SnapCenter ユーザにsudoを設定しておく必要があります。詳細については、を参照してください <<SnapCenter ユーザにsudoを設定します>>。
* SSHベースの導入を使用する場合は、コネクタでSSHポートへの通信が有効になっていることを確認します（デフォルト：22）。
* 操作が機能するように、コネクタがプラグインポート（デフォルト：8145）との通信が有効になっていることを確認します。




=== SnapCenter ユーザにsudoを設定します

SnapCenter ユーザを作成し、そのユーザにsudoを設定する必要があります。

* 手順 *

. Connector VMにログインします。
. SnapCenter Linuxホストプラグインバイナリをダウンロードします。
`sudo docker exec -it cloudmanager_scs_cloud curl -X GET 'http://127.0.0.1/deploy/downloadLinuxPlugin'`
. ベースマウントパスを取得します。
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. 1～16の行を、*_base_mount_path/_version_/sc-linux-host-plugin/*にある*ORACLE_checksum_scs.txt *ファイルからコピーします。
. Oracleデータベース・ホストにログインし、次の手順を実行します。
+
.. SnapCenter ユーザアカウントと秘密鍵のペアを作成し、権限を割り当てます。詳細については、を参照してください https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/managing-users.html#create-user-account["ユーザアカウントを作成します"^]。
.. 手順4でコピーした行を、visudo Linuxユーティリティを使用して、/etc/sudoers_fileに貼り付けます。
+
上記の行で、<LINUXUSER> を作成したSnapCenter ユーザーに置き換え、visudoユーティリティでファイルを保存します。







== SSHオプションを使用してプラグインを導入し、UIからホストを追加します

. BlueXP UIで、[*保護*>*バックアップとリカバリ*>*アプリケーション*]をクリックします。
. アプリケーションの検出をクリックします。
. クラウドネイティブ*を選択し、*次へ*をクリックします。
+
SnapCenter system_roleを持つサービスアカウントが作成され、このアカウントのすべてのユーザに対してスケジュールされたデータ保護処理が実行されます。

+
** *Account*>*Manage Account*>*Members*をクリックして、サービスアカウントを表示します。
+

NOTE: スケジュールされたバックアップ処理を実行するには、サービスアカウント（_SnapCenter -account-<accountId>>）を使用します。サービスアカウントは絶対に削除しないでください。



. [Add Host]ページで、次の手順を実行します。
+
.. SSHを使用して*を選択します。
.. プラグインをインストールするホストのFQDNまたはIPアドレスを指定します。
.. ユーザ名を指定します（<<Configure a sudo for SnapCenter user,sudo SnapCenter ユーザ>>）を使用して、プラグインパッケージをホストにコピーします。
.. SSHとプラグインポートを指定します。
+
デフォルトのSSHポートは22で、プラグインポートは8145です。

+
プラグインをインストールしたら、アプリケーションホスト上のSSHポートを閉じることができます。SSHポートは、他のプラグイン処理には必要ありません。

.. コネクタを選択します。
.. （オプション）コネクタとホストの間でキーレス認証が有効になっていない場合は、ホストとの通信に使用するSSH秘密鍵を指定する必要があります。
+

NOTE: SSH秘密鍵はアプリケーション内のどこにも保存されず、他の操作には使用されません。

.. 「 * 次へ * 」をクリックします。
+
*** ホスト上のすべてのデータベースが表示されます。データベースでOS認証が無効になっている場合は、* Configure *をクリックしてデータベース認証を設定する必要があります。詳細については、を参照してください <<Oracleデータベースのクレデンシャルを設定する>>。
*** すべてのホストを表示するには、[*設定*]をクリックし、[*ホスト*]を選択します。データベース・ホストを削除するには'[* Remove *]をクリックします
+

NOTE: 特定のホストを表示するフィルタが機能しない。フィルタでホスト名を指定すると、すべてのホストが表示されます。

*** [*設定]をクリックし、[*ポリシー]を選択して、組み込みポリシーを表示します。組み込みのポリシーを確認して、要件に合わせて編集することも、新しいポリシーを作成することもできます。








== スクリプトを使用してプラグインを導入し、手動オプションを使用してUIからホストを追加します

OracleホストでSnapCenter ユーザに対してSSHキーベースの認証が有効になっている場合は、次の手順を実行してプラグインを導入できます。手順を実行する前に、コネクタへのSSH接続が有効になっていることを確認してください。

* 手順 *

. Connector VMにログインします。
. ベースマウントパスを取得します。
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. コネクタに用意されているヘルパースクリプトを使用して、プラグインを導入します。
`sudo <base_mount_path>/scripts/oracle_plugin_copy_and_install.sh --host <host_name> --sshkey <ssh_key_file> --username <user_name> --port <ssh_port> --pluginport <plugin_port> --installdir <install_dir>`
+
** host_nameはOracleホストの名前です。これは必須パラメータです。
** ssh_key_fileはSnapCenter ユーザのSSHキーで、Oracleホストへの接続に使用します。これは必須パラメータです。
** user_name：Oracleホストに対するSSH権限を持つSnapCenter ユーザ。これはオプションパラメータです。デフォルト値はec2-userです。
** ssh_port：Oracleホスト上のSSHポート。これはオプションパラメータです。デフォルト値は22です
** plugin_port：プラグインで使用するポート。これはオプションパラメータです。デフォルト値は8145です
** install_dir：プラグインが配置されるディレクトリ。これはオプションのパラメータです。デフォルト値は/optです。
+
例：
`sudo /var/lib/docker/volumes/service-manager-2_cloudmanager_scs_cloud_volume/_data/scripts/oracle_plugin_copy_and_install.sh --host xxx.xx.x.x --sshkey /keys/netapp-ssh.ppk`



. BlueXP UIで、[*保護*>*バックアップとリカバリ*>*アプリケーション*]をクリックします。
. アプリケーションの検出をクリックします。
. クラウドネイティブ*を選択し、*次へ*をクリックします。
+
SnapCenter system_roleを持つサービスアカウントが作成され、このアカウントのすべてのユーザに対してスケジュールされたデータ保護処理が実行されます。

+
** *Account*>*Manage Account*>*Members*をクリックして、サービスアカウントを表示します。
+

NOTE: スケジュールされたバックアップ処理を実行するには、サービスアカウント（_SnapCenter -account-<accountId>>）を使用します。サービスアカウントは絶対に削除しないでください。



. [Add Host]ページで、次の手順を実行します。
+
.. [* Manual*]を選択します。
.. プラグインを導入するホストのFQDNまたはIPアドレスを指定します。
+
FQDNまたはIPアドレスを使用して、コネクタがデータベースホストと通信できることを確認します。

.. プラグインポートを指定します。
+
デフォルトポートは8145です。

.. コネクタを選択します。
.. チェックボックスを選択して、プラグインがホストにインストールされていることを確認します
.. [*アプリケーションの検出*]をクリックします。
+
*** ホスト上のすべてのデータベースが表示されます。データベースでOS認証が無効になっている場合は、* Configure *をクリックしてデータベース認証を設定する必要があります。詳細については、を参照してください <<Oracleデータベースのクレデンシャルを設定する>>。
*** すべてのホストを表示するには、[*設定*]をクリックし、[*ホスト*]を選択します。データベース・ホストを削除するには'[* Remove *]をクリックします
+

NOTE: 特定のホストを表示するフィルタが機能しない。フィルタでホスト名を指定すると、すべてのホストが表示されます。

*** [*設定]をクリックし、[*ポリシー]を選択して、組み込みポリシーを表示します。組み込みのポリシーを確認して、要件に合わせて編集することも、新しいポリシーを作成することもできます。








== プラグインを手動で導入し、手動オプションを使用してUIからホストを追加します

OracleデータベースホストでSSHキーベースの認証が有効になっていない場合は、次の手動手順を実行してプラグインを導入し、manualオプションを使用してUIからホストを追加する必要があります。

* 手順 *

. Connector VMにログインします。
. SnapCenter Linuxホストプラグインバイナリをダウンロードします。
`sudo docker exec -it cloudmanager_scs_cloud curl -X GET 'http://127.0.0.1/deploy/downloadLinuxPlugin'`
. ベースマウントパスを取得します。
`sudo docker volume ls | grep scs_cloud_volume | awk {'print $2'} | xargs sudo docker volume inspect | grep Mountpoint`
. ダウンロードしたプラグインのバイナリパスを取得します。
`sudo ls <base_mount_path> $(sudo docker ps|grep -Po "cloudmanager_scs_cloud:.*? "|sed -e 's/ *$//'|cut -f2 -d":")/sc-linux-host-plugin/snapcenter_linux_host_plugin_scs.bin`
. scpまたはその他の代替方法を使用して、Oracleデータベースホストのそれぞれにcopy_snapcenter linux_host_plugin_scs.bin _をコピーします。
+
_snapcenter_linux_host_plugin_scs.bin_は、SnapCenter ユーザがアクセスできる場所にコピーする必要があります。

. SnapCenter ユーザアカウントを使用してOracleデータベースホストにログインし、次のコマンドを実行してバイナリの実行権限を有効にします。
`chmod +x snapcenter_linux_host_plugin_scs.bin`
. Oracleプラグインをsudo SnapCenter ユーザとして導入します。
`./snapcenter_linux_host_plugin_scs.bin -i silent -DSPL_USER=<snapcenter-user>`
. connector VMのcopy_certificate.p12_from_<base_mount_path>/client/certificate/_pathを、プラグインホスト上の_/var/opt/snapcenter/spl/etc/にコピーします。
. _/var/opt/snapcenter/spl/etcに移動し、keytoolコマンドを実行して証明書をインポートします。
`keytool -v -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore keystore.jks -deststoretype JKS -srcstorepass snapcenter -deststorepass snapcenter -srcalias agentcert -destalias agentcert -noprompt`
. SPLを再起動します。 `systemctl restart spl`
. コネクタから次のコマンドを実行して、コネクタからプラグインに到達できることを確認します。
`docker exec -it cloudmanager_scs_cloud curl -ik \https://<FQDN or IP of the plug-in host>:<plug-in port>/getVersion --cert /config/client/certificate/certificate.pem --key /config/client/certificate/key.pem`
. BlueXP UIで、[*保護*>*バックアップとリカバリ*>*アプリケーション*]をクリックします。
. アプリケーションの検出をクリックします。
. クラウドネイティブ*を選択し、*次へ*をクリックします。
+
SnapCenter system_roleを持つサービスアカウントが作成され、このアカウントのすべてのユーザに対してスケジュールされたデータ保護処理が実行されます。

+
** *Account*>*Manage Account*>*Members*をクリックして、サービスアカウントを表示します。
+

NOTE: スケジュールされたバックアップ処理を実行するには、サービスアカウント（_SnapCenter -account-<accountId>>）を使用します。サービスアカウントは絶対に削除しないでください。



. [Add Host]ページで、次の手順を実行します。
+
.. [* Manual*]を選択します。
.. プラグインを導入するホストのFQDNまたはIPアドレスを指定します。
+
FQDNまたはIPアドレスを使用して、コネクタがデータベースホストと通信できることを確認します。

.. プラグインポートを指定します。
+
デフォルトポートは8145です。

.. コネクタを選択します。
.. チェックボックスを選択して、プラグインがホストにインストールされていることを確認します
.. [*アプリケーションの検出*]をクリックします。
+
*** ホスト上のすべてのデータベースが表示されます。データベースでOS認証が無効になっている場合は、* Configure *をクリックしてデータベース認証を設定する必要があります。詳細については、を参照してください <<Oracleデータベースのクレデンシャルを設定する>>。
*** すべてのホストを表示するには、[*設定*]をクリックし、[*ホスト*]を選択します。データベース・ホストを削除するには'[* Remove *]をクリックします
+

NOTE: 特定のホストを表示するフィルタが機能しない。フィルタでホスト名を指定すると、すべてのホストが表示されます。

*** [*設定]をクリックし、[*ポリシー]を選択して、組み込みポリシーを表示します。組み込みのポリシーを確認して、要件に合わせて編集することも、新しいポリシーを作成することもできます。








== Oracleデータベースのクレデンシャルを設定する

Oracleデータベースに対してデータ保護処理を実行する際に使用するクレデンシャルを設定する必要があります。

* 手順 *

. データベースでOS認証が無効になっている場合は、* Configure *をクリックしてデータベース認証を設定する必要があります。
. ユーザ名、パスワード、およびポートの詳細を指定します。
+
データベースがASMにある場合は、ASMも設定する必要があります。

+
Oracleユーザにはsysdba権限が必要で、ASMユーザにはSYSASM権限が必要です。

. [*Configure*] をクリックします。

