---
sidebar: sidebar 
permalink: task-restore-hana-backup.html 
keywords: restore, mount application backups, SAP HANA database 
summary: SAP HANAデータベースをクラウドからオンプレミスのSnapCenterサーバにリストアできます。 
---
= SAP HANAデータベースをリストア
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SAP HANAデータベースは任意のホストにリストアできます。

* 手順 *

. BlueXP UIで、[*保護*>*バックアップとリカバリ*>*アプリケーション*]をクリックします。
. [Filter by]*フィールドで、フィルタ* Type *を選択し、ドロップダウンから* HANA *を選択します。
. リストアするデータベースに対応する *View Details* をクリックし、 *Restore* をクリックします。
. [Restore options]ページで、次のいずれかを指定します。
+
.. NAS環境の場合は、オブジェクトストアからリストアするボリュームのエクスポート先となるホストのFQDNまたはIPアドレスを指定します。
.. SAN環境の場合、オブジェクトストアからリストアするボリュームのLUNをマッピングするホストのイニシエータを指定します。


. スナップショットがアーカイブストレージにある場合は、アーカイブストレージからデータをリストアする優先度を選択します。
. ソースストレージに十分なスペースがないか、ソースストレージが停止している場合は、*[ストレージの場所を変更]*を選択します。
+
[ストレージの場所の変更]*を選択した場合は、デスティネーションボリュームにサフィックスを追加できます。このチェックボックスをオンにしていない場合、デフォルトではデスティネーションボリュームに*_restore *が追加されます。

. 「 * 次へ * 」をクリックします。
. [ストレージマッピング]ページで、オブジェクトストアからリストアしたデータを格納する代替ストレージの場所の詳細を指定します。
. 「 * 次へ * 」をクリックします。
. 詳細を確認して、 * リストア * をクリックします。


この処理では、指定したホスト上の選択したバックアップのストレージエクスポートのみが実行されます。ファイルシステムを手動でマウントし、データベースを起動する必要があります。ボリュームを利用したあと、ストレージ管理者はONTAP クラスタからボリュームを削除できます。

SAP HANAデータベースを起動する方法については、を参照してください https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-introduction.html["TR-4667：『Automating SAP HANA System Copy and Clone Operations with SnapCenter 』"^]。


NOTE: リストア処理が完了しない場合は、ジョブモニタにリストア処理が失敗したことが表示されるまで、リストアプロセスを再試行しないでください。ジョブモニタにリストア処理が失敗したことが表示される前にリストアプロセスを再試行すると、リストア処理は再び失敗します。ジョブモニタのステータスが「Failed」と表示されたら、リストアプロセスを再試行できます。
