---
sidebar: sidebar 
permalink: task-register-snapCenter-plug-in-for-vmware-vsphere.html 
keywords: register, registration, SnapCenter Plug-in for VMware vSphere 
summary: BlueXPでSnapCenter Plug-in for VMware vSphereホストを登録します。 
---
= BlueXP バックアップおよびリカバリを使用して VMware vSphere ホスト用の SnapCenter プラグインを登録する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
データストアと仮想マシンを表示するには、BlueXP バックアップおよびリカバリで VMware vSphere ホスト用の SnapCenter プラグインを登録する必要があります。SnapCenter Plug-in for VMware vSphereホストを登録できるのは、管理者アクセス権を持つユーザだけです。

.手順
. BlueXP UIで、[*保護*>*バックアップとリカバリ*>*仮想マシン*]をクリックします。
. [*設定*]ドロップダウンから、[* SnapCenter Plug-in for VMware vSphere*]をクリックします。
. [* SnapCenter Plug-in for VMware vSphere*の登録]をクリックします。
. 次の情報を指定します。
+
.. SnapCenter Plug-in for VMware vSphereフィールドで、SnapCenter Plug-in for VMware vSphereホストのFQDNまたはIPアドレスを指定します。
.. [ポート]フィールドで、SnapCenter Plug-in for VMware vSphereホストが実行されているポート番号を指定します。
+
デフォルトの8144ポートで実行されているオンプレミスのSnapCenter Plug-in for VMware vSphereホストと、任意のクラウドプロバイダ（Amazon Web Services、Microsoft Azure、Google Cloud Platform）またはオンプレミスで実行されているBlueXPコネクタインスタンスの間で通信が開かれていることを確認する必要があります。

.. [Username]フィールドと[Password]フィールドに、管理者ロールを持つvCenterユーザのクレデンシャルを指定します。


. [*Register] をクリックします。


* 終了後 *

[バックアップとリカバリ]*>*[仮想マシン]*をクリックして、登録済みのSnapCenter Plug-in for VMware vSphereホストを使用して保護されているすべてのデータストアと仮想マシンを表示します。
