---
sidebar: sidebar 
permalink: task-create-policies-apps.html 
keywords: policy, create, pre-canned polices, custom policies, protection policies 
summary: 組み込みポリシーを使用するか、独自のポリシーを作成してアプリケーションを保護します。 
---
= アプリケーションをバックアップするポリシーを作成する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
組み込みのポリシーのいずれかを使用するか、カスタムポリシーを作成してアプリケーションデータをクラウドにバックアップできます。組み込みのポリシーを編集しない場合は、ポリシーを作成できます。

組み込みのポリシーは次のとおりです。

|===
| ポリシー名 | ラベル | 保持値 


 a| 
1 年ごとの LTR
 a| 
毎日
 a| 
366



 a| 
5 年ごとの LTR
 a| 
毎日
 a| 
1830 年に



 a| 
7 年ごとの LTR
 a| 
毎週
 a| 
370



 a| 
10 年間の月単位 LTR
 a| 
毎月
 a| 
120

|===
* 手順 *

. BlueXP UIで、[*保護*>*バックアップとリカバリ*>*アプリケーション*]をクリックします。
. [設定]ドロップダウンから、[*ポリシー*>*ポリシーの作成*]をクリックします。
. [ポリシーの詳細]セクションで、ポリシー名を指定します。
. 保持セクションで、保持タイプの1つを選択し、保持するバックアップの数を指定します。
. バックアップストレージソースとして、プライマリまたはセカンダリを選択します。
. （オプション）コストを最適化するために一定の日数が経過したバックアップをオブジェクトストアからアーカイブストレージに移動する場合は、「*ティアBackup to Archival *」チェックボックスを選択します。
+
ONTAP 9.10.1以降とAmazon Web ServicesまたはAzureをクラウドプロバイダとして使用している場合にのみ、オブジェクトストアからアーカイブストレージにバックアップを移動できます。各クラウドプロバイダにアーカイブアクセス階層を設定する必要があります。

. [ 作成（ Create ） ] をクリックします。
+
カスタマイズしたポリシーは編集、コピー、および削除できます。

+

NOTE: アプリケーションに関連付けられているポリシーを編集または削除することはできません。


