---
sidebar: sidebar 
permalink: task-register-snapCenter-plug-in-for-vmware-vsphere.html 
keywords: register, registration, SnapCenter Plug-in for VMware vSphere 
summary: SnapCenter Plug-in for VMware vSphereをCloud Managerに登録します。 
---
= SnapCenter Plug-in for VMware vSphereの登録
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
データストアと仮想マシンをCloud Managerに表示するには、SnapCenter Plug-in for VMware vSphereをCloud Managerに登録する必要があります。SnapCenter Plug-in for VMware vSphereの登録は、管理者アクセス権を持つユーザのみが実行できます。


NOTE: 複数のSnapCenter Plug-in for VMware vSphereを登録できます。ただし、一度登録すると、SnapCenter Plug-in for VMware vSphereを削除できなくなります。

.手順
. Cloud Manager UIで、* Backup & Restore *>* Virtual Machines *をクリックします。
. [*設定*]ドロップダウンから、[* SnapCenter Plug-in for VMware vSphere*]をクリックします。
. [* SnapCenter Plug-in for VMware vSphere*の登録]をクリックします。
. 次の情報を指定します。
+
.. SnapCenter Plug-in for VMware vSphereフィールドで、SnapCenter Plug-in for VMware vSphereのFQDNまたはIPアドレスを指定します。
.. Portフィールドで、SnapCenter Plug-in for VMware vSphereを実行しているポート番号を指定します。
+
SnapCenter Plug-in for VMware vSphereとCloud Backup for Virtual Machinesの間の通信に使用するポートが開いていることを確認する必要があります。

.. Username and Passwordフィールドで、管理者ロールを持つユーザのクレデンシャルを指定します。


. [*Register] をクリックします。


* 終了後 *

[*バックアップとリストア>仮想マシン*]をクリックして、登録済みのSnapCenter Plug-in for VMware vSphereを使用して保護対象となるすべてのデータストアおよび仮想マシンを表示します。
