---
sidebar: sidebar 
permalink: task-report-inventory.html 
keywords: cloud backup, backup and recovery service, backup and recovery, backup, restore, report, inventory 
summary: BlueXPのバックアップ/リカバリレポートを使用すると、組織で定義されたポリシーに従って重要なデータを確実に保護し、コンプライアンスプロセスの監査を効率的にサポートできます。バックアップインベントリレポートでは、特定のアカウント、作業環境、またはSVMインベントリのすべてのバックアップを表示できます。 
---
= データ保護の適用範囲に関するレポートを作成します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPのバックアップ/リカバリレポートを使用すると、組織で定義されたポリシーに従って重要なデータを確実に保護し、コンプライアンスニーズを監査できます。

BlueXPのバックアップとリカバリレポートを使用すると、次のことを実現できます。

* *運用の可視性*:データ保護、バックアップ成功率、およびバックアップウィンドウとビジネスニーズとの整合性に関するサービスレベルアグリーメントを監視します。
* *コンプライアンスと監査*:内部および外部の監査プロセスで運用レポートと在庫レポートを使用して、コンプライアンスを継続的に監視します。



NOTE: レポートアクティビティはジョブ監視ログで監視されるため、すべてのアクティビティを監査できます。 link:task-monitor-backup-jobs.html["ジョブ監視について説明します"]。



== レポートの範囲

BlueXPのバックアップとリカバリのレポートには、次の情報が表示されます。

* *コネクタの場所*：オンプレミスまたはクラウド
* *ソース*：Cloud Volumes ONTAPボリューム、オンプレミスのONTAPボリューム、アプリケーション、Kubernetes永続ボリューム
* *デスティネーション*：任意のクラウドプロバイダ、NetApp StorageGRID、ONTAP S3
* * ONTAPバージョン*：9.13.0




== バックアップインベントリレポートを作成します

BlueXPの[Backup and recovery Reports]タブでは、[Backup Inventory]レポートを作成してその内容をフィルタリングできます。Backup Inventoryレポートでは、特定のアカウント、作業環境、またはSVMインベントリのすべてのバックアップを表示できます。

Backup Inventoryレポートには、次の情報などが表示されます。

* アカウント、作業環境、およびSVM
* 保護されているボリュームと保護されていないボリューム
* バックアップターゲット
* バックアップポリシーが適用されました
* 暗号化形式（プロバイダ管理キーまたはユーザ管理キー）
* DataLockとランサムウェア対策のステータス（ガバナンス、コンプライアンス、なし）
* アーカイブ有効ステータス
* バックアップコピーの数
* バックアップ・タイプ（スケジュール・バックアップまたはユーザーが開始したアドホック・バックアップ）
* ストレージクラス
* Snapshot ラベル



NOTE: Backup Inventoryレポートには、期限切れまたは失敗したバックアップ情報は含まれません。

レポートの上部には、次の情報を示すグラフが表示されます。

* 対象となるボリュームのうち、少なくとも1つのバックアップが含まれているボリュームの数
* アクティブでないボリュームとアクティブなボリュームの合計


Backup Inventoryレポートには、次のチャートが表示されます。

* *ボリュームのバックアップステータス*：選択した範囲について、保護されているボリュームと保護されていないボリュームとの比較が表示されます。
* *バックアップ数別のボリューム*：このボリュームで使用可能なバックアップコピーの数でボリュームをグループ化します。


.手順
. トップメニューから*[レポート]*を選択します。
. [インベントリのバックアップ]*を選択します。
. [レポートの作成]*を選択します。
. アカウント、作業環境、およびSVMを選択します。
+

TIP: 複数の作業環境とSVMを選択できます。

. 期間（[Last 24 hours]、[week]、または[month]）を選択します。
. （オプション）ジョブステータスで結果をフィルタリングします。
. （オプション）*[Download CSV]*を選択して、レポートの内容を.csv形式でエクスポートします。




== Data Protection Job Activityレポートを作成します

プロアクティブな監視により、エコシステム内のすべてのリソースの監視に必要な労力を軽減できます。ONTAP 9.13.0以降では、Snapshot、バックアップ、クローニング、リストアの各処理に関する情報がデータ保護ジョブアクティビティレポートに表示されるようになりました。この情報は、SLAを監視したり、バックアップとリカバリの速度を追跡したりする際に使用できます。

レポート『環境BlueXP Backup and Recovery Operations for Cloud Volumes ONTAP、オンプレミス、アプリケーション、Kubernetes』

Data Protection Job Activityレポートには、次の情報などが表示されます。

* アカウント、作業環境、およびSVM
* ジョブ・タイプ（バックアップまたはリストア）
* リソース名（ボリュームまたはアプリケーション）
* ジョブステータス
* 開始時刻と終了時刻と期間
* バックアップジョブのポリシー名
* バックアップジョブのSnapshotラベル


ページ上部のグラフには、次の情報が表示されます。

* タイプ別のジョブ
+
** ONTAPボリュームのバックアップジョブとリストアジョブの数
** アプリケーションのバックアップジョブとリストアジョブの数
** 仮想マシンのバックアップジョブとリストアジョブの数
** Kubernetesのバックアップジョブとリストアジョブの数


* 毎日のジョブアクティビティ


.手順
. トップメニューから*[レポート]*を選択します。
. [データ保護ジョブアクティビティ]*を選択します。
. [レポートの作成]*を選択します。
. アカウント、作業環境、およびSVMを選択します。
. 期間（[Last 24 hours]、[week]、または[month]）を選択します。
. （オプション）ジョブステータス、ジョブタイプ（バックアップまたはリストア）、およびリソースで結果をフィルタリングします。
. （オプション）*[Download CSV]*を選択して、レポートの内容を.csv形式でエクスポートします。

