---
sidebar: sidebar 
permalink: task-create-policies-vms.html 
keywords: create policy, protection policies, predefined policies, custom policies 
summary: 仮想マシンをバックアップするポリシーを作成します 
---
= 仮想マシンをバックアップするポリシーを作成します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ポリシーを作成するか、BlueXPで使用可能な次の定義済みポリシーのいずれかを使用できます。

|===
| ポリシー名 | ラベル | 保持値 


 a| 
1 年ごとの LTR
 a| 
毎日
 a| 
366



 a| 
5 年ごとの LTR
 a| 
毎日
 a| 
1830 年に



 a| 
7 年ごとの LTR
 a| 
毎週
 a| 
370



 a| 
10 年間の月単位 LTR
 a| 
毎月
 a| 
120

|===
事前定義されたポリシーを編集しない場合は、ポリシーを作成する必要があります。

.手順
. [仮想マシン]ページの[設定]ドロップダウンリストから、[*ポリシー*]を選択します。
. ［*ポリシーの作成*］をクリックします。
. [ポリシーの詳細]セクションで、ポリシー名を指定します。
. 保持セクションで、保持タイプの1つを選択し、保持するバックアップの数を指定します。
. バックアップストレージソースとして、プライマリまたはセカンダリを選択します。
. （オプション）コストを最適化するために一定の日数が経過したあとにバックアップをオブジェクトストアからアーカイブストレージに移動する場合は、「* Tier Backups to Archival *」チェックボックスをオンにし、バックアップをアーカイブするまでの日数を入力します。
+
ONTAP 9.10.1以降とAmazon Web ServicesまたはAzureをクラウドプロバイダとして使用している場合にのみ、オブジェクトストアからアーカイブストレージにバックアップを移動できます。各クラウドプロバイダにアーカイブアクセス階層を設定する必要があります。

. [ 作成（ Create ） ] をクリックします。
+
カスタマイズしたポリシーは編集、コピー、および削除できます。

+

NOTE: 仮想マシンに関連付けられているポリシーを編集または削除することはできません。


