---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery, protection' 
summary: BlueXPのバックアップとリカバリの新機能をご紹介します。 
---
= BlueXPのバックアップとリカバリの最新情報
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPのバックアップとリカバリの新機能をご紹介します。



== 2025 年 6 月 9 日

このBlueXP  バックアップ/リカバリリリースには、次の更新が含まれています。



=== インデックスカタログのサポートの更新

2025年2月、データ復元の「検索と復元」メソッドで使用するインデックス作成機能のアップデート（インデックスカタログv2）を導入しました。前回のリリースでは、オンプレミス環境におけるデータインデックス作成のパフォーマンスが大幅に向上しました。今回のリリースでは、Amazon Web Services、Microsoft Azure、Google Cloud Platform（GCP）環境でインデックスカタログがご利用いただけるようになりました。

新規のお客様の場合、すべての新規環境では Indexed Catalog v2 がデフォルトで有効になっています。既存のお客様の場合は、環境のインデックスを再作成することで Indexed Catalog v2 を活用できます。

.インデックス作成を有効にするにはどうすればよいですか。
データのリストアにSearch & Restore方式を使用する前に、ボリュームまたはファイルのリストア元となる各ソース作業環境で[Indexing]を有効にする必要があります。検索と復元を実行するときは、「*インデックスを有効にする*」オプションを選択します。

インデックスカタログはすべてのボリュームとバックアップ ファイルを追跡できるため、検索が迅速かつ効率的になります。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["検索と復元を使用してONTAPデータを復元する方法"]。



=== Azure プライベート リンク エンドポイントとサービス エンドポイント

BlueXP バックアップ＆リカバリは通常、クラウドプロバイダーとプライベートエンドポイントを確立し、様々な保護タスクを処理します。今回のリリースでは、BlueXP バックアップ＆リカバリによるプライベートエンドポイントの自動作成を有効または無効にできるオプション設定が導入されました。これは、プライベートエンドポイントの作成プロセスをより細かく制御したい場合に役立ちます。

この設定を無効にすると、BlueXP のバックアップとリカバリが正常に機能するために、プライベートエンドポイントを手動で作成する必要があります。適切な接続がないと、バックアップとリカバリのタスクを正常に実行できない可能性があります。



=== ONTAP S3 での SnapMirror からクラウドへの再同期のサポート

前回のリリースでは、SnapMirror to Cloud Resync（SM-C Resync）のサポートが導入されました。この機能は、NetApp環境におけるボリューム移行時のデータ保護を効率化します。今回のリリースでは、ONTAP S3に加え、WasabiやMinIOなどの他のS3互換プロバイダーでもSM-C Resyncのサポートが追加されました。



=== StorageGRID 用の独自のバケットを用意する

作業環境のオブジェクトストレージにバックアップファイルを作成すると、BlueXP バックアップ＆リカバリはデフォルトで、ユーザーが設定したオブジェクトストレージアカウント内にバックアップファイル用のコンテナ（バケットまたはストレージアカウント）を作成します。以前は、この設定をオーバーライドして、Amazon S3、Azure Blob Storage、Google Cloud Storage 用の独自のコンテナを指定できました。今回のリリースでは、独自の StorageGRID オブジェクトストレージコンテナを使用できるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["独自のオブジェクトストレージコンテナを作成する"]



== 2025年5月13日

このBlueXP  バックアップ/リカバリリリースには、次の更新が含まれています。



=== ボリューム移行のためのSnapMirrorからクラウドへの再同期

SnapMirrorからクラウドへの再同期機能は、NetApp環境でのボリューム移行時のデータ保護と継続性を合理化します。SnapMirror論理レプリケーション（LRSE）を使用して、オンプレミスのNetApp環境から別の環境、またはCloud Volumes ONTAPやCloud Volumes Serviceなどのクラウドベースのソリューションにボリュームを移行する場合、SnapMirrorからクラウドへの再同期により、既存のクラウドバックアップに影響を与えずに運用できます。

この機能により、時間とリソースを大量に消費するベースライン再処理が不要になり、移行後もバックアップ処理を継続できます。この機能は、FlexVolとFlexGroupの両方をサポートするワークロードマイグレーションシナリオで役立ちます。ONTAPバージョン9.16.1以降で使用できます。

SnapMirrorからクラウドへの再同期は、環境全体でバックアップの継続性を維持することで運用効率を高め、ハイブリッドクラウドやマルチクラウドのデータ管理の複雑さを軽減します。

再同期処理の実行方法の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-migrate-volumes-snapmirror-cloud-resync.html["SnapMirrorを使用したボリュームのクラウドへの再同期"]。



=== サードパーティ製MinIOオブジェクトストアのサポート（プレビュー）

BlueXP  のバックアップとリカバリでは、MinIOを中心にサードパーティのオブジェクトストアもサポートされるようになりました。この新しいプレビュー機能を使用すると、バックアップとリカバリのニーズに合わせてS3互換オブジェクトストアを活用できます。

このプレビュー版では、すべての機能がリリースされる前に、サードパーティのオブジェクトストアとの強固な統合を確保したいと考えています。この新しい機能について検討し、サービスの強化に役立つフィードバックを提供することをお勧めします。


IMPORTANT: この機能は本番環境では使用しないでください。

*プレビューモードの制限*

この機能はプレビュー中ですが、次のような制限があります。

* Bring Your Own Bucket（BYOB）はサポートされていません。
* ポリシーでDataLockを有効にすることはできません。
* ポリシーでアーカイブモードを有効にすることはできません。
* オンプレミスのONTAP環境のみがサポートされます。
* MetroClusterはサポートされていません。
* バケットレベルの暗号化を有効にするオプションはサポートされていません。


* はじめに *

このプレビュー機能を使用するには、BlueXP  コネクタでフラグを有効にする必要があります。その後、バックアップセクションで*サードパーティ互換*オブジェクトストアを選択して、MinIOのサードパーティオブジェクトストアの接続の詳細を保護ワークフローに入力できます。

プレビュー機能を有効にする方法については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-preview-enable.html["BlueXP  バックアップ/リカバリのプレビュー機能を有効にする"]。



== 2025年4月16日

このBlueXP  バックアップ/リカバリリリースには、次の更新が含まれています。



=== UIの改善

このリリースでは、インターフェイスが簡素化され、操作性が向上しています。

* [Volumes]テーブルから[Aggregate]列を削除し、[V2]ダッシュボードの[Volume]テーブルから[Snapshot Policy]列、[Backup Policy]列、および[Replication Policy]列を削除すると、レイアウトがより効率的になります。
* アクティブ化されていない作業環境をドロップダウンリストから除外すると、インターフェイスがすっきりし、ナビゲーションが効率的になり、読み込みが高速になります。
* [タグ]列でのソートが無効になっていても、タグを表示できるため、重要な情報に簡単にアクセスできます。
* 保護アイコンのラベルを削除すると、見た目がきれいになり、ロード時間が短縮されます。
* 作業環境のアクティブ化プロセスでは、検出プロセスが完了するまでダイアログボックスにロードアイコンが表示されてフィードバックが提供されるため、システムの運用の透明性と信頼性が向上します。




=== ボリュームダッシュボードの強化（プレビュー）

ボリュームダッシュボードが10秒未満でロードされるようになり、インターフェイスの速度と効率が大幅に向上しました。このプレビュー版は一部のお客様にご利用いただけ、これらの改善点をいち早くご紹介しています。



=== サードパーティ製Wasabiオブジェクトストアのサポート（プレビュー）

BlueXP  のバックアップとリカバリでは、Wasabiを中心にサードパーティのオブジェクトストアのサポートが拡張されました。この新しいプレビュー機能を使用すると、バックアップとリカバリのニーズに合わせてS3互換オブジェクトストアを活用できます。



==== Wasabiの使用を開始する

サードパーティ製ストレージをオブジェクトストアとして使用するには、BlueXP  Connectorでフラグを有効にする必要があります。その後、サードパーティオブジェクトストアの接続の詳細を入力し、バックアップとリカバリのワークフローに統合できます。

.手順
. コネクタにSSH接続します。
. BlueXP  バックアップとリカバリのCBSサーバコンテナに移動します。
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. Vimまたはその他のエディタを使用して、フォルダ内のファイルを `config`開き `default.json`ます。
+
[listing]
----
vi default.json
----
. 「：false」を「true」に `allow-s3-compatible`変更し `allow-s3-compatible`ます。
. 変更を保存します。
. コンテナを終了します。
. BlueXP  バックアップおよびリカバリCBSサーバコンテナを再起動します。


.結果
コンテナが再びオンになったら、BlueXP  バックアップとリカバリのUIを開きます。バックアップを開始するか、バックアップ戦略を編集すると、新しいプロバイダ「S3 Compatible」が、AWS、Microsoft Azure、Google Cloud、StorageGRID、ONTAP S3の他のバックアッププロバイダとともにリストされます。



==== プレビューモードの制限事項

この機能のプレビュー中は、次の制限事項を考慮してください。

* Bring Your Own Bucket（BYOB）はサポートされていません。
* ポリシーでDataLockを有効にすることはできません。
* ポリシーでアーカイブモードを有効にすることはできません。
* オンプレミスのONTAP環境のみがサポートされます。
* MetroClusterはサポートされていません。
* バケットレベルの暗号化を有効にするオプションはサポートされていません。


このプレビューでは、すべての機能をリリースする前に、この新機能について確認し、サードパーティのオブジェクトストアとの統合に関するフィードバックをお寄せいただくことを推奨します。



== 2025年3月17日

このBlueXP  バックアップ/リカバリリリースには、次の更新が含まれています。



=== SMB Snapshotの参照

このBlueXP  のバックアップとリカバリに関する更新では、SMB環境でローカルSnapshotを参照できないという問題が解決されました。



=== AWS GovCloud環境の更新

このBlueXP  のバックアップとリカバリの更新で、TLS証明書エラーが原因でUIがAWS GovCloud環境に接続できない問題が修正されました。この問題は、IPアドレスではなくBlueXP  Connectorホスト名を使用することで解決されました。



=== バックアップポリシー保持の制限

以前は、BlueXP  のバックアップとリカバリのUIではバックアップコピー数が999個に制限されていましたが、CLIではそれより多くのコピーを実行できました。これで、1つのバックアップポリシーに最大4、000個のボリューム（バックアップポリシーに関連付けられていない1、018個のボリューム）を関連付けることができます。このアップデートには、これらの制限を超えないようにする追加の検証が含まれています。



=== SnapMirrorクラウドの再同期

この更新により、SnapMirror関係の削除後にサポートされていないバージョンのONTAPについては、BlueXP  バックアップおよびリカバリからSnapMirrorクラウドの再同期を開始できなくなります。



== 2025年2月21日

このBlueXP  バックアップ/リカバリリリースには、次の更新が含まれています。



=== 高性能な索引付け

BlueXP  のバックアップとリカバリでは、ソース作業環境上のデータのインデックス作成を効率化する、更新されたインデックス作成機能が導入されています。新しいインデックス作成機能には、UIの更新、データをリストアするSearch & Restore方式のパフォーマンスの向上、グローバル検索機能のアップグレード、拡張性の向上が含まれています。

改善点の内訳は次のとおりです。

* *フォルダ統合*:更新されたバージョンでは、特定の識別子を含む名前を使用してフォルダがグループ化されるため、インデックス作成プロセスがスムーズになります。
* *寄木細工ファイルの圧縮*:更新されたバージョンは、各ボリュームのインデックス作成に使用されるファイルの数を減らし、プロセスを簡素化し、余分なデータベースを必要としません。
* *より多くのセッションでスケールアウト*：新しいバージョンでは、インデックス作成タスクを処理するためのセッションが追加され、プロセスが高速化されます。
* *複数のインデックスコンテナのサポート*：新しいバージョンでは、複数のコンテナを使用してインデックスタスクの管理と分散を強化しています。
* *インデックスの分割ワークフロー*:新しいバージョンでは、インデックス作成プロセスが2つの部分に分割され、効率が向上しています。
* *同時実行性の向上*:新しいバージョンでは、ディレクトリの削除や移動を同時に行うことができるため、インデックス作成プロセスが高速化されます。


.この機能を利用できるのは誰ですか？
新しいインデックス作成機能は、すべての新規顧客が利用できます。

.インデックス作成を有効にするにはどうすればよいですか。
データのリストアにSearch & Restore方式を使用する前に、ボリュームまたはファイルのリストア元となる各ソース作業環境で[Indexing]を有効にする必要があります。これにより、インデックスカタログはすべてのボリュームとすべてのバックアップファイルを追跡できるため、検索が迅速かつ効率的になります。

検索とリストアの実行時に[Enable Indexing]オプションを選択して、ソースの作業環境でインデックス作成を有効にします。

詳細については、のドキュメントを参照して https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["検索と復元を使用してONTAPデータを復元する方法"]ください。

.サポートされるスケール
新しいインデックス作成機能では、次の機能がサポートされています。

* 3分未満でグローバル検索を効率化
* 最大50億個のファイル
* クラスタあたり最大5、000個のボリューム
* ボリュームあたり最大100Kのスナップショット
* ベースラインインデックス作成の最大時間は7日未満です。実際の時間は環境によって異なります。




=== グローバル検索のパフォーマンスの向上

このリリースでは、グローバル検索のパフォーマンスも強化されています。これで、進行状況インジケータと、ファイルの数や検索にかかった時間など、より詳細な検索結果が表示されます。検索とインデックス作成用の専用コンテナにより、グローバル検索が5分以内に完了します。

グローバル検索に関連する次の考慮事項に注意してください。

* 新しいインデックスは、hourlyとラベル付けされたスナップショットでは実行されません。
* 新しいインデックス機能は、FlexVol上のSnapshotに対してのみ機能し、FlexGroup上のSnapshotに対しては機能しません。




== 2024年11月22日

このBlueXP  バックアップ/リカバリリリースには、次の更新が含まれています。



=== SnapLock ComplianceおよびSnapLock Enterprise保護モード

BlueXP  バックアップ/リカバリで、SnapLock ComplianceまたはSnapLock Enterprise保護モードを使用して設定されたオンプレミスのFlexVolボリュームとFlexGroupボリュームの両方をバックアップできるようになりました。このサポートを実行するには、クラスタでONTAP 9.14以降が実行されている必要があります。ONTAPバージョン9.11.1以降では、SnapLock Enterpriseモードを使用したFlexVolボリュームのバックアップがサポートされています。以前のONTAPリリースでは、SnapLock保護ボリュームのバックアップはサポートされません。

でサポートされるボリュームの一覧を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["BlueXPのバックアップとリカバリについて説明します"]。



=== [ボリューム]ページでの検索とリストアプロセスのインデックス作成

検索とリストアを使用する前に、ボリュームデータのリストア元となる各ソース作業環境でインデックスの作成を有効にする必要があります。これにより、インデックス付きカタログで各ボリュームのバックアップファイルを追跡できます。[Volumes]ページにインデックスのステータスが表示されます。

* Indexed：ボリュームにインデックスが作成されました。
* 実行中
* インデックスなし
* インデックスを一時停止しました
* エラー
* 無効




== 2024年9月27日

このBlueXP  バックアップ/リカバリリリースには、次の更新が含まれています。



=== 参照とリストアを使用したRHEL 8または9でのPodmanのサポート

BlueXP  のバックアップとリカバリで、Podmanエンジンを使用したRed Hat Enterprise Linux（RHEL）バージョン8および9でのファイルとフォルダのリストアがサポートされるようになりました。これは、BlueXP  のバックアップとリカバリの参照とリストアの方法に適用されます。

BlueXP  Connectorバージョン3.9.40では、に記載されているオペレーティングシステムに加えて、コネクタソフトウェアをRHEL 8または9ホストに手動でインストールする場合、Red Hat Enterprise Linuxバージョン8および9の特定のバージョンがサポートされ https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["ホストの要件"^]ます。これらの新しいバージョンのRHELでは、DockerエンジンではなくPodmanエンジンが必要です。これまで、BlueXP  のバックアップとリカバリには、Podmanエンジンを使用する場合に2つの制限がありました。これらの制限は削除されました。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["バックアップファイルからのONTAPデータのリストアの詳細"]です。



=== カタログのインデックス作成を高速化し、検索とリストアを向上

このリリースには、ベースラインインデックス作成をはるかに高速に完了する改善されたカタログインデックスが含まれています。インデックス作成を高速化すると、検索とリストア機能をより迅速に使用できるようになります。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["バックアップファイルからのONTAPデータのリストアの詳細"]です。



== 2024年7月22日



=== 1GB未満のボリュームをリストア

このリリースでは、ONTAPで作成した1GB未満のボリュームをリストアできるようになりました。ONTAPを使用して作成できる最小ボリュームサイズは20MBです。



=== DataLockのコストを削減する方法のヒント

DataLock機能は、指定された期間、バックアップファイルが変更または削除されないように保護します。これは、ランサムウェア攻撃からファイルを保護するのに役立ちます。

DataLockの詳細および関連コストを軽減する方法のヒントについては、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["オブジェクトへのバックアップポリシーの設定"]。



=== AWS IAM Roles Anywhere統合

Amazon Web Services（AWS）Identity and Access Management（IAM）Roles Anywhereサービスを使用すると、workloads_on_awsにIAMロールを使用してAWS APIに安全にアクセスできるようになります。これは、workloads_on_awsにIAMロールを使用する場合と同じ方法です。IAM Roles Anywhereの秘密鍵インフラストラクチャとAWSトークンを使用する場合、長期的なAWSアクセスキーとシークレットキーは必要ありません。これにより、クレデンシャルをより頻繁にローテーションすることができ、セキュリティが向上します。

このリリースでは、AWS IAM Roles Anywhereサービスのサポートがテクノロジプレビューになります。

を参照してください https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["BlueXPのバックアップとリカバリ：2024年7月リリースブログ"]。



=== FlexGroupフォルダまたはディレクトリのリストアを利用できるようになりました

以前は、FlexVolボリュームはリストアできましたが、FlexGroupのフォルダやディレクトリはリストアできませんでした。ONTAP 9.15.1 p2では、[参照してリストア]オプションを使用してFlexGroupフォルダをリストアできます。

このリリースでは、FlexGroupフォルダのリストアがテクノロジプレビューとしてサポートされます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-browse-restore["参照と復元を使用したフォルダとファイルの復元"]。

手動で有効にする方法については、を参照してください https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["BlueXPのバックアップとリカバリ：2024年7月リリースブログ"]。



== 2024年5月17日



=== RHEL 8およびRHEL 9をオンプレミスコネクタに使用する場合の制限事項

BlueXP Connectorバージョン3.9.40は、Red Hat Enterprise Linuxバージョン8および9の特定のバージョンをサポートしており、コネクタソフトウェアをRHEL 8または9ホストに手動でインストールする際に、場所に関係なく、 https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["ホストの要件"^]。これらの新しいバージョンのRHELでは、DockerエンジンではなくPodmanエンジンが必要です。現時点では、BlueXPのバックアップとリカバリでPodmanエンジンを使用する場合には2つの制限があります。

を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-limitations.html["バックアップとリストアの制限事項"] を参照してください。

次の手順には、新しいPodmanの手順が含まれています。

* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-restart-backup.html["BlueXPのバックアップとリカバリを再開します"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["ダークサイトでBlueXPのバックアップとリカバリのデータをリストア"]




== 2024年4月30日



=== ランサムウェアの定期的なスキャンを有効または無効にする機能

以前は、ランサムウェアスキャンを有効または無効にすることはできましたが、スケジュールされたスキャンではこれを行うことはできませんでした。

このリリースでは、[Advanced Settings]ページのオプションを使用して、最新のSnapshotコピーに対してスケジュールされたランサムウェアスキャンを有効または無効にできるようになりました。有効にすると、スキャンはデフォルトで毎週実行されます。このスケジュールを数日または数週間に変更したり、無効にしたりすることで、コストを節約できます。

詳細については、次の情報を参照してください。

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["バックアップ設定の管理"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["ONTAPボリュームのポリシーを管理します。"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["オブジェクトへのバックアップポリシーの設定"]




== 2024年4月4日



=== ランサムウェアスキャンを有効または無効にする機能

以前は、バックアップポリシーでランサムウェアの検出を有効にすると、最初のバックアップの作成時とバックアップのリストア時に自動的にスキャンが実行されていました。以前はすべてのSnapshotコピーがスキャンされており、スキャンを無効にすることはできませんでした。

このリリースでは、[Advanced Settings]ページのオプションを使用して、最新のSnapshotコピーに対するランサムウェアスキャンを有効または無効にできるようになりました。有効にすると、スキャンはデフォルトで毎週実行されます。

詳細については、次の情報を参照してください。

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["バックアップ設定の管理"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["ONTAPボリュームのポリシーを管理します。"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["オブジェクトへのバックアップポリシーの設定"]


ifdef::aws[]

および https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Cloud Volumes ONTAP データをAzure Blobにバックアップしています"]を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Amazon S3 への Cloud Volumes ONTAP データのバックアップ"]。

endif::aws[]



== 2024年3月12日



=== クラウドバックアップからオンプレミスのONTAPボリュームへの「迅速なリストア」が可能

クラウドストレージからオンプレミスのONTAPデスティネーションボリュームへのボリュームの_クイックリストア_を実行できるようになりました。以前は、Cloud Volumes ONTAPシステムにのみクイックリストアを実行できました。迅速なリストアは、ボリュームへのアクセスをできるだけ早く提供する必要があるディザスタリカバリ環境に最適です。迅速なリストアは、フルボリュームリストアよりもはるかに高速です。クラウドSnapshotからONTAPデスティネーションボリュームにメタデータをリストアします。ソースは、AWS S3、Azure Blob、Google Cloud Services、NetApp StorageGRIDのいずれかです。

オンプレミスのONTAPデスティネーションシステムでONTAPバージョン9.14.1以降が実行されている必要があります。

これは、検索とリストアのプロセスではなく、参照とリストアのプロセスを使用して実行できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["バックアップファイルからONTAPデータを復元します"]。



=== Snapshotコピーとレプリケーションコピーからファイルとフォルダをリストアする機能

以前は、AWS、Azure、Google Cloud Servicesのバックアップコピーからのみファイルとフォルダをリストアできました。ローカルSnapshotコピーとレプリケーションコピーからファイルとフォルダをリストアできるようになりました。

この機能は、参照とリストアのプロセスではなく、検索とリストアのプロセスを使用して実行できます。



== 2024年2月1日



=== 仮想マシンのBlueXPバックアップとリカバリの機能拡張

* 代替保存場所への仮想マシンのリストアのサポート
* データストアの保護解除のサポート




== 2023年12月15日



=== ローカルSnapshotコピーとレプリケーションSnapshotコピーで使用できるレポート

以前は、バックアップコピーに関するレポートのみを生成できました。ローカルSnapshotコピーとレプリケーションSnapshotコピーに関するレポートも作成できるようになりました。

これらのレポートでは、次の操作を実行できます。

* 重要なデータが組織のポリシーに従って保護されていることを確認します。
* ボリュームグループのバックアップがスムーズに実行されたことを確認します。
* 本番環境のデータに対する保護の証明を提供


を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["データ保護の適用範囲に関するレポートを作成します"]。



=== ボリュームで並べ替えとフィルタリングに使用できるカスタムタグ付け

ONTAP 9.13.1以降では、カスタムタグをボリュームに追加できるようになりました。これにより、複数の作業環境内および複数の作業環境間でボリュームをグループ化できます。これにより、BlueXPのバックアップとリカバリのUIページでボリュームをソートしたり、レポートでフィルタリングしたりできます。



=== 30日間保持されるバックアップをカタログ化

以前は、Catalog.zipのバックアップは7日間保持されていました。現在、それらは30日間保持されます。

を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["ダークサイトでのBlueXPのバックアップとリカバリデータのリストア"]。



== 2023年10月23日



=== バックアップのアクティブ化中の3-2-1バックアップポリシーの作成

これまでは、Snapshot、レプリケーション、またはバックアップを開始する前にカスタムポリシーを作成する必要がありました。BlueXPのバックアップとリカバリのUIを使用して、バックアップのアクティブ化プロセスでポリシーを作成できるようになりました。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["ポリシーの詳細"]。



=== ONTAPボリュームのオンデマンドのクイックリストアのサポート

BlueXPでは、クラウドストレージからCloud Volumes ONTAPシステムへボリュームの「クイックリストア」を実行できるようになりました。迅速なリストアは、ボリュームへのアクセスをできるだけ早く提供する必要があるディザスタリカバリ環境に最適です。クイックリストアでは、バックアップファイル全体をリストアするのではなく、バックアップファイルからボリュームにメタデータをリストアできます。

Cloud Volumes ONTAPデスティネーションシステムでONTAPバージョン9.13.0以降が実行されている必要があります。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["データのリストアに関する詳細情報"]。

BlueXPのバックアップとリカバリのジョブモニタには、クイックリストアジョブの進捗状況も表示されます。



=== ジョブモニタでのスケジュール済みジョブのサポート

BlueXPのバックアップおよびリカバリジョブモニタでは、以前にスケジュールされたボリュームからオブジェクトストアへのバックアップおよびリストアジョブを監視しましたが、UIまたはAPIを使用してスケジュールされたローカルのSnapshot、レプリケーション、バックアップ、およびリストアジョブは監視しません。

BlueXPのバックアップとリカバリのジョブモニタに、ローカルのSnapshot、レプリケーション、オブジェクトストレージへのバックアップに関するスケジュール済みジョブが追加されました。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["更新されたジョブモニタの詳細"]。



== 2023年10月13日



=== BlueXPのアプリケーション向けバックアップとリカバリの機能拡張（クラウドネイティブ）

* Microsoft SQL Serverデータベース
+
** Amazon FSx for NetApp ONTAP上にあるMicrosoft SQL Serverデータベースのバックアップ、リストア、リカバリをサポート
** すべての処理がREST APIでのみサポートされます。


* SAP HANAシステム
+
** システムの更新時に、スクリプトではなくワークフローを使用してボリュームの自動マウントおよびアンマウントが実行されます。
** 追加、削除、編集、削除、保守、 UIヲシヨウシタフラクインホストノアツフクレエト






=== アプリケーション向けのBlueXPのバックアップとリカバリの機能拡張（ハイブリッド）

* データロックとランサムウェア対策をサポート
* StorageGRIDからアーカイブ階層へのバックアップの移動をサポート
* MongoDB、MySQL、PostgreSQLの各アプリケーションデータをオンプレミスのONTAPシステムからAmazon Web Services、Microsoft Azure、Google Cloud Platform、StorageGRIDにバックアップできます。必要に応じてデータをリストアできます。




=== 仮想マシンのBlueXPバックアップとリカバリの機能拡張

* コネクタプロキシ配置モデルのサポート




== 2023年9月11日



=== ONTAPデータの新しいポリシー管理

このリリースには、UI内で、ONTAPデータのオブジェクトストレージへのバックアップ用のカスタムSnapshotポリシー、レプリケーションポリシー、およびポリシーを作成する機能が含まれています。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["ポリシーの詳細"]。



=== ONTAP S3オブジェクトストレージ内のボリュームからのファイルとフォルダのリストアのサポート

これまでは、ボリュームがONTAP S3オブジェクトストレージにバックアップされている場合、[Browse & Restore]機能を使用してファイルやフォルダをリストアすることはできませんでした。このリリースでは、この制限はなくなりました。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["データのリストアに関する詳細情報"]。



=== 最初に標準ストレージに書き込むのではなく、バックアップデータを即座にアーカイブ可能

これで、データを標準のクラウドストレージに書き込む代わりに、バックアップファイルをすぐにアーカイブストレージに送信できます。これは、クラウドバックアップからデータにアクセスする必要がほとんどないユーザや、テープバックアップ環境に取って代わるユーザに特に役立ちます。



=== SnapLockボリュームのバックアップとリストアのサポートの追加

バックアップとリカバリで、SnapLock Enterprise保護モードを使用して設定されたFlexVolボリュームとFlexGroupボリュームの両方をバックアップできるようになりました。このサポートを実行するには、クラスタでONTAP 9.14以降が実行されている必要があります。ONTAPバージョン9.11.1以降では、SnapLock Enterpriseモードを使用したFlexVolボリュームのバックアップがサポートされています。以前のONTAPリリースでは、SnapLock保護ボリュームのバックアップはサポートされません。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["ONTAPデータの保護に関する詳細情報"]。



== 2023年8月1日

[IMPORTANT]
====
* 重要なセキュリティ強化のため、パブリッククラウド環境内のバックアップとリカバリのリソースを管理するために、Connectorに追加のエンドポイントへのアウトバウンドインターネットアクセスが必要になりました。このエンドポイントがファイアウォールの[Allowed]リストに追加されていない場合は、UIに「Service Unavailable」または「Failed to determine service status」というエラーが表示されます。
+
\https://netapp-cloud-account.auth0.com

* Cloud Volumes ONTAPとBlueXPのバックアップとリカバリをバンドルできる「CVO Professional」パッケージを使用する場合、バックアップとリカバリのPAYGOサブスクリプションが必要になりました。これは以前は必要ありませんでした。対象となるCloud Volumes ONTAPシステムのバックアップとリカバリのサブスクリプション料金は発生しませんが、新しいボリュームでバックアップを設定する場合は必要です。


====


=== S3に設定されたONTAPシステムでバケットへのボリュームのバックアップがサポートされるようになりました。

Simple Storage Service（S3）用に設定されたONTAPシステムを使用して、オブジェクトストレージにボリュームをバックアップできるようになりました。これは、オンプレミスのONTAPシステムとCloud Volumes ONTAPシステムの両方でサポートされます。この構成は、クラウド環境およびインターネットアクセスのないオンプレミス環境（「プライベート」モード展開）でサポートされます。

ifdef::aws[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["詳細はこちら。"]。

endif::aws[]



=== 保護対象ボリュームの既存のSnapshotをバックアップファイルに含めることができるようになりました。

これまでは、（最新のSnapshotコピーから始めるのではなく）最初のバックアップファイルに読み書き可能ボリュームの既存のSnapshotコピーを含めることができました。読み取り専用ボリューム（データ保護ボリューム）の既存のSnapshotコピーがバックアップファイルに含まれていませんでした。「DP」ボリュームのバックアップファイルに古いSnapshotコピーを含めるように選択できるようになりました。

バックアップウィザードの最後に、これらの「既存のSnapshot」を選択するためのプロンプトが表示されます。



=== BlueXPのバックアップとリカバリでは、今後追加されるボリュームの自動バックアップはサポートされなくなります。

これまでは、バックアップウィザードのチェックボックスをオンにして、選択したバックアップポリシーをクラスタに追加するすべてのボリュームに適用できました。この機能は、ユーザーからのフィードバックとこの機能の使用不足に基づいて削除されました。クラスタに追加された新しいボリュームのバックアップは、手動で有効にする必要があります。



=== ジョブ監視ページが更新され、新機能が追加されました。

[Job Monitoring]ページに、3-2-1バックアップ戦略に関する詳細情報が表示されるようになりました。また、バックアップ戦略に関連する追加のアラート通知も提供されます。

[Backup lifecycle（バックアップライフサイクル）]タイプフィルタの名前が[Retention（保持）]に変更されました。このフィルタを使用して、バックアップのライフサイクルを追跡し、すべてのバックアップコピーの有効期限を特定します。「保持」ジョブタイプには、BlueXPのバックアップとリカバリで保護されているボリュームで開始されたSnapshot削除ジョブがすべてキャプチャされます。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["更新されたジョブモニタの詳細"]。



== 2023年7月6日



=== BlueXPのバックアップとリカバリに、Snapshotコピーとレプリケートされたボリュームのスケジュール設定と作成が追加されました

BlueXPのバックアップとリカバリでは、3-2-1戦略を実装できるようになりました。この戦略では、ソースデータのコピーを2つのストレージシステムに3つ、クラウドに1つ配置できます。アクティベーションが完了すると、次のような状態になります。

* ソースシステム上のボリュームのSnapshotコピー
* 別のストレージシステムにレプリケートされたボリューム
* オブジェクトストレージ内のボリュームのバックアップ


https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html["新しいフルスペクトルバックアップおよびリストア機能の詳細については、こちらをご覧ください"]。

この新機能は、環境リカバリ処理にも対応しています。リストア処理は、Snapshotコピー、レプリケートされたボリューム、またはクラウド内のバックアップファイルから実行できます。これにより、リカバリのコストや速度など、リカバリ要件を満たすバックアップファイルを柔軟に選択できます。

この新機能とユーザインターフェイスは、ONTAP 9.8以降を実行するクラスタでのみサポートされます。クラスタに以前のバージョンのソフトウェアがインストールされている場合は、以前のバージョンのBlueXPバックアップとリカバリを引き続き使用できます。ただし、最新の機能を利用するには、サポートされているバージョンのONTAPにアップグレードすることを推奨します。古いバージョンのソフトウェアを引き続き使用するには、次の手順に従います。

. [* Volumes （ボリューム） ] タブで、 [* Backup Settings （バックアップ設定） ] を選択します。
. [_Backup Settings]ページで、*[Display the previous BlueXP backup and recovery version]*のラジオボタンをクリックします。
+
その後、以前のバージョンのソフトウェアを使用して古いクラスタを管理できます。





=== オブジェクトストレージにバックアップするためのストレージコンテナを作成できます

オブジェクトストレージにバックアップファイルを作成すると、デフォルトでは、バックアップおよびリカバリサービスによってオブジェクトストレージにバケットが作成されます。特定の名前を使用したり、特殊なプロパティを割り当てたりする場合は、バケットを自分で作成できます。独自のバケットを作成する場合は、アクティブ化ウィザードを開始する前にバケットを作成する必要があります。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["オブジェクトストレージバケットの作成方法について説明します"]。

この機能は、StorageGRIDシステムにバックアップファイルを作成する場合は現在サポートされていません。



== 2023年7月4日



=== BlueXPのアプリケーション向けバックアップとリカバリの機能拡張（クラウドネイティブ）

* SAP HANAシステム
+
** Azure NetApp Filesセカンダリ保護が有効な非データボリュームおよびグローバル非データボリュームの接続とコピーリストアをサポートします


* Oracleデータベース
+
** Azure NetApp Files上のOracleデータベースを別の場所にリストアできます
** Azure NetApp Files上のOracleデータベースのバックアップのOracle Recovery Manager（RMAN）カタログ化をサポートします
** データベースホストをメンテナンスモードにしてメンテナンスタスクを実行できます






=== アプリケーション向けのBlueXPのバックアップとリカバリの機能拡張（ハイブリッド）

* 別の場所へのリストアをサポートします
* Oracleデータベースのバックアップをマウントできます
* GCPからアーカイブ層へのバックアップの移動をサポートします




=== BlueXPの仮想マシンのバックアップとリカバリの機能拡張（ハイブリッド）

* NFSおよびVMFSタイプのデータストアの保護をサポートします
* SnapCenter Plug-in for VMware vSphereホストの登録を解除できます
* 最新のデータストアとバックアップの更新と検出がサポートされます




== 2023年6月5日



=== FlexGroupボリュームは、DataLockとランサムウェア対策を使用してバックアップおよび保護できます

クラスタでONTAP 9.13.1以降が実行されている場合、FlexGroupボリュームのバックアップポリシーでDataLockとランサムウェア対策を使用できるようになりました。



=== 新しいレポート機能

[Reports]タブでバックアップインベントリレポートを生成できるようになりました。このレポートには、特定のアカウント、作業環境、またはSVMインベントリのすべてのバックアップが含まれます。Data Protection Job Activityレポートを作成することもできます。このレポートには、Snapshot、バックアップ、クローニング、およびリストアの各処理に関する情報が表示され、サービスレベルアグリーメントの監視に役立ちます。を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["データ保護の適用範囲に関するレポートを作成します"]。



=== ジョブモニタの機能拡張

[Job Monitor]ページで、_backup lifecycle_をジョブタイプとして確認できるようになりました。これにより、バックアップライフサイクル全体を追跡できます。BlueXPタイムラインでは、すべての処理の詳細を確認することもできます。を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["バックアップジョブとリストアジョブのステータスを監視します"]。



=== 一致しないポリシーラベルに関する追加の通知アラート

新しいバックアップアラート「Backup files were not created because Snapshot policy labels do not match」が追加されました。バックアップポリシーで定義された_label_inにSnapshotポリシーにmatching_label_inがない場合、バックアップファイルは作成されません。欠落しているラベルをボリュームSnapshotポリシーに追加するには、System ManagerまたはONTAP CLIを使用する必要があります。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["BlueXPのバックアップとリカバリから送信されるアラートをすべて確認します"]。



=== ダークサイトのBlueXPの重要なバックアップファイルとリカバリファイルを自動でバックアップ

インターネットアクセスのないサイト（「プライベートモード」環境）でBlueXPのバックアップとリカバリを使用している場合、BlueXPのバックアップとリカバリの情報はローカルコネクタシステムにのみ格納されます。この新機能では、BlueXPの重要なバックアップ/リカバリデータが接続されたStorageGRIDシステムのバケットに自動的にバックアップされるため、必要に応じてこのデータを新しいコネクタにリストアできます。 https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["詳細はこちら。"]



== 2023年5月8日



=== アーカイブストレージとロックされたバックアップでフォルダレベルのリストア処理がサポートされるようになりました

バックアップファイルにDataLockおよびRansomware保護が設定されている場合、またはバックアップファイルがアーカイブストレージにある場合、クラスタでONTAP 9.13.1以降が実行されている場合にフォルダレベルのリストア処理がサポートされるようになりました。



=== ボリュームをGoogle Cloudにバックアップするときは、リージョン間およびプロジェクト間でお客様が管理するキーがサポートされます

顧客管理暗号化キー（CMEK）のプロジェクトとは別のプロジェクトにあるバケットを選択できるようになりました。

ifdef::gcp[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["お客様が管理する独自の暗号化キーの設定の詳細については、こちらをご覧ください"]です。

endif::gcp[]



=== バックアップファイルでAWS Chinaリージョンがサポートされるようになりました

クラスタでONTAP 9.12.1以降が実行されている場合、AWS China Beijing（cn-north-1）リージョンとNingxia（cn-northwest-1）リージョンがバックアップファイルのデスティネーションとしてサポートされるようになりました。

BlueXPコネクタに割り当てるIAMポリシーでは、all_Resource_sectionsの下にあるAWSリソース名「arn」を「aws」から「aws-cn」に変更する必要があります（例：「arn：aws-cn：s3：：：netapp-backup-*」）。

ifdef::aws[]

詳細については、およびを参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Cloud Volumes ONTAP データを Amazon S3 にバックアップします"] https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html["オンプレミスのONTAPデータをAmazon S3にバックアップ"] 。

endif::aws[]



=== ジョブモニタの機能拡張

ONTAP 9.13.1以降を実行しているオンプレミスのONTAP システムで、システム開始ジョブ（進行中のバックアップ処理など）を*[ジョブ監視]*タブで確認できるようになりました。以前のバージョンのONTAP では、ユーザが開始したジョブのみが表示されます。



== 2023年4月14日



=== BlueXPのアプリケーション向けバックアップとリカバリの機能拡張（クラウドネイティブ）

* SAP HANAデータベース
+
** スクリプトベースのシステム更新をサポートします
** Azure NetApp Files バックアップが設定されている場合は、Single-File-Snapshot-Restoreがサポートされます
** プラグインのアップグレードをサポートします


* Oracleデータベース
+
** root以外のsudoユーザ設定が簡易化され、プラグインの導入が強化されました
** プラグインのアップグレードをサポートします
** Azure NetApp Files 上のOracleデータベースの自動検出とポリシーベースの保護をサポートします
** きめ細かなリカバリにより、Oracleデータベースを元の場所にリストアできます






=== アプリケーション向けのBlueXPのバックアップとリカバリの機能拡張（ハイブリッド）

* アプリケーション（ハイブリッド）向けのBlueXPのバックアップとリカバリは、SaaSコントロールプレーンから実行されます
* ハイブリッドREST APIが変更され、クラウドネイティブAPIと連携するようになりました。
* Eメール通知をサポートします




== 2023年4月4日



=== 「制限付き」モードでCloud Volumes ONTAP システムからクラウドにデータをバックアップする機能

これで、AWS、Azure、GCPの商用リージョンにインストールされているCloud Volumes ONTAP システムのデータを「制限モード」でバックアップできるようになりました。これを行うには、まず「制限された」商業地域にコネクタをインストールする必要があります。 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXPの導入モードの詳細については、こちらをご覧ください"^]です。

ifdef::aws[]

を参照し https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Amazon S3 への Cloud Volumes ONTAP データのバックアップ"]

endif::aws[]

ifdef::azure[]

を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Cloud Volumes ONTAP データをAzure Blobにバックアップしています"]

endif::azure[]



=== APIを使用して、オンプレミスのONTAP ボリュームをONTAP S3にバックアップする機能

APIの新機能を使用して、BlueXPのバックアップとリカバリを使用してボリュームSnapshotをONTAP S3にバックアップできます。この機能は、現時点ではオンプレミスのONTAP システムでのみ使用できます。詳細な手順については、ブログを参照してください https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-April-23-Updates/ba-p/443075#toc-hId--846533830["デスティネーションとしてのONTAP S3との統合"^]。



=== Azureストレージアカウントのゾーン冗長性の側面をLRSからZRSに変更する機能

Cloud Volumes ONTAP システムからAzureストレージへのバックアップを作成する場合、BlueXPのバックアップとリカバリでは、コスト最適化のためにローカル冗長性（LRS）を使用してBlobコンテナがデフォルトでプロビジョニングされます。異なるゾーン間でデータを複製する場合は、この設定をZone redundancy（ZRS）に変更できます。Microsoftの手順を参照してください https://learn.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal["ストレージアカウントの複製方法の変更"^]。



=== ジョブモニタの機能拡張

* ONTAP 9.13.0以降を実行しているCloud Volumes ONTAP システムでは、BlueXPのバックアップ/リカバリのUIとAPIでユーザが開始したバックアップ処理とリストア処理と、システムが開始したジョブ（進行中のバックアップ処理など）が[ジョブ監視]タブで利用できるようになりました。以前のバージョンのONTAP では、ユーザが開始したジョブのみが表示されます。
* すべてのジョブをレポートするためのCSVファイルをダウンロードできるほか、単一のジョブのJSONファイルをダウンロードして詳細を確認できるようになりました。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["詳細はこちら。"]。
* 「Scheduled job failure」と「Restore job completes but with warnings」という2つの新しいバックアップジョブアラートが追加されました。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["BlueXPのバックアップとリカバリから送信されるアラートをすべて確認します"]。




== 2023年3月9日



=== フォルダレベルのリストア処理に、すべてのサブフォルダとファイルが含まれるようになりました

以前は、フォルダをリストアしたときに、そのフォルダのファイルのみがリストアされました。サブフォルダやサブフォルダ内のファイルはリストアされませんでした。ONTAP 9.13.0以降を使用している場合は、選択したフォルダ内のすべてのサブフォルダとファイルが復元されます。これにより、トップレベルフォルダに複数のフォルダがネストされている場合に、時間とコストを大幅に節約できます。



=== アウトバウンド接続が制限されているサイトのCloud Volumes ONTAPシステムからデータをバックアップする機能

AWSおよびAzureの商用リージョンにインストールされているCloud Volumes ONTAP システムから、Amazon S3またはAzure Blobにデータをバックアップできるようになりました。これには、商用地域のLinuxホストに「制限モード」でコネクタをインストールし、そこにCloud Volumes ONTAPシステムを展開する必要があります。

ifdef::aws[]

を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Amazon S3 への Cloud Volumes ONTAP データのバックアップ"]

endif::aws[]

ifdef::azure[]

を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Cloud Volumes ONTAP データをAzure Blobにバックアップしています"]

endif::azure[]



=== ジョブモニタに複数の機能拡張が追加されました

* [Job Monitoring]ページには高度なフィルタ機能が追加され、バックアップジョブとリストアジョブを時間、ワークロード（ボリューム、アプリケーション、または仮想マシン）、ジョブタイプ、 ステータス、作業環境、Storage VM。任意のリソース（「application_3」など）を検索するフリーテキストを入力することもできます。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#searching-and-filtering-the-list-of-jobs["詳細フィルタの使用方法を参照してください"]です。
* ONTAP 9.13.0以降を実行しているCloud Volumes ONTAP システムでは、BlueXPのバックアップ/リカバリのUIとAPIでユーザが開始したバックアップ処理とリストア処理と、システムが開始したジョブ（進行中のバックアップ処理など）が[ジョブ監視]タブで利用できるようになりました。以前のバージョンのCloud Volumes ONTAP システムおよびオンプレミスのONTAP システムでは、現時点ではユーザが開始したジョブのみが表示されます。




== 2023年2月6日



=== 古いバックアップファイルをStorageGRID システムからAzureアーカイブストレージに移動する機能

これで、古いバックアップファイルをStorageGRID システムからAzureのアーカイブストレージに階層化できるようになりました。これにより、StorageGRID システムのスペースを解放し、古いバックアップファイルには低コストのストレージクラスを使用することでコストを削減できます。

この機能は、オンプレミスクラスタがONTAP 9.12.1以降を使用し、StorageGRID システムが11.4以降を使用している場合に使用できます。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["詳細はこちらをご覧ください"^]。



=== DataLockとRansomwareによる保護は、Azure Blobでのバックアップファイルに対して設定できます

DataLockとRansomware Protectionは、Azure Blobに保存されたバックアップファイルでサポートされるようになりました。Cloud Volumes ONTAP またはオンプレミスONTAP システムでONTAP 9.12.1以降を実行している場合、バックアップファイルをロックしてスキャンし、ランサムウェアの可能性を検出できるようになりました。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["DataLockとランサムウェア防御を使用してバックアップを保護する方法については、こちらをご覧ください"^]。



=== FlexGroup ボリュームのバックアップとリストアの機能拡張

* FlexGroup ボリュームのリストア時に複数のアグリゲートを選択できるようになりました。前回のリリースでは、アグリゲートを1つしか選択できませんでした。
* FlexGroup ボリュームリストアがCloud Volumes ONTAP システムでサポートされるようになりました。前回のリリースでは、オンプレミスのONTAP システムにのみリストアできました。




=== Cloud Volumes ONTAP システムでは、古いバックアップをGoogleアーカイブストレージに移動できます

バックアップファイルは、最初にGoogle Standardストレージクラスで作成されます。BlueXPのバックアップとリカバリ機能を使用して、古いバックアップをGoogleアーカイブストレージに階層化し、コストをさらに最適化できるようになりました。前回のリリースでは、オンプレミスのONTAP クラスタでのみこの機能がサポートされていました。現在Google Cloudに導入されているCloud Volumes ONTAP システムがサポートされています。



=== ボリュームリストア処理で、ボリュームデータをリストアするSVMを選択できるようになりました

次に、ONTAP クラスタ内の別のStorage VMにボリュームデータをリストアします。これまでは、Storage VMを選択できませんでした。



=== MetroCluster 構成でのボリュームのサポートが強化されました

ONTAP 9.12.1 GA以降を使用している場合、MetroCluster 構成でプライマリシステムに接続しているときにバックアップがサポートされるようになりました。バックアップ構成全体がセカンダリシステムに転送されるため、スイッチオーバー後もクラウドへのバックアップが自動的に続行されます。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#backup-limitations["詳細については、「バックアップの制限」を参照してください"]。



== 2023年1月9日



=== StorageGRID システムからAWS S3アーカイブストレージに古いバックアップファイルを移動する機能

これにより、StorageGRID システムの古いバックアップファイルをAWS S3のアーカイブストレージに階層化できるようになりました。これにより、StorageGRID システムのスペースを解放し、古いバックアップファイルには低コストのストレージクラスを使用することでコストを削減できます。AWS S3 GlacierまたはS3 Glacier Deep Archiveストレージにバックアップを階層化することもできます。

この機能は、オンプレミスクラスタでONTAP 9.12.1以降を使用し、StorageGRID システムで11.3以上を使用している場合に使用できます。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["詳細はこちらをご覧ください"]。



=== Google Cloudのデータ暗号化に、お客様が管理する独自のキーを選択できます

ONTAP システムからGoogle Cloud Storageにデータをバックアップする際に、Googleが管理するデフォルトの暗号化キーを使用する代わりに、アクティベーションウィザードで、お客様が管理する独自のキーを選択してデータを暗号化できるようになりました。まずGoogleでお客様が管理する暗号化キーを設定し、BlueXPのバックアップとリカバリをアクティブ化する際に詳細を入力するだけです。



=== 「ストレージ管理者」ロールは、サービスアカウントがGoogle Cloud Storageでバックアップを作成するために必要なくなりました

以前のリリースでは、BlueXPのバックアップとリカバリでGoogle Cloud Storageバケットにアクセスするためのサービスアカウントに「Storage Admin」ロールが必要でした。これで、一連の権限を減らしてサービスアカウントに割り当てるカスタムロールを作成できるようになりました。

ifdef::gcp[]

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["Google Cloud Storageでバックアップを準備する方法をご覧ください"]です。

endif::gcp[]



=== インターネットにアクセスできないサイトで検索とリストアを使用してデータをリストアする機能がサポートされるようになりました

インターネットアクセスのないサイト（ダークサイトまたはオフラインサイトとも呼ばれます）のオンプレミスのONTAP クラスタからStorageGRID にデータをバックアップする場合は、必要に応じて検索とリストアのオプションを使用してデータをリストアできるようになりました。この機能を使用するには、BlueXPコネクタ(バージョン3.9.25以上)がオフラインサイトに配置されている必要があります。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["検索と復元を使用してONTAPデータを復元する方法"]。
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["コネクターをオフラインサイトにインストールする方法を参照してください"]。



=== ジョブ監視結果ページを.csvレポートとしてダウンロードできるようになりました

[ジョブ監視]ページをフィルタリングして、必要なジョブとアクションを表示したら、そのデータの.csvファイルを生成してダウンロードできるようになりました。次に、情報を分析したり、組織内の他のユーザーにレポートを送信したりできます。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["「ジョブ監視レポートを生成する方法」を参照してください"]。



== 2022年12月19日



=== Cloud Backup for Applicationsの機能強化

* SAP HANAデータベース
+
** Azure NetApp Files 上にあるSAP HANAデータベースのポリシーベースのバックアップとリストアをサポートします
** カスタムポリシーをサポート


* Oracleデータベース
+
** ホストを追加してプラグインを自動的に導入
** カスタムポリシーをサポート
** Cloud Volumes ONTAP 上にあるOracleデータベースのポリシーベースのバックアップ、リストア、およびクローニングをサポートします
** Amazon FSX for NetApp ONTAP 上に存在するOracleデータベースのポリシーベースのバックアップおよびリストアをサポートします
** Connect and Copy方式を使用したOracleデータベースのリストアをサポートします
** Oracle 21cをサポートします
** クラウドネイティブのOracleデータベースのクローニングをサポート






=== Cloud Backup for Virtual Machinesの機能拡張

* 仮想マシン
+
** オンプレミスのセカンダリストレージから仮想マシンをバックアップ
** カスタムポリシーをサポート
** では、Google Cloud Platform（GCP）をサポートしており、1つ以上のデータストアのバックアップに使用できます
** Glacier、Deep Glacier、Azure Archiveなどの低コストのクラウドストレージをサポートします






== 2022年12月6日



=== 必須コネクターアウトバウンドインターネットアクセスエンドポイントの変更

Cloud Backupの処理が変更されたため、クラウドバックアップの処理を成功させるには、次のコネクタエンドポイントを変更する必要があります。

[cols="50,50"]
|===
| 古いエンドポイント | 新しいエンドポイント 


| \ https://cloudmanager.cloud.netapp.com | \ https://api.bluexp.netapp.com 


| \ https://*.cloudmanager.cloud.netapp.com | \ https://*.api.bluexp.netapp.com 
|===
のすべてのエンドポイントのリストを参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^]、 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^]または https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure"^] クラウド環境：



=== UIでのGoogleアーカイブストレージクラスの選択がサポートされます

バックアップファイルは、最初にGoogle Standardストレージクラスで作成されます。Cloud Backup UIを使用して、特定の日数が経過した古いバックアップをGoogle Archiveストレージに階層化し、コストをさらに最適化できるようになりました。

この機能は、現在、ONTAP 9.12.1以降を使用するオンプレミスONTAP クラスタでサポートされています。現在、Cloud Volumes ONTAP システムでは使用できません。



=== FlexGroup ボリュームのサポート

Cloud BackupでFlexGroup ボリュームのバックアップとリストアがサポートされるようになりました。ONTAP 9.12.1以降を使用している場合は、FlexGroup ボリュームをパブリッククラウドストレージとプライベートクラウドストレージにバックアップできます。FlexVol ボリュームとFlexGroup ボリュームが含まれる作業環境がある場合、ONTAP ソフトウェアを更新すると、それらのシステム上の任意のFlexGroup をバックアップできます。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#supported-volumes["サポートされるボリュームタイプの一覧を参照してください"]。



=== バックアップのデータをCloud Volumes ONTAP システムの特定のアグリゲートにリストアする機能

以前のリリースでは、データをオンプレミスのONTAP システムにリストアする場合にのみアグリゲートを選択できました。この機能は、Cloud Volumes ONTAP システムにデータをリストアする場合に使用できるようになりました。



== 2022年11月2日



=== 古いSnapshotコピーをベースラインバックアップファイルにエクスポートできるようになりました

バックアップスケジュールのラベル（日単位、週単位など）に一致するボリュームのローカルSnapshotコピーが作業環境にある場合は、それらの履歴Snapshotをバックアップファイルとしてオブジェクトストレージにエクスポートできます。これにより、古いSnapshotコピーをベースラインバックアップコピーに移動することで、クラウドでバックアップを初期化できます。

このオプションは、作業環境でCloud Backupをアクティブ化する場合に使用できます。この設定は、あとでで変更することもできます https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["[詳細設定]ページ"]。



=== これで、ソースシステムで不要になったボリュームのアーカイブにCloud Backupを使用できるようになります

これで、ボリュームのバックアップ関係を削除できるようになります。これにより、新しいバックアップファイルの作成を停止してソースボリュームを削除し、既存のすべてのバックアップファイルを保持する場合に、アーカイブメカニズムを実現できます。これにより、必要に応じて、あとでソースストレージシステムからスペースを消去しながら、バックアップファイルからボリュームをリストアできるようになります。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-ontap.html#deleting-volume-backup-relationships["詳細をご確認ください"]。



=== Cloud BackupのアラートをEメールおよび通知センターで受信するためのサポートが追加されました

Cloud Backupは、BlueXP Notificationサービスに統合されています。Cloud Backup通知を表示するには、BlueXPメニューバーの通知ベルをクリックします。また、システムにログインしていないときでも重要なシステムアクティビティを通知できるように、メールで通知を送信するようにBlueXPを構成することもできます。このEメールは、バックアップとリストアのアクティビティに注意する必要があるすべての受信者に送信できます。 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status["詳細をご確認ください"]。



=== 新しいAdvanced Settingsページでは、クラスタレベルのバックアップ設定を変更できます

この新しいページでは、ONTAP システムごとにクラウドバックアップをアクティブ化するときに設定したクラスタレベルのバックアップ設定の多くを変更できます。「デフォルト」バックアップ設定として適用される一部の設定を変更することもできます。変更可能なバックアップ設定の完全なセットは、次のとおりです。

* ONTAP システムにオブジェクトストレージへのアクセス権を付与するストレージキー
* バックアップをオブジェクトストレージにアップロードするために割り当てられるネットワーク帯域幅
* 以降のボリュームの自動バックアップ設定（およびポリシー）
* アーカイブストレージクラス（AWSのみ）
* Snapshotコピーの履歴が最初のベースラインバックアップファイルに含まれているかどうか
* ソースシステムから「年次」スナップショットを削除するかどうか
* オブジェクトストレージに接続されているONTAP IPspace（アクティブ化時に誤って選択された場合）


https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["クラスタレベルのバックアップ設定の管理に関する詳細情報"]。



=== オンプレミスコネクタを使用している場合に、検索とリストアを使用してバックアップファイルをリストアできるようになりました

以前のリリースでは、Connectorをオンプレミスに導入すると、バックアップファイルをパブリッククラウドに作成するためのサポートが追加されていました。このリリースでは、Connectorがオンプレミスに導入されている場合、Search & Restoreを使用してAmazon S3またはAzure Blobからバックアップをリストアできるようになりました。検索とリストアでは、StorageGRID システムからオンプレミスのONTAP システムへのバックアップのリストアもサポートされています。

現時点では、Google Cloud Storageからバックアップをリストアするために検索とリストアを使用する場合、ConnectorをGoogle Cloud Platformに導入する必要があります。



=== ジョブ監視ページが更新されました

には、次の更新が行われています https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["ジョブ監視ページ"]：

* [ワークロード]の列では、ページをフィルタして、ボリューム、アプリケーション、および仮想マシンのバックアップサービスのジョブを表示できます。
* 特定のバックアップジョブの詳細を表示するには、「ユーザ名」と「ジョブタイプ」の列を新たに追加します。
* [ジョブの詳細]ページには、メインジョブを完了するために実行中のすべてのサブジョブが表示されます。
* このページは15分ごとに自動的に更新されるため、常に最新のジョブステータスの結果が表示されます。また、[*更新*]ボタンをクリックすると、ページをすぐに更新できます。




=== AWSのクロスアカウントバックアップの機能拡張

Cloud Volumes ONTAP バックアップにソースボリュームに使用しているものとは異なるAWSアカウントを使用する場合は、デスティネーションのAWSアカウントクレデンシャルをBlueXPに追加し、「s3：PutBucketPolicy」および「s3：PutBucketOwnershipControls」権限をBlueXPに権限を提供するIAMロールに追加する必要があります。これまでは、AWSコンソールで多数の設定を行う必要がありましたが、これはもう必要ありません。



== 2022年9月28日



=== Cloud Backup for Applicationsの機能強化

* Google Cloud Platform（GCP）とStorageGRID をサポートし、アプリケーションと整合性のあるスナップショットをバックアップします
* カスタムポリシーを作成する
* アーカイブストレージをサポートします
* SAP HANAアプリケーションをバックアップ
* VMware環境のOracleおよびSQLアプリケーションをバックアップする
* オンプレミスのセカンダリストレージからアプリケーションをバックアップ
* バックアップの非アクティブ化
* SnapCenter サーバを登録解除します




=== Cloud Backup for Virtual Machinesの機能拡張

* では、StorageGRID を使用して1つ以上のデータストアをバックアップできます
* カスタムポリシーを作成する




== 2022年9月19日



=== DataLockとRansomwareによる保護は、StorageGRID システムのバックアップファイルに対して設定できます

最後のリリースで導入された、Amazon S3バケットに格納されたバックアップ向けの_DataLockとRansomware Protection_forが含まれます。このリリースでは、StorageGRID システムに格納されたバックアップファイルのサポートが拡張されています。クラスタがONTAP 9.11.1以降を使用していて、StorageGRID システムがバージョン11.6.0.3以降を実行している場合、この新しいバックアップポリシーオプションを使用できます。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["DataLockとRansomwareによる保護でバックアップを保護する方法の詳細をご確認ください"^]。

バージョン3.9.22以降のソフトウェアがインストールされたコネクタを実行する必要があります。コネクタはオンプレミスにインストールする必要があり、インターネットにアクセスできるサイトまたはインターネットに接続できないサイトにインストールできます。



=== これで、バックアップファイルからフォルダレベルのリストアを実行できるようになりました

フォルダ（ディレクトリまたは共有）内のすべてのファイルにアクセスする必要がある場合は、バックアップファイルからフォルダをリストアできるようになりました。フォルダをリストアする方が、ボリューム全体をリストアするよりもはるかに効率的です。この機能は、ONTAP 9.11.1以降を使用している場合、Browse & RestoreメソッドとSearch & Restoreメソッドの両方を使用してリストア処理を実行するときに使用できます。この時点では、1つのフォルダのみを選択してリストアできます。そのフォルダのファイルのみがリストアされます。サブフォルダやサブフォルダ内のファイルはリストアされません。



=== アーカイブストレージに移動されたバックアップからファイルレベルのリストアを実行できるようになりました

以前は、アーカイブストレージに移動されたバックアップファイルからのみボリュームをリストアできました（AWSおよびAzureのみ）。これらのアーカイブ済みバックアップファイルから個 々 のファイルをリストアできるようになりました。この機能は、ONTAP 9.11.1以降を使用している場合、Browse & RestoreメソッドとSearch & Restoreメソッドの両方を使用してリストア処理を実行するときに使用できます。



=== ファイルレベルのリストアで、元のソースファイルを上書きするオプションが追加されました

以前は、元のボリュームにリストアされたファイルは、「Restore_< file_name >」というプレフィックスの新しいファイルとして常にリストアされていました。ボリューム上の元の場所にファイルをリストアする際に、元のソースファイルを上書きできるようになりました。この機能は、参照およびリストア方法と検索およびリストア方法の両方を使用して、リストア処理を実行する場合に使用できます。



=== ドラッグアンドドロップして、StorageGRID システムへのクラウドバックアップを有効にします

状況に応じて https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRID"^] バックアップ先がキャンバス上の作業環境として存在する場合、オンプレミスのONTAP 作業環境をデスティネーションにドラッグしてクラウドバックアップセットアップウィザードを開始できます。
