---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore' 
summary: Cloud Backup の新機能をご確認ください。 
---
= Cloud Backup の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Backup の新機能をご確認ください。



== 2022年9月30日



=== Cloud Backup for Applicationsの機能強化

* Google Cloud Provider（GCP）とStorageGRID をサポートしており、アプリケーションと整合性のあるSnapshotをバックアップできます
* カスタムポリシーを作成する
* アーカイブストレージをサポートします
* SAP HANAアプリケーションをバックアップ
* VMware環境のOracleおよびSQLアプリケーションをバックアップする
* オンプレミスのセカンダリストレージからアプリケーションをバックアップ
* バックアップの非アクティブ化
* SnapCenter サーバを登録解除します




=== Cloud Backup for Virtual Machinesの機能拡張

* では、StorageGRID を使用して1つ以上のデータストアをバックアップできます
* カスタムポリシーを作成する




== 2022年9月19日



=== DataLockとRansomwareによる保護は、StorageGRID システムのバックアップファイルに対して設定できます

最後のリリースで導入された、Amazon S3バケットに格納されたバックアップ向けの_DataLockとRansomware Protection_forが含まれます。このリリースでは、StorageGRID システムに格納されたバックアップファイルのサポートが拡張されています。クラスタがONTAP 9.11.1以降を使用していて、StorageGRID システムがバージョン11.6.0.3以降を実行している場合、この新しいバックアップポリシーオプションを使用できます。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["DataLockとRansomwareによる保護でバックアップを保護する方法の詳細をご確認ください"^]。

バージョン3.9.22以降のソフトウェアがインストールされたコネクタを実行する必要があります。コネクタはオンプレミスにインストールする必要があり、インターネットにアクセスできるサイトまたはインターネットに接続できないサイトにインストールできます。



=== これで、バックアップファイルからフォルダレベルのリストアを実行できるようになりました

フォルダ（ディレクトリまたは共有）内のすべてのファイルにアクセスする必要がある場合は、バックアップファイルからフォルダをリストアできるようになりました。フォルダをリストアする方が、ボリューム全体をリストアするよりもはるかに効率的です。この機能は、ONTAP 9.11.1以降を使用している場合、Browse & RestoreメソッドとSearch & Restoreメソッドの両方を使用してリストア処理を実行するときに使用できます。この時点では、1つのフォルダのみを選択してリストアできます。そのフォルダのファイルのみがリストアされます。サブフォルダやサブフォルダ内のファイルはリストアされません。



=== アーカイブストレージに移動されたバックアップからファイルレベルのリストアを実行できるようになりました

以前は、アーカイブストレージに移動されたバックアップファイルからのみボリュームをリストアできました（AWSおよびAzureのみ）。これらのアーカイブ済みバックアップファイルから個 々 のファイルをリストアできるようになりました。この機能は、ONTAP 9.11.1以降を使用している場合、Browse & RestoreメソッドとSearch & Restoreメソッドの両方を使用してリストア処理を実行するときに使用できます。



=== ファイルレベルのリストアで、元のソースファイルを上書きするオプションが追加されました

以前は、元のボリュームにリストアされたファイルは、「Restore_< file_name >」というプレフィックスの新しいファイルとして常にリストアされていました。ボリューム上の元の場所にファイルをリストアする際に、元のソースファイルを上書きできるようになりました。この機能は、参照およびリストア方法と検索およびリストア方法の両方を使用して、リストア処理を実行する場合に使用できます。



=== ドラッグアンドドロップして、StorageGRID システムへのクラウドバックアップを有効にします

状況に応じて https://docs.netapp.com/us-en/cloud-manager-storagegrid/task-discover-storagegrid.html["StorageGRID"^] バックアップ先がキャンバス上の作業環境として存在する場合、オンプレミスのONTAP 作業環境をデスティネーションにドラッグしてクラウドバックアップセットアップウィザードを開始できます。



== 2022年8月18日



=== クラウドネイティブアプリケーションデータを保護するためのサポートが追加されました

Cloud Backup for Applicationsは、NetApp Cloud Storageで実行されているアプリケーションにデータ保護機能を提供するSaaSベースのサービスです。Cloud Managerで有効になっているアプリケーション向けのCloud Backupは、Amazon FSX for NetApp ONTAP 上に存在するOracleデータベースを、アプリケーションと整合性のある効率的なポリシーベースのバックアップおよびリストアを実現します。https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-cloud-app-data-to-cloud.html["詳細はこちら。"^]。



=== 検索とリストアがAzure Blobでのバックアップファイルでサポートされるようになりました

Azure BLOBストレージにバックアップファイルを保存するユーザが、ボリュームとファイルのリストア方法を検索してリストアできるようになりました。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#prerequisites-2["Search  Restoreを使用してボリュームとファイルをリストアする方法を参照してください"^]。

この機能を使用するには、Connectorロールで追加の権限が必要です。バージョン3.9.21ソフトウェア（2022年8月）を使用して導入されたコネクタに、次の権限が含まれます。以前のリリースを使用してコネクタを導入した場合は、権限を手動で追加する必要があります。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-azure.html#verify-or-add-permissions-to-the-connector["必要に応じて、これらの権限を追加する方法を参照してください"^]。



=== バックアップファイルを削除攻撃やランサムウェア攻撃から保護する機能が追加されました

Cloud Backupでランサムウェアセーフバックアップのオブジェクトロックがサポートされるようになりました。クラスタがONTAP 9.11.1以降を使用していて、バックアップのデスティネーションがAmazon S3の場合、_DataLockという新しいバックアップポリシーオプションとランサムウェア防御_が利用可能になりました。DataLockはバックアップファイルの変更や削除を防止します。ランサムウェア対策はバックアップファイルをスキャンして、ランサムウェアによるバックアップファイルへの攻撃の証拠を探します。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["DataLockとRansomwareによる保護でバックアップを保護する方法の詳細をご確認ください"^]。

この機能を使用するには、Connectorロールで追加の権限が必要です。バージョン3.9.21ソフトウェアを使用して展開されたコネクタには、これらの権限が含まれています。以前のリリースを使用してコネクタを導入した場合は、権限を手動で追加する必要があります。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-to-aws.html#set-up-s3-permissions["必要に応じて、これらの権限を追加する方法を参照してください"^]。



=== Cloud Backupで、カスタムSnapMirrorラベルを使用して作成したポリシーがサポートされるようになりまし

以前は、Cloud Backupであらかじめ定義されているSnapMirrorラベル（hourly、daily、weekly、hourly、yearlyなど）のみがサポートされていました。これで、System ManagerまたはCLIを使用して作成したカスタムのSnapMirrorラベルを含むSnapMirrorポリシーがCloud Backupで検出されるようになります。これらの新しいラベルはCloud BackupのUIで公開されており、SnapMirrorラベルを使用してボリュームをクラウドにバックアップできます。



=== ONTAP システムのバックアップポリシーも強化されました

一部のバックアップポリシーのページが再設計され、各ONTAP クラスタのボリュームに使用できるすべてのバックアップポリシーが表示されるようになりました。これにより、使用可能なポリシーの詳細を簡単に確認できるため、ボリュームに最適なポリシーを適用できます。



=== ドラッグアンドドロップして、Azure BlobやGoogle Cloud StorageへのCloud Backupを有効にします

状況に応じて https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-viewing-azure-blob.html["Azure Blob の略"^] または https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-viewing-gcp-storage.html["Google クラウドストレージ"^] バックアップ先はキャンバス上の作業環境として存在し、オンプレミスのONTAP またはCloud Volumes ONTAP 作業環境（AzureまたはGCPにインストール）を移行先にドラッグしてバックアップセットアップウィザードを開始できます。

この機能はAmazon S3バケットに対してはすでに存在します。



== 2022年7月13日



=== SnapLock Enterpriseボリュームのバックアップがサポートされるようになりました

Cloud Backupを使用して、SnapLock Enterpriseボリュームをパブリッククラウドとプライベートクラウドにバックアップできるようになりました。この機能を使用するには、ONTAP システムでONTAP 9.11.1以降が実行されている必要があります。ただし、SnapLock Complianceボリュームは現在サポートされていません。



=== オンプレミスコネクタを使用して、パブリッククラウドにバックアップファイルを作成できるようになりました

以前は、バックアップファイルの作成場所と同じクラウドプロバイダにConnectorを導入する必要がありました。オンプレミスに導入されたコネクタを使用して、オンプレミスのONTAP システムからAmazon S3、Azure Blob、Google Cloud Storageへのバックアップファイルを作成できるようになりました。（StorageGRID システムでバックアップファイルを作成する場合は、オンプレミスコネクタが常に必要でした）。



=== ONTAP システムのバックアップポリシーを作成する場合には、追加の機能を使用できます

* 毎年のスケジュールでバックアップを実行できるようになりました。年単位のバックアップの場合、デフォルトの保持期間は1ですが、この値を変更して、以前の多数のバックアップファイルにアクセスできるようにすることができます。
* バックアップポリシーに名前を付けておくと、よりわかりやすいテキストでポリシーを識別できます。




== 2022年6月14日



=== インターネットにアクセスできないサイトのオンプレミスONTAP クラスタデータをバックアップするサポートが追加されました

オンプレミスのONTAP クラスタが、インターネットにアクセスできないサイト（ダークサイトまたはオフラインサイトとも呼ばれます）にある場合は、Cloud Backupを使用して、同じサイトにあるNetApp StorageGRID システムにボリュームデータをバックアップできるようになりました。この機能を使用するには、Cloud Manager Connector（バージョン3.9.19以降）もオフラインサイトに導入する必要があります。

https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html["コネクターをオフラインサイトにインストールする方法を参照してください"]。https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-onprem-private-cloud.html["オフラインサイトのStorageGRID にONTAP データをバックアップする方法を参照してください"]。



=== Cloud Backup for Virtual Machines 1.1.0のGA版になりました

SnapCenter Plug-in for VMware vSphereとCloud Managerを統合することで、仮想マシン上のデータを保護できます。データストアをクラウドにバックアップし、仮想マシンをオンプレミスのSnapCenter Plug-in for VMware vSphereにリストアする作業は簡単です。

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-vm-data.html["仮想マシンをクラウドに保護する方法については、こちらをご覧ください"]。



=== クラウドのリストアインスタンスは、ONTAP の参照とリストア機能では必要ありません

S3およびBLOBストレージからのファイルレベルの参照およびリストア処理に必要な、別のCloud Restoreインスタンス/仮想マシン。このインスタンスは使用していないときにシャットダウンされますが、ファイルのリストアに時間とコストがかかります。この機能は、必要に応じてコネクタに導入される無償のコンテナに置き換えられました。これには、次の利点があります。

* ファイルレベルのリストア処理のための追加コストは不要です
* ファイルレベルのリストア処理が高速化されます
* Connectorがオンプレミスにインストールされている場合のクラウドからのファイルの参照とリストアの処理がサポートされます


以前に使用していた場合は、Cloud Restoreインスタンス/VMが自動的に削除されることに注意してください。Cloud Backupプロセスが1日に1回実行され、古いCloud Restoreインスタンスがすべて削除されます。この変更は完全に透過的に行われます。データへの影響はなく、バックアップジョブやリストアジョブの変更は通知されません。



=== Google CloudおよびStorageGRID ストレージからのファイルのサポートを参照してリストアできます

前述のように、参照および復元操作用のコンテナが追加されたことで、Google CloudおよびStorageGRID システムに保存されているバックアップファイルからファイルの復元操作を実行できるようになりました。現在は、参照とリストアを使用して、すべてのパブリッククラウドプロバイダとStorageGRID からファイルをリストアできます。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#restoring-ontap-data-using-browse-restore["参照リストアを使用してONTAP バックアップからボリュームとファイルをリストアする方法を参照してください"]。



=== ドラッグアンドドロップして、Cloud Backup to S3ストレージを有効にします

バックアップのAmazon S3デスティネーションがキャンバス上の作業環境として存在する場合、オンプレミスのONTAP クラスタまたはCloud Volumes ONTAP システム（AWSにインストール）をAmazon S3作業環境にドラッグしてセットアップウィザードを開始できます。



=== Kubernetesクラスタ内に新しく作成されたボリュームにバックアップポリシーを自動的に適用します

Cloud Backupをアクティブ化したあとにKubernetesクラスタに新しい永続ボリュームを追加した場合は、以前にそれらのボリュームのバックアップを忘れずに設定する必要がありました。新しく作成したボリュームに自動的に適用するポリシーを選択できます https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-kubernetes.html#setting-a-backup-policy-to-be-assigned-to-new-volumes["[バックアップ設定]ページから選択します"] Cloud Backupをすでにアクティブ化しているクラスタの場合



=== Cloud Backup APIを使用して、バックアップとリストアの処理を管理できるようになりました

APIはにあります https://docs.netapp.com/us-en/cloud-manager-automation/cbs/overview.html[]。を参照してください link:api-backup-restore.html["このページです"] を参照してください。



== 2022年5月2日



=== Google Cloud Storageのバックアップファイルで検索とリストアがサポートされるようになりました

ボリュームとファイルをリストアするための検索とリストアの方法は、AWSにバックアップファイルを格納するユーザ向けに4月に導入されました。Google Cloud Storageにバックアップファイルを保存するユーザーがこの機能を使用できるようになりました。 https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#prerequisites-2["Search  Restoreを使用してボリュームとファイルをリストアする方法を参照してください"]。



=== Kubernetesクラスタ内に新しく作成されたボリュームにバックアップポリシーが自動的に適用されるように設定します

Cloud Backupをアクティブ化したあとにKubernetesクラスタに新しい永続ボリュームを追加した場合は、以前にそれらのボリュームのバックアップを忘れずに設定する必要がありました。新しく作成したボリュームに自動的に適用するポリシーを選択できます。このオプションは、新しいKubernetesクラスタに対してCloud Backupをアクティブ化するときにセットアップウィザードで使用できます。



=== Cloud Backupを作業環境でアクティブ化するには、ライセンスが必要になります

Cloud Backupのライセンスの実装方法には、次の点が変更されています。

* Cloud Backupをアクティブ化するには、クラウドプロバイダからPAYGO Marketplaceサブスクリプションに登録するか、ネットアップからBYOLライセンスを購入する必要があります。
* 30日間無償トライアルは、クラウドプロバイダがPAYGOサブスクリプションを使用している場合にのみ利用できます。BYOLライセンスを使用している場合は利用できません。
* 無料トライアルは、Marketplaceのサブスクリプションが開始された日から開始されます。たとえば、Cloud Volumes ONTAP システムのMarketplaceサブスクリプションを30日間使用した後で無料トライアルを有効にした場合、クラウドバックアップトライアルは利用できません。


https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-licensing-cloud-backup.html["使用可能なライセンスモデルの詳細については、こちらをご覧ください"]。



== 2022 年 4 月 4 日



=== Cloud Backup for Applications 1.1.0 （ SnapCenter 搭載）の GA 版になりました

新しいCloud Backup for Applications機能を使用すると、OracleおよびMicrosoft SQLの既存のアプリケーション整合性スナップショット（バックアップ）を、オンプレミスのプライマリストレージからAmazon S3またはAzure Blobのクラウドオブジェクトストレージにオフロードできます。

必要に応じて、クラウドからオンプレミスへデータをリストアできます。

link:concept-protect-app-data-to-cloud.html["オンプレミスアプリケーションのデータをクラウドで保護する方法については、こちらをご覧ください"]。



=== すべての ONTAP バックアップファイルでボリュームまたはファイルを検索するための新しい検索とリストア機能

ボリューム名またはフルボリューム名、部分的またはフルファイル名、サイズ範囲、および追加の検索フィルタを使用して、すべての ONTAP バックアップファイル * にまたがるボリュームまたはファイルを検索できるようになりました。これは、どのクラスタまたはボリュームがデータのソースであるかがわからない場合に、リストアするデータを見つけるための新しい優れた方法です。 link:task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["検索とリストアの使用方法を説明します"]。



== 2022 年 3 月 3 日



=== GKE Kubernetes クラスタから Google Cloud ストレージに永続ボリュームをバックアップする機能

ネットアップ Astra Trident がインストールされている GKE クラスタで、 Cloud Volumes ONTAP for GCP をクラスタのバックエンドストレージとして使用している場合は、 Google Cloud ストレージとの間で永続的ボリュームのバックアップとリストアを行うことができます。 link:task-backup-kubernetes-to-gcp.html["詳細については、こちらをご覧ください"]。



=== Cloud Data Sense を使用して Cloud Backup ファイルをスキャンするベータ機能は、本リリースでは廃止されました



== 2022 年 2 月 14 日



=== バックアップポリシーを単一クラスタ内の個々のボリュームに割り当てることができるようになりました

これまでは、クラスタ内のすべてのボリュームに割り当てることができるバックアップポリシーは 1 つだけでした。1 つのクラスタに複数のバックアップポリシーを作成し、異なるボリュームに異なるポリシーを適用できるようになりました。 link:task-manage-backups-ontap#changing-the-policy-assigned-to-existing-volumes["クラスタの新しいバックアップポリシーを作成し、選択したボリュームに割り当てる方法を参照してください"]。



=== 新しいオプションを使用すると、新規に作成されたボリュームにデフォルトのバックアップポリシーを自動的に適用できます

以前は、 Cloud Backup をアクティブ化したあとに作業環境で作成した新しいボリュームには、バックアップポリシーを手動で適用する必要がありました。これで、 Cloud Manager 、 System Manager 、 CLI 、または API を使用してボリュームを作成したかどうかに関係なく、 Cloud Backup はボリュームを検出し、デフォルトポリシーとして選択したバックアップポリシーを適用します。

このオプションは、新しい作業環境でバックアップを有効にする場合、または既存の作業環境で _ ボリュームの管理 _ ページから有効にする場合に使用できます。



=== すべてのバックアップジョブとリストアジョブの処理中ステータスを確認するには、新しいジョブモニタを使用できます

ジョブモニタは、バックアップポリシーの変更やバックアップの削除など、複数のボリュームに対して処理を開始した場合に非常に役立ちます。そのため、すべてのボリュームで処理が完了したことを確認できます。 link:task-monitor-backup-jobs.html["「ジョブモニタの使用方法」を参照してください"]。



== 2022 年 1 月 2 日



=== AKS Kubernetes クラスタから Azure BLOB ストレージに永続ボリュームをバックアップする機能

AKS クラスタに NetApp Astra Trident がインストールされていて、クラスタのバックエンドストレージとして Cloud Volumes ONTAP for Azure を使用している場合、 Azure BLOB ストレージとのボリュームをバックアップおよびリストアできます。 link:task-backup-kubernetes-to-azure.html["詳細については、こちらをご覧ください"]。



=== このリリースでは、業界標準に合わせて Cloud Backup Service の料金が変更されています

バックアップファイルのサイズに基づいてネットアップに容量を支払う代わりに、バックアップ対象のソース ONTAP ボリュームの論理使用容量（ ONTAP の効率化前）で計算された、保護対象のデータにのみ料金が発生します。この容量はフロントエンドテラバイト（ FETB ）とも呼ばれます。



== 2021 年 11 月 28 日



=== EKS Kubernetes クラスタから Amazon S3 に永続ボリュームをバックアップできます

EKS クラスタに NetApp Astra Trident がインストールされていて、クラスタのバックエンドストレージとして Cloud Volumes ONTAP for AWS を使用している場合、 Amazon S3 との間でボリュームをバックアップおよびリストアできます。 link:task-backup-kubernetes-to-s3.html["詳細については、こちらをご覧ください"]。



=== DP ボリュームのバックアップ機能が強化されました

Cloud Backup で、 SVM-DR 関係のターゲット ONTAP システムに存在する DP ボリュームのバックアップの作成がサポートされるようになりました。いくつかの制限事項があります。を参照してください link:concept-ontap-backup-to-cloud.html#limitations["制限事項"] を参照してください。



== 2021 年 11 月 5 日



=== オンプレミスの ONTAP システムにボリュームをリストアする際にプライベートエンドポイントを選択できます

Amazon S3 または Azure Blob にあるバックアップファイルからオンプレミスの ONTAP システムにボリュームをリストアする場合、オンプレミスシステムに接続するプライベートかつセキュアなプライベートエンドポイントを選択できるようになりました。



=== 古いバックアップファイルを数日後にアーカイブストレージに階層化してコストを削減できるようになりました

クラスタで ONTAP 9.10.1 以降が実行されており、 AWS または Azure クラウドストレージを使用している場合に、アーカイブストレージへのバックアップの階層化を有効にすることができます。詳細については、を参照してください link:reference-aws-backup-tiers.html["AWS S3 アーカイブストレージクラス"] および link:reference-azure-backup-tiers.html["Azure BLOB アーカイブアクセス層"]。



=== Cloud Backup BYOL ライセンスが、 Digital Wallet の Data Services Licenses タブに移動しました

Cloud Backup の BYOL ライセンスが、 Cloud Manager Digital Wallet の Cloud Backup Licenses タブから Data Services Licenses タブに移動しました。



== 2021 年 10 月 4 日



=== ボリュームまたはファイルのリストアを実行するときに、バックアップページでバックアップファイルのサイズを確認できるようになりました

これは、不要な大容量のバックアップファイルを削除する場合や、バックアップファイルのサイズを比較して、悪意のあるソフトウェア攻撃の結果として発生する可能性のある異常なバックアップファイルを特定する場合に便利です。



=== クラウドバックアップのコストを比較するための TCO 計算ツールが用意されています

総所有コスト計算ツールを使用すると、 Cloud Backup の総所有コストを把握し、これらのコストを従来のバックアップソリューションと比較して、削減可能なコストを見積もることができます。ご確認くださいhttps://cloud.netapp.com/cloud-backup-service-tco-calculator["こちらをご覧ください"^]。



=== 作業環境に対する Cloud Backup の登録を解除する機能

これで、簡単に実現できます link:task_manage_backups.html#unregistering-cloud-backup-for-a-working-environment["作業環境での Cloud Backup の登録を解除します"] その作業環境でバックアップ機能を使用しない（または課金される）場合。



== 2021 年 9 月 2 日



=== ボリュームのオンデマンドバックアップを作成する機能

オンデマンドバックアップをいつでも作成して、ボリュームの現在の状態をキャプチャできるようになりました。これは、ボリュームに重要な変更が加えられており、次のスケジュールされたバックアップがそのデータを保護するのを待つ必要がない場合に便利です。

link:task-manage-backups-ontap.html#creating-a-manual-volume-backup-at-any-time["オンデマンドバックアップの作成方法を参照してください"]。



=== プライベートインターフェイス接続を定義して、 Amazon S3 へのセキュアなバックアップを実現できる

オンプレミスの ONTAP システムから Amazon S3 へのバックアップを設定する際に、アクティブ化ウィザードでプライベートインターフェイスエンドポイントへの接続を定義できるようになりました。これにより、オンプレミスシステムをプライベートかつセキュアに接続するネットワークインターフェイスを、 AWS PrivateLink を基盤とするサービスに使用できるようになります。 link:task-backup-onprem-to-aws.html#preparing-amazon-s3-for-backups["このオプションの詳細を参照してください"]。



=== Amazon S3 にデータをバックアップする際に、お客様が管理する独自のキーをデータ暗号化用に選択できるようになりました

セキュリティと制御を強化するために、デフォルトの Amazon S3 暗号化キーを使用する代わりに、アクティブ化ウィザードでお客様が管理するデータ暗号化キーを選択できます。オンプレミスの ONTAP システムまたは AWS の Cloud Volumes ONTAP システムからバックアップを設定する場合に使用できます。



=== 30 、 000 を超えるファイルを含むディレクトリからファイルをリストアできるようになりました
