= ボリューム移行のためのSnapMirrorからクラウドへの再同期
:allow-uri-read: 




=== ボリューム移行のためのSnapMirrorからクラウドへの再同期

SnapMirrorからクラウドへの再同期機能は、NetApp環境でのボリューム移行時のデータ保護と継続性を合理化します。SnapMirror論理レプリケーション（LRSE）を使用して、オンプレミスのNetApp環境から別の環境、またはCloud Volumes ONTAPやCloud Volumes Serviceなどのクラウドベースのソリューションにボリュームを移行する場合、SnapMirrorからクラウドへの再同期により、既存のクラウドバックアップに影響を与えずに運用できます。

この機能により、時間とリソースを大量に消費するベースライン再処理が不要になり、移行後もバックアップ処理を継続できます。この機能は、FlexVolとFlexGroupの両方をサポートするワークロードマイグレーションシナリオで役立ちます。ONTAPバージョン9.16.1以降で使用できます。

SnapMirrorからクラウドへの再同期は、環境全体でバックアップの継続性を維持することで運用効率を高め、ハイブリッドクラウドやマルチクラウドのデータ管理の複雑さを軽減します。

再同期処理の実行方法の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-migrate-volumes-snapmirror-cloud-resync.html["SnapMirrorを使用したボリュームのクラウドへの再同期"]。



=== サードパーティ製MinIOオブジェクトストアのサポート（プレビュー）

BlueXP  のバックアップとリカバリでは、MinIOを中心にサードパーティのオブジェクトストアもサポートされるようになりました。この新しいプレビュー機能を使用すると、バックアップとリカバリのニーズに合わせてS3互換オブジェクトストアを活用できます。

このプレビュー版では、すべての機能がリリースされる前に、サードパーティのオブジェクトストアとの強固な統合を確保したいと考えています。この新しい機能について検討し、サービスの強化に役立つフィードバックを提供することをお勧めします。


IMPORTANT: この機能は本番環境では使用しないでください。

*プレビューモードの制限*

この機能はプレビュー中ですが、次のような制限があります。

* Bring Your Own Bucket（BYOB）はサポートされていません。
* ポリシーでDataLockを有効にすることはできません。
* ポリシーでアーカイブモードを有効にすることはできません。
* オンプレミスのONTAP環境のみがサポートされます。
* MetroClusterはサポートされていません。
* バケットレベルの暗号化を有効にするオプションはサポートされていません。


* はじめに *

このプレビュー機能を使用するには、BlueXP  コネクタでフラグを有効にする必要があります。その後、バックアップセクションで*サードパーティ互換*オブジェクトストアを選択して、MinIOのサードパーティオブジェクトストアの接続の詳細を保護ワークフローに入力できます。

プレビュー機能を有効にする方法については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/task-preview-enable.html["BlueXP  バックアップ/リカバリのプレビュー機能を有効にする"]。
