= 高性能な索引付け
:allow-uri-read: 




=== 高性能な索引付け

BlueXP  のバックアップとリカバリでは、ソース作業環境上のデータのインデックス作成を効率化する、更新されたインデックス作成機能が導入されています。新しいインデックス作成機能には、UIの更新、データをリストアするSearch & Restore方式のパフォーマンスの向上、グローバル検索機能のアップグレード、拡張性の向上が含まれています。

改善点の内訳は次のとおりです。

* *フォルダ統合*:更新されたバージョンでは、特定の識別子を含む名前を使用してフォルダがグループ化されるため、インデックス作成プロセスがスムーズになります。
* *寄木細工ファイルの圧縮*:更新されたバージョンは、各ボリュームのインデックス作成に使用されるファイルの数を減らし、プロセスを簡素化し、余分なデータベースを必要としません。
* *より多くのセッションでスケールアウト*：新しいバージョンでは、インデックス作成タスクを処理するためのセッションが追加され、プロセスが高速化されます。
* *複数のインデックスコンテナのサポート*：新しいバージョンでは、複数のコンテナを使用してインデックスタスクの管理と分散を強化しています。
* *インデックスの分割ワークフロー*:新しいバージョンでは、インデックス作成プロセスが2つの部分に分割され、効率が向上しています。
* *同時実行性の向上*:新しいバージョンでは、ディレクトリの削除や移動を同時に行うことができるため、インデックス作成プロセスが高速化されます。


.この機能を利用できるのは誰ですか？
新しいインデックス作成機能は、すべての新規顧客が利用できます。

.インデックス作成を有効にするにはどうすればよいですか。
データのリストアにSearch & Restore方式を使用する前に、ボリュームまたはファイルのリストア元となる各ソース作業環境で[Indexing]を有効にする必要があります。これにより、インデックスカタログはすべてのボリュームとすべてのバックアップファイルを追跡できるため、検索が迅速かつ効率的になります。

検索とリストアの実行時に[Enable Indexing]オプションを選択して、ソースの作業環境でインデックス作成を有効にします。

詳細については、のドキュメントを参照して https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["検索と復元を使用してONTAPデータを復元する方法"]ください。

.サポートされるスケール
新しいインデックス作成機能では、次の機能がサポートされています。

* 3分未満でグローバル検索を効率化
* 最大50億個のファイル
* クラスタあたり最大5、000個のボリューム
* ボリュームあたり最大100Kのスナップショット
* ベースラインインデックス作成の最大時間は7日未満です。実際の時間は環境によって異なります。




=== グローバル検索のパフォーマンスの向上

このリリースでは、グローバル検索のパフォーマンスも強化されています。これで、進行状況インジケータと、ファイルの数や検索にかかった時間など、より詳細な検索結果が表示されます。検索とインデックス作成用の専用コンテナにより、グローバル検索が5分以内に完了します。

グローバル検索に関連する次の考慮事項に注意してください。

* 新しいインデックスは、hourlyとラベル付けされたスナップショットでは実行されません。
* 新しいインデックス機能は、FlexVol上のSnapshotに対してのみ機能し、FlexGroup上のSnapshotに対しては機能しません。

