= 強化されたONTAPボリュームダッシュボード
:allow-uri-read: 




=== 強化されたONTAPボリュームダッシュボード

2025 年 4 月には、はるかに高速で効率的な、強化されたONTAPボリューム ダッシュボードのプレビューをリリースしました。

このダッシュボードは、多数のワークロードを抱えるエンタープライズのお客様を支援するために設計されました。20,000ボリュームのお客様でも、新しいダッシュボードは10秒未満で読み込まれます。

プレビューが成功し、プレビュー版のお客様から素晴らしいフィードバックをいただいたことを受け、この度、すべてのお客様のデフォルトエクスペリエンスとして提供することになりました。驚異的な速さを誇るダッシュボードをご体験ください。

詳細については、を参照してください link:br-use-dashboard.html["ダッシュボードで保護の状態を確認する"]。



=== パブリック テクノロジー プレビューとしての Microsoft SQL Server ワークロード サポート

BlueXP backup and recoveryのこのリリースでは、 BlueXP backup and recoveryサービスでお馴染みの3-2-1保護戦略を用いてMicrosoft SQL Serverワークロードを管理できる、更新されたユーザーインターフェースが提供されます。この新バージョンでは、これらのワークロードをプライマリストレージにバックアップし、セカンダリストレージに複製し、クラウドオブジェクトストレージにバックアップすることが可能です。

プレビューにサインアップするには、こちらに記入してください https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["プレビュー登録フォーム"^] 。


NOTE: MICROSOFT SQL SERVER ワークロードの保護に関するこのドキュメントは、テクノロジ プレビューとして提供されています。このプレビューサービスでは、NetAppは、一般提供前にサービスの詳細、内容、スケジュールを変更する権利を留保します。

このバージョンのBlueXP backup and recoveryには、次の更新が含まれています。

* *3-2-1 バックアップ機能*: このバージョンではSnapCenter機能が統合されており、 BlueXP backup and recoveryユーザー インターフェイスから 3-2-1 データ保護戦略を使用してSnapCenterリソースを管理および保護できます。
* * SnapCenterからのインポート*: SnapCenter のバックアップ データとポリシーをBlueXP backup and recoveryにインポートできます。
* *再設計されたユーザー インターフェイス* により、バックアップおよびリカバリ タスクをより直感的に管理できるようになります。
* *バックアップ ターゲット*: Amazon Web Services (AWS)、Microsoft Azure Blob Storage、 StorageGRID、 ONTAP S3 環境にバケットを追加して、Microsoft SQL Server ワークロードのバックアップ ターゲットとして使用できます。
* *ワークロードのサポート*: このバージョンでは、Microsoft SQL Server データベースと可用性グループのバックアップ、復元、検証、クローン作成が可能です。(他のワークロードのサポートは、今後のリリースで追加される予定です。)
* *柔軟な復元オプション*: このバージョンでは、破損や偶発的なデータ損失が発生した場合に、データベースを元の場所と別の場所の両方に復元できます。
* *即時の実稼働コピー*: 開発、テスト、分析用のスペース効率の高い実稼働コピーを、数時間または数日ではなく数分で生成します。
* このバージョンには、詳細なレポートを作成する機能が含まれています。


Microsoft SQL Server ワークロードの保護の詳細については、以下を参照してください。 link:br-use-mssql-protect-overview.html["Microsoft SQL Server ワークロードの保護の概要"] 。
