= ボリュームダッシュボードの強化（プレビュー）
:allow-uri-read: 




=== ボリュームダッシュボードの強化（プレビュー）

ボリュームダッシュボードが10秒未満でロードされるようになり、インターフェイスの速度と効率が大幅に向上しました。このプレビュー版は一部のお客様にご利用いただけ、これらの改善点をいち早くご紹介しています。



=== UIの改善

このリリースでは、インターフェイスが簡素化され、操作性が向上しています。

* [Volumes]テーブルから[Aggregate]列を削除し、[V2]ダッシュボードの[Volume]テーブルから[Snapshot Policy]列、[Backup Policy]列、および[Replication Policy]列を削除すると、レイアウトがより効率的になります。
* アクティブ化されていない作業環境をドロップダウンリストから除外すると、インターフェイスがすっきりし、ナビゲーションが効率的になり、読み込みが高速になります。
* [タグ]列でのソートが無効になっていても、タグを表示できるため、重要な情報に簡単にアクセスできます。
* 保護アイコンのラベルを削除すると、見た目がきれいになり、ロード時間が短縮されます。
* 作業環境のアクティブ化プロセスでは、検出プロセスが完了するまでダイアログボックスにロードアイコンが表示されてフィードバックが提供されるため、システムの運用の透明性と信頼性が向上します。




=== サードパーティ製Wasabiオブジェクトストアのサポート（プレビュー）

BlueXP  のバックアップとリカバリでは、Wasabiを中心にサードパーティのオブジェクトストアのサポートが拡張されました。この新しいプレビュー機能を使用すると、バックアップとリカバリのニーズに合わせてS3互換オブジェクトストアを活用できます。



==== Wasabiの使用を開始する

この機能の使用を開始するには、BlueXP  UIでフラグを有効にする必要があります。その後、サードパーティオブジェクトストアの接続の詳細を入力し、バックアップとリカバリのワークフローに統合できます。



==== プレビューモードの制限事項

この機能のプレビュー中は、次の制限事項を考慮してください。

* Bring Your Own Bucket（BYOB）はサポートされていません。
* ポリシーでDataLockを有効にすることはできません。
* ポリシーでアーカイブモードを有効にすることはできません。
* オンプレミスのONTAP環境のみがサポートされます。
* MetroClusterはサポートされていません。
* バケットレベルの暗号化を有効にするオプションはサポートされていません。


このプレビューでは、すべての機能をリリースする前に、この新機能について確認し、サードパーティのオブジェクトストアとの統合に関するフィードバックをお寄せいただくことを推奨します。
