= インデックスカタログのサポートの更新
:allow-uri-read: 




=== インデックスカタログのサポートの更新

2025年2月、データ復元の「検索と復元」メソッドで使用するインデックス作成機能のアップデート（インデックスカタログv2）を導入しました。前回のリリースでは、オンプレミス環境におけるデータインデックス作成のパフォーマンスが大幅に向上しました。今回のリリースでは、Amazon Web Services、Microsoft Azure、Google Cloud Platform（GCP）環境でインデックスカタログがご利用いただけるようになりました。

新規のお客様の場合、すべての新規環境では Indexed Catalog v2 がデフォルトで有効になっています。既存のお客様の場合は、環境のインデックスを再作成することで Indexed Catalog v2 を活用できます。

.インデックス作成を有効にするにはどうすればよいですか。
データのリストアにSearch & Restore方式を使用する前に、ボリュームまたはファイルのリストア元となる各ソース作業環境で[Indexing]を有効にする必要があります。検索と復元を実行するときは、「*インデックスを有効にする*」オプションを選択します。

インデックスカタログはすべてのボリュームとバックアップ ファイルを追跡できるため、検索が迅速かつ効率的になります。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["検索と復元のインデックスを有効にする"]。



=== Azure プライベート リンク エンドポイントとサービス エンドポイント

通常、 BlueXP backup and recoveryでは、保護タスクを処理するためにクラウド プロバイダーとのプライベート エンドポイントを確立します。今回のリリースでは、BlueXP バックアップ＆リカバリによるプライベートエンドポイントの自動作成を有効または無効にできるオプション設定が導入されました。これは、プライベートエンドポイントの作成プロセスをより細かく制御したい場合に役立ちます。

保護を有効にするとき、または復元プロセスを開始するときに、このオプションを有効または無効にすることができます。

この設定を無効にすると、BlueXP のバックアップとリカバリが正常に機能するために、プライベートエンドポイントを手動で作成する必要があります。適切な接続がないと、バックアップとリカバリのタスクを正常に実行できない可能性があります。



=== ONTAP S3 での SnapMirror からクラウドへの再同期のサポート

前回のリリースでは、SnapMirror to Cloud Resync（SM-C Resync）のサポートが導入されました。この機能は、NetApp環境におけるボリューム移行時のデータ保護を効率化します。今回のリリースでは、ONTAP S3に加え、WasabiやMinIOなどの他のS3互換プロバイダーでもSM-C Resyncのサポートが追加されました。



=== StorageGRID 用の独自のバケットを用意する

作業環境のオブジェクトストレージにバックアップファイルを作成すると、BlueXP バックアップ＆リカバリはデフォルトで、ユーザーが設定したオブジェクトストレージアカウント内にバックアップファイル用のコンテナ（バケットまたはストレージアカウント）を作成します。以前は、この設定をオーバーライドして、Amazon S3、Azure Blob Storage、Google Cloud Storage 用の独自のコンテナを指定できました。今回のリリースでは、独自の StorageGRID オブジェクトストレージコンテナを使用できるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-protect-journey.html["独自のオブジェクトストレージコンテナを作成する"]
