= UIの改善
:allow-uri-read: 




=== UIの改善

このリリースでは、インターフェイスが簡素化され、操作性が向上しています。

* [Volumes]テーブルから[Aggregate]列を削除し、[V2]ダッシュボードの[Volume]テーブルから[Snapshot Policy]列、[Backup Policy]列、および[Replication Policy]列を削除すると、レイアウトがより効率的になります。
* アクティブ化されていない作業環境をドロップダウンリストから除外すると、インターフェイスがすっきりし、ナビゲーションが効率的になり、読み込みが高速になります。
* [タグ]列でのソートが無効になっていても、タグを表示できるため、重要な情報に簡単にアクセスできます。
* 保護アイコンのラベルを削除すると、見た目がきれいになり、ロード時間が短縮されます。
* 作業環境のアクティブ化プロセスでは、検出プロセスが完了するまでダイアログボックスにロードアイコンが表示されてフィードバックが提供されるため、システムの運用の透明性と信頼性が向上します。




=== ボリュームダッシュボードの強化（プレビュー）

ボリュームダッシュボードが10秒未満でロードされるようになり、インターフェイスの速度と効率が大幅に向上しました。このプレビュー版は一部のお客様にご利用いただけ、これらの改善点をいち早くご紹介しています。



=== サードパーティ製Wasabiオブジェクトストアのサポート（プレビュー）

BlueXP  のバックアップとリカバリでは、Wasabiを中心にサードパーティのオブジェクトストアのサポートが拡張されました。この新しいプレビュー機能を使用すると、バックアップとリカバリのニーズに合わせてS3互換オブジェクトストアを活用できます。



==== Wasabiの使用を開始する

サードパーティ製ストレージをオブジェクトストアとして使用するには、BlueXP  Connectorでフラグを有効にする必要があります。その後、サードパーティオブジェクトストアの接続の詳細を入力し、バックアップとリカバリのワークフローに統合できます。

.手順
. コネクタにSSH接続します。
. BlueXP  バックアップとリカバリのCBSサーバコンテナに移動します。
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. Vimまたはその他のエディタを使用して、フォルダ内のファイルを `config`開き `default.json`ます。
+
[listing]
----
vi default.json
----
. 「：false」を「true」に `allow-s3-compatible`変更し `allow-s3-compatible`ます。
. 変更を保存します。
. コンテナを終了します。
. BlueXP  バックアップおよびリカバリCBSサーバコンテナを再起動します。


.結果
コンテナが再びオンになったら、BlueXP  バックアップとリカバリのUIを開きます。バックアップを開始するか、バックアップ戦略を編集すると、新しいプロバイダ「S3 Compatible」が、AWS、Microsoft Azure、Google Cloud、StorageGRID、ONTAP S3の他のバックアッププロバイダとともにリストされます。



==== プレビューモードの制限事項

この機能のプレビュー中は、次の制限事項を考慮してください。

* Bring Your Own Bucket（BYOB）はサポートされていません。
* ポリシーでDataLockを有効にすることはできません。
* ポリシーでアーカイブモードを有効にすることはできません。
* オンプレミスのONTAP環境のみがサポートされます。
* MetroClusterはサポートされていません。
* バケットレベルの暗号化を有効にするオプションはサポートされていません。


このプレビューでは、すべての機能をリリースする前に、この新機能について確認し、サードパーティのオブジェクトストアとの統合に関するフィードバックをお寄せいただくことを推奨します。
